import type { BopObject, BopDependency } from "@/lib/bop/types/objects";
import { OPS_SCREEN_OBJECTS, OPS_API_OBJECTS, OPS_TABLE_OBJECTS, OPS_DEPENDENCIES } from "./ops";

export const SCREEN_OBJECTS: BopObject[] = [
  { object_id:"screen:AI001",type:"screen",module:"AIM",name:"AI Command Center",route:"/console/ai/command",status:"active" },
  { object_id:"screen:AI002",type:"screen",module:"AIM",name:"Tool Registry",route:"/console/ai/tools",status:"active" },
  { object_id:"screen:AI003",type:"screen",module:"AIM",name:"Prompt Manager",route:"/console/ai/prompts",status:"active" },
  { object_id:"screen:AI004",type:"screen",module:"AIM",name:"AI Action Audit",route:"/console/ai/audit",status:"active" },
  { object_id:"screen:AI005",type:"screen",module:"AIM",name:"Model Configuration",route:"/console/ai/models",status:"active" },
  { object_id:"screen:AS001",type:"screen",module:"AST",name:"Inventory",route:"/console/ast/inventory",status:"active" },
  { object_id:"screen:AS002",type:"screen",module:"AST",name:"Vehicle 360",route:"/console/ast/inventory/[id]",status:"active" },
  { object_id:"screen:AS003",type:"screen",module:"AST",name:"Lifecycle Tracker",route:"/console/inventory/lifecycle",status:"planned" },
  { object_id:"screen:AS004",type:"screen",module:"AST",name:"Cost Tracker",route:"/console/inventory/costs",status:"planned" },
  { object_id:"screen:CR001",type:"screen",module:"CRM",name:"Leads",route:"/console/crm/leads",status:"active" },
  { object_id:"screen:CR002",type:"screen",module:"CRM",name:"Lead Detail",route:"/console/crm/leads/[id]",status:"active" },
  { object_id:"screen:CR003",type:"screen",module:"CRM",name:"Lead Statistics",route:"/console/crm/lead-stats",status:"active" },
  { object_id:"screen:CR004",type:"screen",module:"CRM",name:"Activities",route:"/console/crm/activities",status:"active" },
  { object_id:"screen:CR006",type:"screen",module:"CRM",name:"Pipeline Kanban",route:"/console/crm/kanban",status:"active" },
  { object_id:"screen:SY030",type:"screen",module:"SYS",name:"Development Group",route:"/console/sys/group/dev",status:"active" },
  { object_id:"screen:SY031",type:"screen",module:"SYS",name:"Integration Group",route:"/console/sys/group/int",status:"active" },
  { object_id:"screen:SY013",type:"screen",module:"SYS",name:"Counters",route:"/console/sys/counters",status:"active" },
  { object_id:"screen:SY010",type:"screen",module:"SYS",name:"Google Drive Storage",route:"/console/sys/drive",status:"active" },
  { object_id:"api:st/accounts:GET",type:"api",module:"SYS",name:"GET Drive Accounts",route:"/api/bop/st/accounts",status:"active" },
  { object_id:"api:st/files:GET",type:"api",module:"SYS",name:"GET Drive Files",route:"/api/bop/st/files",status:"active" },
  { object_id:"api:st/files:POST",type:"api",module:"SYS",name:"Upload Drive File",route:"/api/bop/st/files",status:"active" },
  { object_id:"api:st/files/[fileId]:DELETE",type:"api",module:"SYS",name:"Trash Drive File",route:"/api/bop/st/files/[fileId]",status:"active" },
  { object_id:"api:st/files/[fileId]/download:GET",type:"api",module:"SYS",name:"Download Drive File",route:"/api/bop/st/files/[fileId]/download",status:"active" },
  { object_id:"api:st/oauth/start:GET",type:"api",module:"SYS",name:"Drive OAuth Start",route:"/api/bop/st/oauth/start",status:"active" },
  { object_id:"api:st/oauth/callback:GET",type:"api",module:"SYS",name:"Drive OAuth Callback",route:"/api/bop/st/oauth/callback",status:"active" },
  { object_id:"table:st_drive_accounts",type:"table",module:"SYS",name:"st_drive_accounts",status:"active",description:"Per-tenant Google Drive OAuth connections (BOP-owned, standalone)" },
  { object_id:"table:st_files",type:"table",module:"SYS",name:"st_files",status:"active",description:"Index of files BOP manages in tenant Google Drives" },
  { object_id:"api:sys/counters:GET",type:"api",module:"SYS",name:"List Counters",route:"/api/bop/sys/counters",status:"active" },
  { object_id:"api:sys/counters:PUT",type:"api",module:"SYS",name:"Update Counter",route:"/api/bop/sys/counters",status:"active" },
  { object_id:"api:sys/counters:POST",type:"api",module:"SYS",name:"Create Counter",route:"/api/bop/sys/counters",status:"active" },
  { object_id:"api:sys/counters:DELETE",type:"api",module:"SYS",name:"Delete Counter",route:"/api/bop/sys/counters",status:"active" },
  { object_id:"screen:SY032",type:"screen",module:"SYS",name:"Lock Monitor",route:"/console/sys/locks",status:"active" },
  { object_id:"api:sys/locks:GET",type:"api",module:"SYS",name:"List Object Locks",route:"/api/bop/sys/locks",status:"active" },
  { object_id:"api:sys/locks:POST",type:"api",module:"SYS",name:"Acquire Object Lock",route:"/api/bop/sys/locks",status:"active" },
  { object_id:"api:sys/locks:PUT",type:"api",module:"SYS",name:"Heartbeat Object Lock",route:"/api/bop/sys/locks",status:"active" },
  { object_id:"api:sys/locks:DELETE",type:"api",module:"SYS",name:"Release Object Lock",route:"/api/bop/sys/locks",status:"active" },
  { object_id:"screen:DV001",type:"screen",module:"DEV",name:"Dev Dashboard",route:"/console/dev",status:"active" },
  { object_id:"screen:DV002",type:"screen",module:"DEV",name:"Enhancements",route:"/console/dev/enhancements",status:"active" },
  { object_id:"screen:DV003",type:"screen",module:"DEV",name:"Production Queue",route:"/console/dev/queue",status:"active" },
  { object_id:"screen:DV004",type:"screen",module:"DEV",name:"Commits",route:"/console/dev/commits",status:"active" },
  { object_id:"screen:DV005",type:"screen",module:"DEV",name:"Releases",route:"/console/dev/releases",status:"stub" },
  { object_id:"screen:DV006",type:"screen",module:"DEV",name:"Deployments",route:"/console/dev/deployments",status:"stub" },
  { object_id:"screen:FI001",type:"screen",module:"FIN",name:"BTW Quick Calc",route:"/console/fin/invoices",status:"active" },
  { object_id:"screen:FI002",type:"screen",module:"FIN",name:"Payment Tracking",route:"/console/fin/payments",status:"active" },
  { object_id:"screen:FI005",type:"screen",module:"FIN",name:"Kosten",route:"/console/fin/expenses",status:"planned" },
  { object_id:"screen:FI007",type:"screen",module:"FIN",name:"Bon Scanner AI",route:"/console/fin/scanner",status:"planned" },
  { object_id:"screen:FI008",type:"screen",module:"FIN",name:"BTW Assistent AI",route:"/console/fin/assistant",status:"planned" },
  { object_id:"screen:FI009",type:"screen",module:"FIN",name:"Winst en Verlies",route:"/console/fin/pnl",status:"planned" },
  { object_id:"screen:FI011",type:"screen",module:"FIN",name:"Invoice Detail",route:"/console/fin/invoices/[id]",status:"active" },
  { object_id:"screen:FI012",type:"screen",module:"FIN",name:"Supplier Invoices AP",route:"/console/fin/ap",status:"active" },
  { object_id:"screen:IN001",type:"screen",module:"INV",name:"Catalog Overview",route:"/console/ast/catalog",status:"active" },
  { object_id:"screen:IN002",type:"screen",module:"INV",name:"Brands",route:"/console/ast/brands",status:"active" },
  { object_id:"screen:IN003",type:"screen",module:"INV",name:"Listing Categories",route:"/console/ast/categories",status:"active" },
  { object_id:"screen:IN004",type:"screen",module:"INV",name:"Suppliers",route:"/console/ast/suppliers",status:"active" },
  { object_id:"screen:IN005",type:"screen",module:"INV",name:"Publish Structures",route:"/console/ast/structures",status:"active" },
  { object_id:"screen:MD001",type:"screen",module:"MDM",name:"Business Partners",route:"/console/mdm/partners",status:"active" },
  { object_id:"screen:MD002",type:"screen",module:"MDM",name:"Partner Detail",route:"/console/mdm/partners/[id]",status:"active" },
  { object_id:"screen:MD003",type:"screen",module:"MDM",name:"Vehicle Taxonomy",route:"/console/mdm/taxonomy",status:"active" },
  { object_id:"screen:MD004",type:"screen",module:"MDM",name:"Equipment Catalog",route:"/console/master-data/equipment",status:"active" },
  { object_id:"screen:MP001",type:"screen",module:"MKP",name:"Listing Manager",route:"/console/mkp/listings",status:"active" },
  { object_id:"screen:MP002",type:"screen",module:"MKP",name:"Channel Analytics",route:"/console/mkp/analytics",status:"active" },
  { object_id:"screen:MP003",type:"screen",module:"MKP",name:"Listing Detail",route:"/console/mkp/listings/[id]",status:"active" },
  { object_id:"screen:MP004",type:"screen",module:"MKP",name:"Channel Publisher",route:"/console/mkp/publish",status:"active" },
  { object_id:"api:mkp/listings-v2:GET",type:"api",module:"MKP",name:"GET Listings V2 (bop_listings)",route:"/api/bop/mkp/listings-v2",status:"active" },
  { object_id:"api:int/feed/marktplaats:GET",type:"api",module:"INT",name:"Marktplaats Admarkt XML Feed",route:"/api/bop/int/feed/marktplaats",status:"active" },
  { object_id:"screen:MP005",type:"screen",module:"MKP",name:"Layout Manager",route:"/console/mkp/layout-manager",status:"active" },
  { object_id:"screen:AU001",type:"screen",module:"AUC",name:"Auction Manager",route:"/console/mkp/auctions",status:"active" },
  { object_id:"screen:AU002",type:"screen",module:"AUC",name:"Auction Detail",route:"/console/mkp/auctions/[id]",status:"active" },
  { object_id:"screen:AU004",type:"screen",module:"AUC",name:"Bidding Console",route:"/console/mkp/auctions/[id]/bidding",status:"active" },
  { object_id:"screen:MK001",type:"screen",module:"MKT",name:"AI Overview",route:"/console/mkt/overview",status:"planned" },
  { object_id:"screen:MK002",type:"screen",module:"MKT",name:"Market Evaluation",route:"/console/mkt/market",status:"planned" },
  { object_id:"screen:MK005",type:"screen",module:"MKT",name:"Listing Intelligence",route:"/console/mkt/listings",status:"planned" },
  { object_id:"screen:MK006",type:"screen",module:"MKT",name:"AI Campaigns",route:"/console/mkt/campaigns",status:"active" },
  { object_id:"screen:SA001",type:"screen",module:"SAL",name:"Quotations",route:"/console/sal/quotations",status:"active" },
  { object_id:"screen:SA002",type:"screen",module:"SAL",name:"Quotation Detail",route:"/console/sal/quotations/[id]",status:"active" },
  { object_id:"screen:SA009",type:"screen",module:"SAL",name:"Orders",route:"/console/sal/orders",status:"active" },
  { object_id:"screen:SA010",type:"screen",module:"SAL",name:"Order Detail",route:"/console/sal/orders/[id]",status:"active" },
  { object_id:"screen:SA011",type:"screen",module:"SAL",name:"Sales Dashboard",route:"/console/sal/dashboard",status:"active" },
  { object_id:"screen:SA012",type:"screen",module:"SAL",name:"Margin Calculator",route:"/console/sal/margin",status:"active" },
  { object_id:"screen:SA019",type:"screen",module:"SAL",name:"Handovers",route:"/console/sal/handovers",status:"active" },
  { object_id:"screen:SA020",type:"screen",module:"SAL",name:"Handover Detail",route:"/console/sal/handovers/[id]",status:"active" },
  { object_id:"screen:SA021",type:"screen",module:"SAL",name:"Warranties",route:"/console/sal/warranties",status:"active" },
  { object_id:"screen:SA022",type:"screen",module:"SAL",name:"Warranty Detail",route:"/console/sal/warranties/[id]",status:"active" },
  { object_id:"screen:SA023",type:"screen",module:"SAL",name:"Customer Surveys",route:"/console/sal/surveys",status:"active" },
  { object_id:"screen:TR000",type:"screen",module:"SAL",name:"Cases",route:"/console/sal/cases",status:"active" },
  { object_id:"screen:TR001",type:"screen",module:"SAL",name:"Case Detail",route:"/console/sal/cases/[id]",status:"active" },
  { object_id:"screen:SY001",type:"screen",module:"SYS",name:"Users",route:"/console/sys/users",status:"active" },
  { object_id:"screen:SY002",type:"screen",module:"SYS",name:"Role Catalog",route:"/console/sys/roles",status:"active" },
  { object_id:"screen:SY004",type:"screen",module:"SYS",name:"System Settings",route:"/console/sys/settings",status:"active" },
  { object_id:"screen:SY005",type:"screen",module:"SYS",name:"System Health",route:"/console/sys/health",status:"active" },
  { object_id:"screen:SY008",type:"screen",module:"SYS",name:"Admin Dashboard",route:"/console/sys/dashboard",status:"active" },
  { object_id:"screen:SY011",type:"screen",module:"SYS",name:"RBAC Roles",route:"/console/sys/rbac",status:"active" },
  { object_id:"screen:SY012",type:"screen",module:"SYS",name:"Audit Log",route:"/console/sys/audit",status:"active" },
  { object_id:"screen:SY014",type:"screen",module:"SYS",name:"Handoff Doc",route:"/console/sys/handoff",status:"active" },
  { object_id:"screen:SY016",type:"screen",module:"SYS",name:"Access Audit",route:"/console/sys/access-audit",status:"active" },
  { object_id:"screen:SY017",type:"screen",module:"SYS",name:"IMAP Config",route:"/console/sys/imap",status:"active" },
  { object_id:"screen:SY018",type:"screen",module:"SYS",name:"Module Manager",route:"/console/sys/modules",status:"active" },
  { object_id:"screen:SY024",type:"screen",module:"SYS",name:"Screen Explorer",route:"/console/sys/screen-explorer",status:"active" },
  { object_id:"screen:SY028",type:"screen",module:"SYS",name:"Object Explorer",route:"/console/sys/object-explorer",status:"active" },
  { object_id:"screen:MK004",type:"screen",module:"MKT",name:"Brand Voice Profiles",route:"/console/mkt/brands",status:"active" },
  { object_id:"screen:IN006",type:"screen",module:"INV",name:"Model Catalog",route:"/console/ast/models",status:"active" },
  { object_id:"screen:SY036",type:"screen",module:"SYS",name:"Email Style Library",route:"/console/sys/comm/styles",status:"active" },
  { object_id:"screen:SY037",type:"screen",module:"SYS",name:"Automation Engine",route:"/console/sys/comm/automation",status:"active" },
  { object_id:"screen:SY038",type:"screen",module:"SYS",name:"Communication Log",route:"/console/sys/comm/log",status:"active" },
  { object_id:"screen:SY039",type:"screen",module:"SYS",name:"Template Studio",route:"/console/sys/comm/templates",status:"active" },
  { object_id:"screen:SY040",type:"screen",module:"SYS",name:"Support Center",route:"/console/sys/support",status:"active" },
  { object_id:"screen:SY041",type:"screen",module:"SYS",name:"Dealer Applications",route:"/console/sys/dealer-applications",status:"active" },
  { object_id:"screen:SY042",type:"screen",module:"SYS",name:"Quality Inspector",route:"/console/sys/quality",status:"active" },
  { object_id:"screen:SY034",type:"screen",module:"SYS",name:"Documentation Browser",route:"/console/sys/docs",status:"active" },
  { object_id:"screen:SY035",type:"screen",module:"SYS",name:"Flow Map",route:"/console/sys/flow-map",status:"active" },
  { object_id:"screen:SY043",type:"screen",module:"SYS",name:"TFE Flow Viewer",route:"/console/sys/tfe-flow",status:"active" },
  { object_id:"screen:SY051",type:"screen",module:"SYS",name:"Implementation Cockpit",route:"/console/sys/impl",status:"active",description:"Phase/task/deliverable tracking for SY051 program rollout" },
  { object_id:"table:sup_requests",type:"table",module:"SYS",name:"Support Requests",status:"active" },
  { object_id:"table:sup_messages",type:"table",module:"SYS",name:"Support Messages",status:"active" },
  // Workshop module screens
  { object_id:"screen:WK001",type:"screen",module:"WRK",name:"Workshop Dashboard",route:"/console/wrk/dashboard",status:"active" },
  { object_id:"screen:WK002",type:"screen",module:"WRK",name:"Work Orders",route:"/console/wrk/orders",status:"active" },
  { object_id:"screen:WK003",type:"screen",module:"WRK",name:"Planning Board",route:"/console/wrk/planning",status:"active" },
  { object_id:"screen:WK004",type:"screen",module:"WRK",name:"Efficiency KPI",route:"/console/wrk/efficiency",status:"active" },
  { object_id:"screen:WK005",type:"screen",module:"WRK",name:"Inspection Checklist",route:"/console/wrk/inspections",status:"active" },
  { object_id:"screen:WK006",type:"screen",module:"WRK",name:"APK Reminders",route:"/console/wrk/apk-reminders",status:"active" },
  { object_id:"screen:WK007",type:"screen",module:"WRK",name:"Customer Approvals",route:"/console/wrk/approvals",status:"active" },
  { object_id:"screen:WK008",type:"screen",module:"WRK",name:"Customer Status",route:"/console/wrk/status",status:"active" },
  { object_id:"screen:WK009",type:"screen",module:"WRK",name:"Daily Briefing",route:"/console/wrk/briefing",status:"active" },
  { object_id:"screen:WK010",type:"screen",module:"WRK",name:"Repair Recommendations",route:"/console/wrk/recommendations",status:"active" },
  { object_id:"screen:WK011",type:"screen",module:"WRK",name:"Labour Rates",route:"/console/wrk/rates",status:"active" },
  { object_id:"screen:WK012",type:"screen",module:"WRK",name:"Service Packages",route:"/console/wrk/packages",status:"active" },
  { object_id:"screen:WK013",type:"screen",module:"WRK",name:"DMS Integration",route:"/console/wrk/dms-integration",status:"active" },
  // Database Console (DBA)
  { object_id:"module:DBA",type:"module",module:"DBA",name:"Database Console",status:"active" },
  { object_id:"screen:DB001",type:"screen",module:"DBA",name:"Database Overview",route:"/console/dba",status:"active" },
  { object_id:"screen:DB002",type:"screen",module:"DBA",name:"Schema Explorer",route:"/console/dba/schema",status:"active" },
  { object_id:"screen:DB003",type:"screen",module:"DBA",name:"Table Data",route:"/console/dba/data",status:"active" },
  { object_id:"screen:DB004",type:"screen",module:"DBA",name:"SQL Runner",route:"/console/dba/sql",status:"active" },
  { object_id:"screen:DB005",type:"screen",module:"DBA",name:"Functions & RPC",route:"/console/dba/functions",status:"active" },
  { object_id:"screen:DB006",type:"screen",module:"DBA",name:"Database Actions",route:"/console/dba/actions",status:"active" },
  { object_id:"screen:DB007",type:"screen",module:"DBA",name:"Query History",route:"/console/dba/history",status:"active" },
  { object_id:"screen:DB008",type:"screen",module:"DBA",name:"Migrations",route:"/console/dba/migrations",status:"active" },
  { object_id:"screen:DB009",type:"screen",module:"DBA",name:"Database Health",route:"/console/dba/health",status:"active" },
];

export const API_OBJECTS: BopObject[] = [
  { object_id:"api:crm/leads:GET",type:"api",module:"CRM",name:"GET Leads",route:"/api/bop/crm/leads",status:"active" },
  { object_id:"api:crm/leads:POST",type:"api",module:"CRM",name:"Create Lead",route:"/api/bop/crm/leads",status:"active" },
  { object_id:"api:crm/leads/[id]:GET",type:"api",module:"CRM",name:"GET Lead Detail",route:"/api/bop/crm/leads/[id]",status:"active" },
  { object_id:"api:crm/leads/[id]:PATCH",type:"api",module:"CRM",name:"Update Lead",route:"/api/bop/crm/leads/[id]",status:"active" },
  { object_id:"api:crm/leads/[id]:DELETE",type:"api",module:"CRM",name:"Delete Lead",route:"/api/bop/crm/leads/[id]",status:"active" },
  { object_id:"api:crm/activities:GET",type:"api",module:"CRM",name:"GET Activities",route:"/api/bop/crm/activities",status:"active" },
  { object_id:"api:ast/assets:GET",type:"api",module:"AST",name:"GET Assets",route:"/api/bop/ast/assets",status:"active" },
  { object_id:"api:ast/assets:POST",type:"api",module:"AST",name:"Create Asset",route:"/api/bop/ast/assets",status:"active" },
  { object_id:"api:ast/assets/[id]:GET",type:"api",module:"AST",name:"GET Asset Detail",route:"/api/bop/ast/assets/[id]",status:"active" },
  { object_id:"api:ast/costs:GET",type:"api",module:"AST",name:"GET Costs",route:"/api/bop/ast/costs",status:"active" },
  { object_id:"api:ast/lifecycle:GET",type:"api",module:"AST",name:"GET Lifecycle",route:"/api/bop/ast/lifecycle",status:"active" },
  { object_id:"api:fin/invoices:GET",type:"api",module:"FIN",name:"GET Invoices",route:"/api/bop/fin/invoices",status:"active" },
  { object_id:"api:fin/invoices:POST",type:"api",module:"FIN",name:"Create Invoice",route:"/api/bop/fin/invoices",status:"active" },
  { object_id:"api:fin/payments:GET",type:"api",module:"FIN",name:"GET Payments",route:"/api/bop/fin/payments",status:"active" },
  { object_id:"api:fin/ap/invoices:GET",type:"api",module:"FIN",name:"GET AP Invoices",route:"/api/bop/fin/ap/invoices",status:"active" },
  { object_id:"api:mkp/listings:GET",type:"api",module:"MKP",name:"GET Listings",route:"/api/bop/mkp/listings",status:"active" },
  { object_id:"api:mkp/listings:POST",type:"api",module:"MKP",name:"Create Listing",route:"/api/bop/mkp/listings",status:"active" },
  { object_id:"api:mkp/listings/[id]:PATCH",type:"api",module:"MKP",name:"Update Listing",route:"/api/bop/mkp/listings/[id]",status:"active" },
  { object_id:"api:mkp/listing-layouts:GET",type:"api",module:"MKP",name:"GET Listing Layouts",route:"/api/bop/mkp/listing-layouts",status:"active" },
  { object_id:"api:mkp/listing-layouts:POST",type:"api",module:"MKP",name:"Upsert Listing Layout",route:"/api/bop/mkp/listing-layouts",status:"active" },
  { object_id:"api:mkp/listing-layouts:PATCH",type:"api",module:"MKP",name:"Update Listing Layout",route:"/api/bop/mkp/listing-layouts",status:"active" },
  { object_id:"api:mkp/listing-layouts:DELETE",type:"api",module:"MKP",name:"Delete Listing Layout",route:"/api/bop/mkp/listing-layouts",status:"active" },
  { object_id:"api:mkp/bop-listings:GET",type:"api",module:"MKP",name:"GET BOP Listings",route:"/api/bop/mkp/bop-listings",status:"active" },
  { object_id:"api:mkp/bop-listings:POST",type:"api",module:"MKP",name:"Create BOP Listing",route:"/api/bop/mkp/bop-listings",status:"active" },
  { object_id:"api:mkp/bop-listings/meta:GET",type:"api",module:"MKP",name:"GET BOP Listing Meta",route:"/api/bop/mkp/bop-listings/meta",status:"active" },
  { object_id:"api:mkp/taxonomy:GET",type:"api",module:"MKP",name:"GET Taxonomy Tree",route:"/api/bop/mkp/taxonomy",status:"active" },
  { object_id:"api:mkp/bop-listings/[id]:GET",type:"api",module:"MKP",name:"GET BOP Listing Detail",route:"/api/bop/mkp/bop-listings/[id]",status:"active" },
  { object_id:"api:mkp/bop-listings/[id]:PATCH",type:"api",module:"MKP",name:"Update BOP Listing",route:"/api/bop/mkp/bop-listings/[id]",status:"active" },
  { object_id:"api:mkp/bop-listings/[id]:DELETE",type:"api",module:"MKP",name:"Delete BOP Listing",route:"/api/bop/mkp/bop-listings/[id]",status:"active" },
  { object_id:"api:sys/help:GET",type:"api",module:"SYS",name:"GET Screen Help",route:"/api/bop/sys/help",status:"active" },
  { object_id:"api:sys/help:POST",type:"api",module:"SYS",name:"Author Screen Help",route:"/api/bop/sys/help",status:"active" },
  { object_id:"api:sys/help/tech:GET",type:"api",module:"SYS",name:"GET Technical Info",route:"/api/bop/sys/help/tech",status:"active" },
  { object_id:"api:mkp/auctions:GET",type:"api",module:"AUC",name:"GET Auctions",route:"/api/bop/mkp/auctions",status:"active" },
  { object_id:"api:mkp/auctions:POST",type:"api",module:"AUC",name:"Create Auction",route:"/api/bop/mkp/auctions",status:"active" },
  { object_id:"api:mkp/auctions/[id]:GET",type:"api",module:"AUC",name:"GET Auction Detail",route:"/api/bop/mkp/auctions/[id]",status:"active" },
  { object_id:"api:mkp/auctions/[id]:PATCH",type:"api",module:"AUC",name:"Update Auction",route:"/api/bop/mkp/auctions/[id]",status:"active" },
  { object_id:"api:mkp/auctions/[id]:DELETE",type:"api",module:"AUC",name:"Delete Auction",route:"/api/bop/mkp/auctions/[id]",status:"active" },
  { object_id:"api:mkp/auctions/[id]/lots:POST",type:"api",module:"AUC",name:"Add Auction Lot",route:"/api/bop/mkp/auctions/[id]/lots",status:"active" },
  { object_id:"api:mkp/auctions/[id]/lots:DELETE",type:"api",module:"AUC",name:"Remove Auction Lot",route:"/api/bop/mkp/auctions/[id]/lots",status:"active" },
  { object_id:"api:mkp/auctions/[id]/lots:PATCH",type:"api",module:"AUC",name:"Close/Reopen Lot",route:"/api/bop/mkp/auctions/[id]/lots",status:"active" },
  { object_id:"api:mkp/auctions/[id]/bids:GET",type:"api",module:"AUC",name:"GET Auction Bids",route:"/api/bop/mkp/auctions/[id]/bids",status:"active" },
  { object_id:"api:mkp/auctions/[id]/bids:POST",type:"api",module:"AUC",name:"Place Bid",route:"/api/bop/mkp/auctions/[id]/bids",status:"active" },
  { object_id:"api:ai/chat:GET",type:"api",module:"AIM",name:"AI Chat Status",route:"/api/bop/ai/chat",status:"active" },
  { object_id:"api:ai/chat:POST",type:"api",module:"AIM",name:"AI Chat",route:"/api/bop/ai/chat",status:"active" },
  { object_id:"api:ai/agents:GET",type:"api",module:"AIM",name:"List AI Agents",route:"/api/bop/ai/agents",status:"active" },
  { object_id:"api:ai/agents:POST",type:"api",module:"AIM",name:"Create AI Agent",route:"/api/bop/ai/agents",status:"active" },
  { object_id:"api:ai/agents/[id]:PATCH",type:"api",module:"AIM",name:"Update AI Agent",route:"/api/bop/ai/agents/[id]",status:"active" },
  { object_id:"api:ai/agents/[id]:DELETE",type:"api",module:"AIM",name:"Delete AI Agent",route:"/api/bop/ai/agents/[id]",status:"active" },
  { object_id:"api:md/partners:GET",type:"api",module:"MDM",name:"GET Partners",route:"/api/bop/md/partners",status:"active" },
  { object_id:"api:md/taxonomy:GET",type:"api",module:"MDM",name:"GET Taxonomy",route:"/api/bop/md/taxonomy",status:"active" },
  { object_id:"api:sal/orders:GET",type:"api",module:"SAL",name:"GET Orders",route:"/api/bop/sal/orders",status:"active" },
  { object_id:"api:sal/orders:POST",type:"api",module:"SAL",name:"Create Order",route:"/api/bop/sal/orders",status:"active" },
  { object_id:"api:sal/quotations:GET",type:"api",module:"SAL",name:"GET Quotations",route:"/api/bop/sal/quotations",status:"active" },
  { object_id:"api:sal/quotations:POST",type:"api",module:"SAL",name:"Create Quotation",route:"/api/bop/sal/quotations",status:"active" },
  { object_id:"api:sys/users:GET",type:"api",module:"SYS",name:"GET Users",route:"/api/bop/sys/users",status:"active" },
  { object_id:"api:sys/roles:GET",type:"api",module:"SYS",name:"GET Roles",route:"/api/bop/sys/roles",status:"active" },
  { object_id:"api:sys/screens:GET",type:"api",module:"SYS",name:"GET Screens",route:"/api/bop/sys/screens",status:"active" },
  { object_id:"api:sys/settings:GET",type:"api",module:"SYS",name:"GET Settings",route:"/api/bop/sys/settings",status:"active" },
  { object_id:"api:sys/settings:PUT",type:"api",module:"SYS",name:"PUT Setting",route:"/api/bop/sys/settings",status:"active" },
  { object_id:"api:sys/health:GET",type:"api",module:"SYS",name:"Health Check",route:"/api/bop/sys/health",status:"active" },
  { object_id:"api:access-audit:GET",type:"api",module:"SYS",name:"Access Audit Log",route:"/api/bop/access-audit",status:"active" },
  { object_id:"api:sys/objects:GET",type:"api",module:"SYS",name:"GET Objects",route:"/api/bop/sys/objects",status:"active" },
  { object_id:"api:sys/objects:POST",type:"api",module:"SYS",name:"Upsert Objects",route:"/api/bop/sys/objects",status:"active" },
  { object_id:"api:sys/dependencies:GET",type:"api",module:"SYS",name:"GET Dependencies",route:"/api/bop/sys/dependencies",status:"active" },
  { object_id:"api:sys/dependencies:POST",type:"api",module:"SYS",name:"POST Dependencies",route:"/api/bop/sys/dependencies",status:"active" },
  { object_id:"api:sys/objects/seed:POST",type:"api",module:"SYS",name:"Seed Object Manifest",route:"/api/bop/sys/objects/seed",status:"active" },
  { object_id:"api:an/dashboard:GET",type:"api",module:"ANL",name:"GET Analytics Dashboard",route:"/api/bop/an/dashboard",status:"active" },
  { object_id:"api:ast/costs/[id]:GET",type:"api",module:"AST",name:"GET Cost Entry",route:"/api/bop/ast/costs/[id]",status:"active" },
  { object_id:"api:ast/costs/[id]:PATCH",type:"api",module:"AST",name:"Update Cost Entry",route:"/api/bop/ast/costs/[id]",status:"active" },
  { object_id:"api:crm/customer/[id]:GET",type:"api",module:"CRM",name:"Customer 360",route:"/api/bop/crm/customer/[id]",status:"active" },
  { object_id:"api:fin/invoices/[id]:GET",type:"api",module:"FIN",name:"GET Invoice Detail",route:"/api/bop/fin/invoices/[id]",status:"active" },
  { object_id:"api:fin/invoices/[id]:PATCH",type:"api",module:"FIN",name:"Update Invoice",route:"/api/bop/fin/invoices/[id]",status:"active" },
  { object_id:"api:fin/invoices/[id]:DELETE",type:"api",module:"FIN",name:"Delete Invoice",route:"/api/bop/fin/invoices/[id]",status:"active" },
  { object_id:"api:md/partners/[id]:GET",type:"api",module:"MDM",name:"GET Partner Detail",route:"/api/bop/md/partners/[id]",status:"active" },
  { object_id:"api:md/partners/[id]:PATCH",type:"api",module:"MDM",name:"Update Partner",route:"/api/bop/md/partners/[id]",status:"active" },
  { object_id:"api:md/partners/[id]:DELETE",type:"api",module:"MDM",name:"Delete Partner",route:"/api/bop/md/partners/[id]",status:"active" },
  { object_id:"api:md/taxonomy/[id]:GET",type:"api",module:"MDM",name:"GET Taxonomy Node",route:"/api/bop/md/taxonomy/[id]",status:"active" },
  { object_id:"api:md/taxonomy/[id]:PATCH",type:"api",module:"MDM",name:"Update Taxonomy Node",route:"/api/bop/md/taxonomy/[id]",status:"active" },
  { object_id:"api:mkp/listings/[id]:GET",type:"api",module:"MKP",name:"GET Listing Detail",route:"/api/bop/mkp/listings/[id]",status:"active" },
  { object_id:"api:mkp/listings/[id]:DELETE",type:"api",module:"MKP",name:"Delete Listing",route:"/api/bop/mkp/listings/[id]",status:"active" },
  { object_id:"api:notifications:GET",type:"api",module:"SYS",name:"GET Notifications",route:"/api/bop/notifications",status:"active" },
  { object_id:"api:recent:GET",type:"api",module:"SYS",name:"GET Recent Activity",route:"/api/bop/recent",status:"active" },
  { object_id:"api:sal/orders/[id]:GET",type:"api",module:"SAL",name:"GET Order Detail",route:"/api/bop/sal/orders/[id]",status:"active" },
  { object_id:"api:sal/orders/[id]:PATCH",type:"api",module:"SAL",name:"Update Order",route:"/api/bop/sal/orders/[id]",status:"active" },
  { object_id:"api:sal/quotations/[id]:GET",type:"api",module:"SAL",name:"GET Quotation Detail",route:"/api/bop/sal/quotations/[id]",status:"active" },
  { object_id:"api:sal/quotations/[id]:PATCH",type:"api",module:"SAL",name:"Update Quotation",route:"/api/bop/sal/quotations/[id]",status:"active" },
  { object_id:"api:suim:GET",type:"api",module:"SYS",name:"SUIM Role Browser Data",route:"/api/bop/suim",status:"active" },
  { object_id:"api:sys/access-requests:GET",type:"api",module:"SYS",name:"GET Access Requests",route:"/api/bop/sys/access-requests",status:"active" },
  { object_id:"api:sys/access-requests:POST",type:"api",module:"SYS",name:"Submit Access Request",route:"/api/bop/sys/access-requests",status:"active" },
  { object_id:"api:sys/access-requests/[id]:PATCH",type:"api",module:"SYS",name:"Process Access Request",route:"/api/bop/sys/access-requests/[id]",status:"active" },
  { object_id:"api:sys/admin-dashboard:GET",type:"api",module:"SYS",name:"GET Admin Dashboard",route:"/api/bop/sys/admin-dashboard",status:"active" },
  { object_id:"api:sys/last-updated:GET",type:"api",module:"SYS",name:"GET Last Updated Timestamp",route:"/api/bop/sys/last-updated",status:"active" },
  { object_id:"api:sys/modules:GET",type:"api",module:"SYS",name:"GET Modules",route:"/api/bop/sys/modules",status:"active" },
  { object_id:"api:sys/modules:POST",type:"api",module:"SYS",name:"Upsert Module",route:"/api/bop/sys/modules",status:"active" },
  { object_id:"api:sys/modules/[code]:GET",type:"api",module:"SYS",name:"GET Module Detail",route:"/api/bop/sys/modules/[code]",status:"active" },
  { object_id:"api:sys/modules/[code]:PATCH",type:"api",module:"SYS",name:"Update Module",route:"/api/bop/sys/modules/[code]",status:"active" },
  { object_id:"api:sys/roles/[id]:GET",type:"api",module:"SYS",name:"GET Role Detail",route:"/api/bop/sys/roles/[id]",status:"active" },
  { object_id:"api:sys/roles/[id]:PATCH",type:"api",module:"SYS",name:"Update Role",route:"/api/bop/sys/roles/[id]",status:"active" },
  { object_id:"api:sys/roles/[id]:DELETE",type:"api",module:"SYS",name:"Delete Role",route:"/api/bop/sys/roles/[id]",status:"active" },
  { object_id:"api:sys/roles/[id]/screens:GET",type:"api",module:"SYS",name:"GET Role Screen Assignments",route:"/api/bop/sys/roles/[id]/screens",status:"active" },
  { object_id:"api:sys/roles/[id]/screens:POST",type:"api",module:"SYS",name:"Assign Screen to Role",route:"/api/bop/sys/roles/[id]/screens",status:"active" },
  { object_id:"api:sys/screens/[id]:GET",type:"api",module:"SYS",name:"GET Screen Detail",route:"/api/bop/sys/screens/[id]",status:"active" },
  { object_id:"api:sys/screens/[id]:PATCH",type:"api",module:"SYS",name:"Update Screen",route:"/api/bop/sys/screens/[id]",status:"active" },
  { object_id:"api:sys/screens/[id]/history:GET",type:"api",module:"SYS",name:"GET Screen History",route:"/api/bop/sys/screens/[id]/history",status:"active" },
  { object_id:"api:sys/screens/[id]/meta:GET",type:"api",module:"SYS",name:"GET Screen Meta",route:"/api/bop/sys/screens/[id]/meta",status:"active" },
  { object_id:"api:sys/screens/[id]/roles:GET",type:"api",module:"SYS",name:"GET Screen Role Access",route:"/api/bop/sys/screens/[id]/roles",status:"active" },
  { object_id:"api:sys/screens/[id]/source:GET",type:"api",module:"SYS",name:"GET Screen Source",route:"/api/bop/sys/screens/[id]/source",status:"active" },
  { object_id:"api:sys/screens/[id]/used-by:GET",type:"api",module:"SYS",name:"GET Screen Used-By",route:"/api/bop/sys/screens/[id]/used-by",status:"active" },
  { object_id:"api:sys/search:GET",type:"api",module:"SYS",name:"Global Search",route:"/api/bop/sys/search",status:"active" },
  { object_id:"api:sys/tenants:GET",type:"api",module:"SYS",name:"GET Tenants",route:"/api/bop/sys/tenants",status:"active" },
  { object_id:"api:sys/tenants:POST",type:"api",module:"SYS",name:"Create Tenant",route:"/api/bop/sys/tenants",status:"active" },
  { object_id:"api:sys/tenants/[id]:GET",type:"api",module:"SYS",name:"GET Tenant Detail",route:"/api/bop/sys/tenants/[id]",status:"active" },
  { object_id:"api:sys/tenants/[id]:PATCH",type:"api",module:"SYS",name:"Update Tenant",route:"/api/bop/sys/tenants/[id]",status:"active" },
  { object_id:"api:sys/tenants/[id]:DELETE",type:"api",module:"SYS",name:"Delete Tenant",route:"/api/bop/sys/tenants/[id]",status:"active" },
  { object_id:"api:sys/users/[id]:GET",type:"api",module:"SYS",name:"GET User Detail",route:"/api/bop/sys/users/[id]",status:"active" },
  { object_id:"api:sys/users/[id]:PATCH",type:"api",module:"SYS",name:"Update User",route:"/api/bop/sys/users/[id]",status:"active" },
  { object_id:"api:sys/users/[id]:DELETE",type:"api",module:"SYS",name:"Delete User",route:"/api/bop/sys/users/[id]",status:"active" },
  { object_id:"api:sys/users/[id]/detail:GET",type:"api",module:"SYS",name:"GET User Full Detail",route:"/api/bop/sys/users/[id]/detail",status:"active" },
  { object_id:"api:sys/users/[id]/roles:GET",type:"api",module:"SYS",name:"GET User Role Assignments",route:"/api/bop/sys/users/[id]/roles",status:"active" },
  { object_id:"api:sys/users/[id]/roles:POST",type:"api",module:"SYS",name:"Assign Role to User",route:"/api/bop/sys/users/[id]/roles",status:"active" },
  { object_id:"api:sys/users/[id]/roles:DELETE",type:"api",module:"SYS",name:"Revoke Role from User",route:"/api/bop/sys/users/[id]/roles",status:"active" },
  { object_id:"api:sys/users/invite:POST",type:"api",module:"SYS",name:"Invite User",route:"/api/bop/sys/users/invite",status:"active" },
  { object_id:"api:user/me:GET",type:"api",module:"SYS",name:"GET Current User",route:"/api/bop/user/me",status:"active" },
  { object_id:"api:user/locale:GET",type:"api",module:"SYS",name:"GET User Locale",route:"/api/bop/user/locale",status:"active" },
  { object_id:"api:user/locale:PUT",type:"api",module:"SYS",name:"Set User Locale",route:"/api/bop/user/locale",status:"active" },
  { object_id:"api:user/prefs:GET",type:"api",module:"SYS",name:"GET User Preferences",route:"/api/bop/user/prefs",status:"active" },
  { object_id:"api:user/prefs:PUT",type:"api",module:"SYS",name:"Update User Preferences",route:"/api/bop/user/prefs",status:"active" },
  { object_id:"api:track:POST",type:"api",module:"SYS",name:"Track Page View / Event",route:"/api/bop/track",status:"active" },
  { object_id:"api:roles:GET",type:"api",module:"SYS",name:"GET Roles (shortpath)",route:"/api/bop/roles",status:"active" },
  { object_id:"api:roles:POST",type:"api",module:"SYS",name:"Create Role (shortpath)",route:"/api/bop/roles",status:"active" },
  { object_id:"api:users:GET",type:"api",module:"SYS",name:"GET Users (shortpath)",route:"/api/bop/users",status:"active" },
  { object_id:"api:users:POST",type:"api",module:"SYS",name:"Create User (shortpath)",route:"/api/bop/users",status:"active" },
  { object_id:"api:users/[id]:GET",type:"api",module:"SYS",name:"GET User (shortpath)",route:"/api/bop/users/[id]",status:"active" },
  { object_id:"api:users/[id]:PATCH",type:"api",module:"SYS",name:"Update User (shortpath)",route:"/api/bop/users/[id]",status:"active" },
  { object_id:"api:sys/objects/audit:GET",type:"api",module:"SYS",name:"BOP Object Registry Audit",route:"/api/bop/sys/objects/audit",status:"active" },
  { object_id:"api:mkt/generate:POST",type:"api",module:"MKT",name:"Generate Campaign",route:"/api/bop/mkt/generate",status:"active" },
  { object_id:"api:mkt/campaigns:GET",type:"api",module:"MKT",name:"List Campaigns",route:"/api/bop/mkt/campaigns",status:"active" },
  { object_id:"api:mkt/campaigns:DELETE",type:"api",module:"MKT",name:"Delete Campaign",route:"/api/bop/mkt/campaigns",status:"active" },
  { object_id:"api:mkt/campaigns/[id]:GET",type:"api",module:"MKT",name:"Campaign Detail",route:"/api/bop/mkt/campaigns/[id]",status:"active" },
  { object_id:"api:mkt/outputs/[id]:PATCH",type:"api",module:"MKT",name:"Edit/Approve Output",route:"/api/bop/mkt/outputs/[id]",status:"active" },
  { object_id:"api:mkt/publish:POST",type:"api",module:"MKT",name:"Publish Output",route:"/api/bop/mkt/publish",status:"active" },
  { object_id:"api:mkt/meta:GET",type:"api",module:"MKT",name:"Cockpit Meta / Listing Search",route:"/api/bop/mkt/meta",status:"active" },
  { object_id:"api:mkt/brand:GET",type:"api",module:"MKT",name:"List Brand Profiles",route:"/api/bop/mkt/brand",status:"active" },
  { object_id:"api:mkt/brand:PATCH",type:"api",module:"MKT",name:"Upsert Brand Profile",route:"/api/bop/mkt/brand",status:"active" },
  { object_id:"api:mkp/brands:GET",type:"api",module:"INV",name:"List Brands",route:"/api/bop/mkp/brands",status:"active" },
  { object_id:"api:mkp/brands:POST",type:"api",module:"INV",name:"Create Brand",route:"/api/bop/mkp/brands",status:"active" },
  { object_id:"api:mkp/brands/[id]:PATCH",type:"api",module:"INV",name:"Update Brand",route:"/api/bop/mkp/brands/[id]",status:"active" },
  { object_id:"api:mkp/brands/[id]:DELETE",type:"api",module:"INV",name:"Delete Brand",route:"/api/bop/mkp/brands/[id]",status:"active" },
  { object_id:"api:mkp/brands/[id]/models:GET",type:"api",module:"INV",name:"List Models",route:"/api/bop/mkp/brands/[id]/models",status:"active" },
  { object_id:"api:mkp/brands/[id]/models:POST",type:"api",module:"INV",name:"Create Model",route:"/api/bop/mkp/brands/[id]/models",status:"active" },
  { object_id:"api:mkp/models:GET",type:"api",module:"INV",name:"List Models (flat)",route:"/api/bop/mkp/models",status:"active" },
  { object_id:"api:mkp/models:POST",type:"api",module:"INV",name:"Create Model (flat)",route:"/api/bop/mkp/models",status:"active" },
  { object_id:"api:mkp/media/upload:POST",type:"api",module:"MKP",name:"Upload Listing Media",route:"/api/bop/mkp/media/upload",status:"active" },
  { object_id:"api:mkp/media/[id]:DELETE",type:"api",module:"MKP",name:"Delete Listing Media",route:"/api/bop/mkp/media/[id]",status:"active" },
  { object_id:"api:mkp/media/[id]:PATCH",type:"api",module:"MKP",name:"Update Listing Media",route:"/api/bop/mkp/media/[id]",status:"active" },
  { object_id:"api:mkp/media/reorder:POST",type:"api",module:"MKP",name:"Reorder Listing Media",route:"/api/bop/mkp/media/reorder",status:"active" },
  // Trade Flow Engine — P1 lead RPCs
  { object_id:"api:bop_lead_allowed_transitions",type:"api",module:"CRM",name:"Lead Allowed Transitions",status:"active",description:"Returns valid next stages for a lead" },
  { object_id:"api:bop_lead_transition",type:"api",module:"CRM",name:"Lead Transition",status:"active",description:"Validated lead stage change + audit trail" },
  { object_id:"api:bop_convert_lead",type:"api",module:"CRM",name:"Convert Lead",status:"active",description:"Lead → Case + Quotation/Order atomically" },
  // Trade Flow Engine — P2 quotation RPCs
  { object_id:"api:bop_quotation_allowed_transitions",type:"api",module:"SAL",name:"Quotation Allowed Transitions",status:"active",description:"Returns valid next statuses for a quotation" },
  { object_id:"api:bop_quotation_transition",type:"api",module:"SAL",name:"Quotation Transition",status:"active",description:"Validated quotation status change + audit trail" },
  { object_id:"api:bop_quotation_send",type:"api",module:"SAL",name:"Send Quotation",status:"active",description:"Freeze snapshot + approval token + transition to sent" },
  { object_id:"api:bop_quotation_new_version",type:"api",module:"SAL",name:"New Quotation Version",status:"active",description:"Clone as draft v+1, expire old, doc_flow=replaced" },
  { object_id:"api:bop_approval_respond",type:"api",module:"SAL",name:"Approval Respond",status:"active",description:"Shared handler for quotation+order approval tokens" },
  // Trade Flow Engine — P3 order RPCs
  { object_id:"api:bop_order_allowed_transitions",type:"api",module:"SAL",name:"Order Allowed Transitions",status:"active",description:"Returns valid next statuses for an order" },
  { object_id:"api:bop_order_transition",type:"api",module:"SAL",name:"Order Transition",status:"active",description:"Validated order status change + audit trail" },
  { object_id:"api:bop_order_confirm",type:"api",module:"SAL",name:"Order Confirm",status:"active",description:"OLS vehicle lock + approval token + confirmed" },
  { object_id:"api:bop_order_cancel",type:"api",module:"SAL",name:"Order Cancel",status:"active",description:"Refund guard + lock release + cancelled" },
  // Trade Flow Engine — P4 invoice RPCs
  { object_id:"api:bop_invoice_allowed_transitions",type:"api",module:"FIN",name:"Invoice Allowed Transitions",status:"active",description:"Returns valid next statuses for an invoice" },
  { object_id:"api:bop_invoice_transition",type:"api",module:"FIN",name:"Invoice Transition",status:"active",description:"Validated invoice status change + audit trail" },
  { object_id:"api:bop_create_invoice_from_order",type:"api",module:"FIN",name:"Create Invoice from Order",status:"active",description:"Generates deposit/final/credit_note invoice from order" },
  { object_id:"api:invoice_payment_state",type:"api",module:"FIN",name:"Invoice Payment State",status:"active",description:"Returns paid/partial/unpaid + overdue + credit status" },
  { object_id:"api:fin/invoices/[id]/transition:GET",type:"api",module:"FIN",name:"GET Invoice Transitions",route:"/api/bop/fin/invoices/[id]/transition",status:"active" },
  { object_id:"api:fin/invoices/[id]/transition:POST",type:"api",module:"FIN",name:"POST Invoice Transition",route:"/api/bop/fin/invoices/[id]/transition",status:"active" },
  { object_id:"api:fin/invoices/from-order:POST",type:"api",module:"FIN",name:"Create Invoice from Order API",route:"/api/bop/fin/invoices/from-order",status:"active" },
  // Trade Flow Engine — P5 handover RPCs
  { object_id:"api:bop_handover_allowed_transitions",type:"api",module:"SAL",name:"Handover Allowed Transitions",status:"active",description:"Returns valid next statuses for a handover" },
  { object_id:"api:bop_handover_transition",type:"api",module:"SAL",name:"Handover Transition",status:"active",description:"Validated handover status change + audit trail" },
  { object_id:"api:bop_handover_complete",type:"api",module:"SAL",name:"Handover Complete",status:"active",description:"Signature capture + OLS release + order→delivered" },
  { object_id:"api:bop_create_handover_from_order",type:"api",module:"SAL",name:"Create Handover from Order",status:"active",description:"Creates handover + transitions order to handover_scheduled" },
  { object_id:"api:sal/handovers:GET",type:"api",module:"SAL",name:"GET Handovers",route:"/api/bop/sal/handovers",status:"active" },
  { object_id:"api:sal/handovers:POST",type:"api",module:"SAL",name:"Create Handover",route:"/api/bop/sal/handovers",status:"active" },
  { object_id:"api:sal/handovers/[id]:GET",type:"api",module:"SAL",name:"GET Handover Detail",route:"/api/bop/sal/handovers/[id]",status:"active" },
  { object_id:"api:sal/handovers/[id]:PATCH",type:"api",module:"SAL",name:"Update Handover",route:"/api/bop/sal/handovers/[id]",status:"active" },
  { object_id:"api:sal/handovers/[id]/transition:GET",type:"api",module:"SAL",name:"GET Handover Transitions",route:"/api/bop/sal/handovers/[id]/transition",status:"active" },
  { object_id:"api:sal/handovers/[id]/transition:POST",type:"api",module:"SAL",name:"POST Handover Transition",route:"/api/bop/sal/handovers/[id]/transition",status:"active" },
  { object_id:"api:sal/handovers/[id]/complete:POST",type:"api",module:"SAL",name:"Complete Handover",route:"/api/bop/sal/handovers/[id]/complete",status:"active" },
  { object_id:"api:sal/handovers/from-order:POST",type:"api",module:"SAL",name:"Create Handover from Order API",route:"/api/bop/sal/handovers/from-order",status:"active" },
  // Trade Flow Engine — P6 post-sale RPCs
  { object_id:"api:bop_create_warranty_from_handover",type:"api",module:"SAL",name:"Create Warranty from Handover",status:"active",description:"Creates warranty after completed handover" },
  { object_id:"api:bop_schedule_survey",type:"api",module:"SAL",name:"Schedule Survey",status:"active",description:"Schedules customer satisfaction survey at +N days" },
  { object_id:"api:bop_submit_survey",type:"api",module:"SAL",name:"Submit Survey",status:"active",description:"NPS+rating submission with smart review routing" },
  { object_id:"api:bop_expire_warranties",type:"api",module:"SAL",name:"Expire Warranties",status:"active",description:"Daily cron: expire past-due warranties" },
  { object_id:"api:sal/warranties:GET",type:"api",module:"SAL",name:"GET Warranties",route:"/api/bop/sal/warranties",status:"active" },
  { object_id:"api:sal/warranties/[id]:GET",type:"api",module:"SAL",name:"GET Warranty Detail",route:"/api/bop/sal/warranties/[id]",status:"active" },
  { object_id:"api:sal/warranties/[id]:PATCH",type:"api",module:"SAL",name:"Update Warranty",route:"/api/bop/sal/warranties/[id]",status:"active" },
  { object_id:"api:sal/warranties/[id]/claims:GET",type:"api",module:"SAL",name:"GET Warranty Claims",route:"/api/bop/sal/warranties/[id]/claims",status:"active" },
  { object_id:"api:sal/warranties/[id]/claims:POST",type:"api",module:"SAL",name:"File Warranty Claim",route:"/api/bop/sal/warranties/[id]/claims",status:"active" },
  { object_id:"api:sal/warranties/from-handover:POST",type:"api",module:"SAL",name:"Create Warranty from Handover API",route:"/api/bop/sal/warranties/from-handover",status:"active" },
  { object_id:"api:sal/surveys:GET",type:"api",module:"SAL",name:"GET Surveys",route:"/api/bop/sal/surveys",status:"active" },
  { object_id:"api:sal/surveys/[id]:GET",type:"api",module:"SAL",name:"GET Survey Detail",route:"/api/bop/sal/surveys/[id]",status:"active" },
  { object_id:"api:sal/surveys/[id]:PATCH",type:"api",module:"SAL",name:"Update Survey",route:"/api/bop/sal/surveys/[id]",status:"active" },
  { object_id:"api:sal/surveys/schedule:POST",type:"api",module:"SAL",name:"Schedule Survey API",route:"/api/bop/sal/surveys/schedule",status:"active" },
  { object_id:"api:sal/surveys/[id]/submit:POST",type:"api",module:"SAL",name:"Submit Survey API",route:"/api/bop/sal/surveys/[id]/submit",status:"active" },
  // Workshop module APIs
  { object_id:"api:wrk/orders:GET",type:"api",module:"WRK",name:"GET Work Orders",route:"/api/bop/wrk/orders",status:"active" },
  { object_id:"api:wrk/orders:POST",type:"api",module:"WRK",name:"Create Work Order",route:"/api/bop/wrk/orders",status:"active" },
  { object_id:"api:wrk/orders:PATCH",type:"api",module:"WRK",name:"Update Work Order",route:"/api/bop/wrk/orders",status:"active" },
  { object_id:"api:wrk/orders:DELETE",type:"api",module:"WRK",name:"Soft-Delete Work Order",route:"/api/bop/wrk/orders",status:"active" },
  { object_id:"api:wrk/technicians:GET",type:"api",module:"WRK",name:"GET Technicians",route:"/api/bop/wrk/technicians",status:"active" },
  { object_id:"api:wrk/technicians:POST",type:"api",module:"WRK",name:"Create Technician",route:"/api/bop/wrk/technicians",status:"active" },
  { object_id:"api:wrk/technicians:PATCH",type:"api",module:"WRK",name:"Update Technician",route:"/api/bop/wrk/technicians",status:"active" },
  { object_id:"api:wrk/plate-lookup:POST",type:"api",module:"WRK",name:"RDW Plate Lookup for WO",route:"/api/bop/wrk/plate-lookup",status:"active" },
  { object_id:"api:wrk/inspections:GET",type:"api",module:"WRK",name:"GET Inspections",route:"/api/bop/wrk/inspections",status:"active" },
  { object_id:"api:wrk/inspections:POST",type:"api",module:"WRK",name:"Create Inspection",route:"/api/bop/wrk/inspections",status:"active" },
  { object_id:"api:wrk/apk-reminders:GET",type:"api",module:"WRK",name:"GET APK Reminders",route:"/api/bop/wrk/apk-reminders",status:"active" },
  { object_id:"api:wrk/apk-reminders:POST",type:"api",module:"WRK",name:"Trigger APK Reminder",route:"/api/bop/wrk/apk-reminders",status:"active" },
  { object_id:"api:wrk/apk-reminders:PATCH",type:"api",module:"WRK",name:"Update APK Reminder",route:"/api/bop/wrk/apk-reminders",status:"active" },
  { object_id:"api:wrk/approvals:GET",type:"api",module:"WRK",name:"GET Customer Approvals",route:"/api/bop/wrk/approvals",status:"active" },
  { object_id:"api:wrk/approvals:POST",type:"api",module:"WRK",name:"Create Approval Request",route:"/api/bop/wrk/approvals",status:"active" },
  { object_id:"api:wrk/approvals:PATCH",type:"api",module:"WRK",name:"Update Approval",route:"/api/bop/wrk/approvals",status:"active" },
  { object_id:"api:wrk/status:GET",type:"api",module:"WRK",name:"GET Work Order Status",route:"/api/bop/wrk/status",status:"active" },
  { object_id:"api:wrk/rates:GET",type:"api",module:"WRK",name:"GET Labour Rates",route:"/api/bop/wrk/rates",status:"active" },
  { object_id:"api:wrk/rates:POST",type:"api",module:"WRK",name:"Create Labour Rate",route:"/api/bop/wrk/rates",status:"active" },
  { object_id:"api:wrk/rates:PATCH",type:"api",module:"WRK",name:"Update Labour Rate",route:"/api/bop/wrk/rates",status:"active" },
  { object_id:"api:wrk/rates:DELETE",type:"api",module:"WRK",name:"Delete Labour Rate",route:"/api/bop/wrk/rates",status:"active" },
  { object_id:"api:wrk/packages:GET",type:"api",module:"WRK",name:"GET Service Packages",route:"/api/bop/wrk/packages",status:"active" },
  { object_id:"api:wrk/packages:POST",type:"api",module:"WRK",name:"Create Service Package",route:"/api/bop/wrk/packages",status:"active" },
  { object_id:"api:wrk/packages:PATCH",type:"api",module:"WRK",name:"Update Service Package",route:"/api/bop/wrk/packages",status:"active" },
  { object_id:"api:wrk/packages:DELETE",type:"api",module:"WRK",name:"Deactivate Service Package",route:"/api/bop/wrk/packages",status:"active" },
  { object_id:"api:wrk/efficiency:GET",type:"api",module:"WRK",name:"GET Efficiency KPI",route:"/api/bop/wrk/efficiency",status:"active" },
  { object_id:"api:wrk/planning:GET",type:"api",module:"WRK",name:"GET Planning Board",route:"/api/bop/wrk/planning",status:"active" },
  { object_id:"api:wrk/planning:POST",type:"api",module:"WRK",name:"Create Planning Slot",route:"/api/bop/wrk/planning",status:"active" },
  { object_id:"api:wrk/planning:PATCH",type:"api",module:"WRK",name:"Update Planning Slot",route:"/api/bop/wrk/planning",status:"active" },
  { object_id:"api:wrk/planning:DELETE",type:"api",module:"WRK",name:"Delete Planning Slot",route:"/api/bop/wrk/planning",status:"active" },
  { object_id:"api:wrk/efficiency:POST",type:"api",module:"WRK",name:"Record Efficiency Data",route:"/api/bop/wrk/efficiency",status:"active" },
  { object_id:"api:wrk/inspections:PATCH",type:"api",module:"WRK",name:"Update Inspection",route:"/api/bop/wrk/inspections",status:"active" },
  { object_id:"api:wrk/dashboard:GET",type:"api",module:"WRK",name:"GET Workshop Dashboard",route:"/api/bop/wrk/dashboard",status:"active" },
  { object_id:"api:wrk/briefing:GET",type:"api",module:"WRK",name:"GET Daily Briefing",route:"/api/bop/wrk/briefing",status:"active" },
  { object_id:"api:wrk/recommendations:GET",type:"api",module:"WRK",name:"GET Recommendations",route:"/api/bop/wrk/recommendations",status:"active" },
  { object_id:"api:wrk/autoflex:GET",type:"api",module:"WRK",name:"GET Autoflex Config",route:"/api/bop/wrk/autoflex",status:"active" },
  { object_id:"api:wrk/autoflex:POST",type:"api",module:"WRK",name:"Autoflex Actions",route:"/api/bop/wrk/autoflex",status:"active" },
  { object_id:"api:wrk/autoflex/logs:GET",type:"api",module:"WRK",name:"GET Autoflex Sync Logs",route:"/api/bop/wrk/autoflex/logs",status:"active" },
  { object_id:"api:wrk/autoflex/logs:POST",type:"api",module:"WRK",name:"Create Sync Log Entry",route:"/api/bop/wrk/autoflex/logs",status:"active" },
  // Trade Flow Engine — P7 Case Timeline + Guard Rails
  { object_id:"api:sal/cases:GET",type:"api",module:"SAL",name:"GET Cases",route:"/api/bop/sal/cases",status:"active" },
  { object_id:"api:sal/cases/[id]:GET",type:"api",module:"SAL",name:"GET Case Detail",route:"/api/bop/sal/cases/[id]",status:"active" },
  { object_id:"api:sal/cases/[id]/timeline:GET",type:"api",module:"SAL",name:"GET Case Timeline",route:"/api/bop/sal/cases/[id]/timeline",status:"active" },
  { object_id:"api:sal/cases/[id]/documents:GET",type:"api",module:"SAL",name:"GET Case Documents",route:"/api/bop/sal/cases/[id]/documents",status:"active" },
  { object_id:"api:sys/integrity:GET",type:"api",module:"SYS",name:"Doc-Flow Integrity Check",route:"/api/bop/sys/integrity",status:"active" },
  { object_id:"api:case_stage",type:"api",module:"SAL",name:"Derived Case Stage",status:"active",description:"Returns highest doc type reached in case" },
  { object_id:"api:vehicle_availability",type:"api",module:"SAL",name:"Derived Vehicle Availability",status:"active",description:"Returns available/reserved/sold for a vehicle" },
  { object_id:"api:case_documents",type:"api",module:"SAL",name:"Case Documents Aggregate",status:"active",description:"Returns all linked docs as jsonb array" },
  { object_id:"api:bop_check_doc_flow_integrity",type:"api",module:"SYS",name:"Doc-Flow Integrity Check RPC",status:"active",description:"Finds orphan docs missing doc_flow links" },
  { object_id:"api:bop_guard_status_update",type:"api",module:"SYS",name:"Status Guard Trigger",status:"active",description:"Blocks direct status UPDATE outside RPCs" },
  { object_id:"api:bop_set_rpc_context",type:"api",module:"SYS",name:"Set RPC Context",status:"active",description:"Sets GUC flag for guard trigger bypass" },
  // Database Console APIs
  { object_id:"api:dba/overview:GET",type:"api",module:"DBA",name:"GET Database Overview",route:"/api/bop/dba/overview",status:"active" },
  { object_id:"api:dba/schema:GET",type:"api",module:"DBA",name:"GET Schema Info",route:"/api/bop/dba/schema",status:"active" },
  { object_id:"api:dba/tables:GET",type:"api",module:"DBA",name:"GET Table Data",route:"/api/bop/dba/tables",status:"active" },
  { object_id:"api:dba/tables:POST",type:"api",module:"DBA",name:"Mutate Table Data",route:"/api/bop/dba/tables",status:"active" },
  { object_id:"api:dba/sql:POST",type:"api",module:"DBA",name:"Execute SQL",route:"/api/bop/dba/sql",status:"active" },
  { object_id:"api:dba/functions:GET",type:"api",module:"DBA",name:"GET Functions",route:"/api/bop/dba/functions",status:"active" },
  { object_id:"api:dba/actions:POST",type:"api",module:"DBA",name:"Database Action",route:"/api/bop/dba/actions",status:"active" },
  { object_id:"api:dba/sql:GET",type:"api",module:"DBA",name:"GET Query History / Stats / Classify",route:"/api/bop/dba/sql",status:"active" },
  { object_id:"api:dba/migrations:GET",type:"api",module:"DBA",name:"GET Migrations",route:"/api/bop/dba/migrations",status:"active" },
  { object_id:"api:dba/migrations:POST",type:"api",module:"DBA",name:"Apply Migration",route:"/api/bop/dba/migrations",status:"active" },
  { object_id:"api:dba/health:GET",type:"api",module:"DBA",name:"GET Database Health",route:"/api/bop/dba/health",status:"active" },
  { object_id:"api:dba/health:run_audit",type:"api",module:"DBA",name:"Run Health Audit",route:"/api/bop/dba/health?action=run_audit",status:"active" },
  { object_id:"api:dba/health:run_vacuum",type:"api",module:"DBA",name:"Run Vacuum Now",route:"/api/bop/dba/health?action=run_vacuum",status:"active" },
  { object_id:"api:dba/health:cron_history",type:"api",module:"DBA",name:"GET Cron Job History",route:"/api/bop/dba/health?action=cron_history",status:"active" },
  { object_id:"api:dba/health:trend",type:"api",module:"DBA",name:"GET Audit History Trend",route:"/api/bop/dba/health?action=trend",status:"active" },
  { object_id:"api:dba/schema:table_health",type:"api",module:"DBA",name:"GET Per-Table Health",route:"/api/bop/dba/schema?action=table_health",status:"active" },
  { object_id:"api:dba/schema:tables_health",type:"api",module:"DBA",name:"GET Bulk Table Health",route:"/api/bop/dba/schema?action=tables_health",status:"active" },
];

export const TABLE_OBJECTS: BopObject[] = [
  { object_id:"table:crm_leads",type:"table",module:"CRM",name:"crm_leads",status:"active" },
  { object_id:"table:crm_activities",type:"table",module:"CRM",name:"crm_activities",status:"active" },
  { object_id:"table:ast_vehicles",type:"table",module:"AST",name:"ast_vehicles",status:"active" },
  { object_id:"table:ast_costs",type:"table",module:"AST",name:"ast_costs",status:"active" },
  { object_id:"table:fin_invoices",type:"table",module:"FIN",name:"fin_invoices",status:"active" },
  { object_id:"table:fin_payments",type:"table",module:"FIN",name:"fin_payments",status:"active" },
  { object_id:"table:fin_expenses",type:"table",module:"FIN",name:"fin_expenses",status:"active" },
  { object_id:"table:mkp_listings",type:"table",module:"MKP",name:"mkp_listings",status:"active" },
  { object_id:"table:mdm_business_partners",type:"table",module:"MDM",name:"mdm_business_partners",status:"active" },
  { object_id:"table:mdm_taxonomy",type:"table",module:"MDM",name:"mdm_taxonomy",status:"active" },
  { object_id:"table:sal_orders",type:"table",module:"SAL",name:"sal_orders",status:"active" },
  { object_id:"table:sal_handovers",type:"table",module:"SAL",name:"sal_handovers",status:"active" },
  { object_id:"table:bop_invoice_transitions",type:"table",module:"FIN",name:"bop_invoice_transitions",status:"active" },
  { object_id:"table:bop_handover_transitions",type:"table",module:"SAL",name:"bop_handover_transitions",status:"active" },
  { object_id:"table:sal_warranties",type:"table",module:"SAL",name:"sal_warranties",status:"active" },
  { object_id:"table:sal_warranty_claims",type:"table",module:"SAL",name:"sal_warranty_claims",status:"active" },
  { object_id:"table:sal_surveys",type:"table",module:"SAL",name:"sal_surveys",status:"active" },
  { object_id:"table:sal_quotations",type:"table",module:"SAL",name:"sal_quotations",status:"active" },
  { object_id:"table:bop_screens",type:"table",module:"SYS",name:"bop_screens",status:"active",description:"Screen registry - TC authoritative" },
  { object_id:"table:bop_modules",type:"table",module:"SYS",name:"bop_modules",status:"active" },
  { object_id:"table:bop_roles",type:"table",module:"SYS",name:"bop_roles",status:"active" },
  { object_id:"table:bop_role_screens",type:"table",module:"SYS",name:"bop_role_screens",status:"active" },
  { object_id:"table:bop_change_log",type:"table",module:"SYS",name:"bop_change_log",status:"active",description:"Immutable audit trail" },
  { object_id:"table:bop_settings",type:"table",module:"SYS",name:"bop_settings",status:"active" },
  { object_id:"table:bop_objects",type:"table",module:"SYS",name:"bop_objects",status:"active" },
  { object_id:"table:bop_dependencies",type:"table",module:"SYS",name:"bop_dependencies",status:"active" },
  { object_id:"table:bop_mkt_campaigns",type:"table",module:"MKT",name:"bop_mkt_campaigns",status:"active" },
  { object_id:"table:bop_mkt_generations",type:"table",module:"MKT",name:"bop_mkt_generations",status:"active" },
  { object_id:"table:bop_mkt_outputs",type:"table",module:"MKT",name:"bop_mkt_outputs",status:"active" },
  { object_id:"table:bop_mkt_assets",type:"table",module:"MKT",name:"bop_mkt_assets",status:"active" },
  { object_id:"table:bop_mkt_publications",type:"table",module:"MKT",name:"bop_mkt_publications",status:"active" },
  { object_id:"table:bop_mkt_brand_profiles",type:"table",module:"MKT",name:"bop_mkt_brand_profiles",status:"active" },
  { object_id:"table:bop_mkt_channels",type:"table",module:"MKT",name:"bop_mkt_channels",status:"active" },
  { object_id:"table:bop_brands",type:"table",module:"INV",name:"bop_brands",status:"active" },
  { object_id:"table:bop_models",type:"table",module:"INV",name:"bop_models",status:"active" },
  { object_id:"table:bop_body_types",type:"table",module:"MKP",name:"bop_body_types",status:"active",description:"Opbouw/carrosserie taxonomy — 4-digit numeric codes, parent = code/100" },
  { object_id:"table:bop_body_type_labels",type:"table",module:"MKP",name:"bop_body_type_labels",status:"active",description:"Per-locale labels for bop_body_types (code + locale)" },
  { object_id:"table:bop_listing_categories",type:"table",module:"MKP",name:"bop_listing_categories",status:"active",description:"Main listing categories — 1000-step numeric codes; slug = category enum value" },
  { object_id:"table:bop_listing_specs_car",type:"table",module:"MKP",name:"bop_listing_specs_car",status:"active",description:"Passenger car specs — NL dealer-standard fields; license_plate enables RDW autofill" },
  { object_id:"table:bop_object_locks",type:"table",module:"SYS",name:"bop_object_locks",status:"active",description:"Object Lock Service (OLS) — SAP-style pessimistic locks, atomic acquire, 4-min lease" },
  { object_id:"table:bop_cases",type:"table",module:"SAL",name:"bop_cases",status:"active",description:"Business Case — links all trade documents in a transaction lifecycle" },
  { object_id:"table:bop_doc_flow",type:"table",module:"SAL",name:"bop_doc_flow",status:"active",description:"Document chain — conversion/linking between business objects" },
  { object_id:"table:bop_status_transitions",type:"table",module:"SYS",name:"bop_status_transitions",status:"active",description:"Audit trail for every status change on any business object" },
  { object_id:"table:bop_customer_approvals",type:"table",module:"SAL",name:"bop_customer_approvals",status:"active",description:"Token-based customer approval gates with signature capture" },
  { object_id:"table:bop_conversion_rules",type:"table",module:"SYS",name:"bop_conversion_rules",status:"active",description:"Which source object+status can create which target" },
  { object_id:"table:bop_copy_control",type:"table",module:"SYS",name:"bop_copy_control",status:"active",description:"Field mapping during object conversion" },
  { object_id:"table:bop_lead_transitions",type:"table",module:"CRM",name:"bop_lead_transitions",status:"active",description:"Lead status machine adjacency table" },
  { object_id:"table:bop_listing_category_labels",type:"table",module:"MKP",name:"bop_listing_category_labels",status:"active",description:"Per-locale labels for bop_listing_categories" },
  { object_id:"table:wrk_technicians",type:"table",module:"WRK",name:"wrk_technicians",status:"active",description:"Workshop technicians with grade and specializations" },
  { object_id:"table:wrk_orders",type:"table",module:"WRK",name:"wrk_orders",status:"active",description:"Work orders with status machine and auto-numbering" },
  { object_id:"table:wrk_order_lines",type:"table",module:"WRK",name:"wrk_order_lines",status:"active",description:"WO line items — labour, parts, sublet, sundry" },
  { object_id:"table:wrk_inspections",type:"table",module:"WRK",name:"wrk_inspections",status:"active",description:"Vehicle inspection checklists with condition grading" },
  { object_id:"table:wrk_labour_rates",type:"table",module:"WRK",name:"wrk_labour_rates",status:"active",description:"Time-bound hourly rates per technician grade" },
  { object_id:"table:wrk_service_packages",type:"table",module:"WRK",name:"wrk_service_packages",status:"active",description:"Recipe-based service packages with parts and labour" },
  { object_id:"table:wrk_apk_reminders",type:"table",module:"WRK",name:"wrk_apk_reminders",status:"active",description:"APK expiry tracking and reminder campaigns" },
  { object_id:"table:wrk_approvals",type:"table",module:"WRK",name:"wrk_approvals",status:"active",description:"Token-based customer approval for extra work" },
  { object_id:"table:wrk_efficiency_metrics",type:"table",module:"WRK",name:"wrk_efficiency_metrics",status:"active",description:"Daily technician efficiency standard vs present hours" },
  { object_id:"table:wrk_planning_slots",type:"table",module:"WRK",name:"wrk_planning_slots",status:"active",description:"Workshop planning board time slots" },
  { object_id:"table:wrk_autoflex_config",type:"table",module:"WRK",name:"wrk_autoflex_config",status:"active",description:"Autoflex DMS connection configuration per tenant" },
  { object_id:"table:wrk_autoflex_sync_logs",type:"table",module:"WRK",name:"wrk_autoflex_sync_logs",status:"active",description:"Autoflex sync operation history and results" },
  { object_id:"table:wrk_autoflex_field_maps",type:"table",module:"WRK",name:"wrk_autoflex_field_maps",status:"active",description:"Configurable field mappings between Autoflex and BOP entities" },
  { object_id:"table:bop_db_health_log",type:"table",module:"DBA",name:"bop_db_health_log",status:"active",description:"Database health audit snapshot log with finding counts and summaries" },
];

export const COMPONENT_OBJECTS: BopObject[] = [
  { object_id:"component:ScreenHeader",type:"component",module:"SYS",name:"ScreenHeader",source_path:"components/ScreenBadge.tsx",status:"active" },
  { object_id:"component:Sidebar",type:"component",module:"SYS",name:"Sidebar",source_path:"components/Sidebar.tsx",status:"active" },
  { object_id:"component:ConsoleLayout",type:"component",module:"SYS",name:"ConsoleLayout",source_path:"app/console/layout.tsx",status:"active" },
];

export const MODULE_OBJECTS: BopObject[] = [
  { object_id:"module:AIM",type:"module",module:"AIM",name:"AI Module",status:"active" },
  { object_id:"module:CRM",type:"module",module:"CRM",name:"CRM",status:"active" },
  { object_id:"module:AST",type:"module",module:"AST",name:"Assets",status:"active" },
  { object_id:"module:FIN",type:"module",module:"FIN",name:"Finance",status:"active" },
  { object_id:"module:MKP",type:"module",module:"MKP",name:"Marketplace",status:"active" },
  { object_id:"module:MDM",type:"module",module:"MDM",name:"Master Data",status:"active" },
  { object_id:"module:SAL",type:"module",module:"SAL",name:"Sales",status:"active" },
  { object_id:"module:SYS",type:"module",module:"SYS",name:"System",status:"active" },
  { object_id:"module:MKT",type:"module",module:"MKT",name:"Market Intel",status:"active" },
  { object_id:"module:INV",type:"module",module:"INV",name:"Inventory",status:"active" },
  { object_id:"module:OPS",type:"module",module:"OPS",name:"Operations",status:"active" },
  { object_id:"module:WRK",type:"module",module:"WRK",name:"Workshop",status:"active" },
];

export const ALL_OBJECTS: BopObject[] = [
  ...MODULE_OBJECTS,
  ...TABLE_OBJECTS,
  ...COMPONENT_OBJECTS,
  ...API_OBJECTS,
  ...SCREEN_OBJECTS,
];

export const ALL_DEPENDENCIES: BopDependency[] = [
  { from_id:"screen:CR001",to_id:"api:crm/leads:GET",dep_type:"calls" },
  { from_id:"screen:CR001",to_id:"api:crm/leads:POST",dep_type:"calls" },
  { from_id:"screen:CR002",to_id:"api:crm/leads/[id]:GET",dep_type:"calls" },
  { from_id:"screen:CR002",to_id:"api:crm/leads/[id]:PATCH",dep_type:"calls" },
  { from_id:"screen:CR003",to_id:"api:crm/leads:GET",dep_type:"calls" },
  { from_id:"screen:CR004",to_id:"api:crm/activities:GET",dep_type:"calls" },
  { from_id:"screen:CR006",to_id:"api:crm/leads:GET",dep_type:"calls" },
  { from_id:"api:crm/leads:GET",to_id:"table:crm_leads",dep_type:"reads" },
  { from_id:"api:crm/leads:POST",to_id:"table:crm_leads",dep_type:"writes" },
  { from_id:"api:crm/leads/[id]:GET",to_id:"table:crm_leads",dep_type:"reads" },
  { from_id:"api:crm/leads/[id]:PATCH",to_id:"table:crm_leads",dep_type:"writes" },
  { from_id:"api:crm/leads/[id]:DELETE",to_id:"table:crm_leads",dep_type:"writes" },
  { from_id:"api:crm/activities:GET",to_id:"table:crm_activities",dep_type:"reads" },
  { from_id:"screen:AS001",to_id:"api:ast/assets:GET",dep_type:"calls" },
  { from_id:"screen:AS002",to_id:"api:ast/assets/[id]:GET",dep_type:"calls" },
  { from_id:"screen:AS003",to_id:"api:ast/lifecycle:GET",dep_type:"calls" },
  { from_id:"screen:AS004",to_id:"api:ast/costs:GET",dep_type:"calls" },
  { from_id:"api:ast/assets:GET",to_id:"table:ast_vehicles",dep_type:"reads" },
  { from_id:"api:ast/assets:POST",to_id:"table:ast_vehicles",dep_type:"writes" },
  { from_id:"api:ast/costs:GET",to_id:"table:ast_costs",dep_type:"reads" },
  { from_id:"screen:FI001",to_id:"api:fin/invoices:GET",dep_type:"calls" },
  { from_id:"screen:FI002",to_id:"api:fin/payments:GET",dep_type:"calls" },
  { from_id:"screen:FI012",to_id:"api:fin/ap/invoices:GET",dep_type:"calls" },
  { from_id:"api:fin/invoices:GET",to_id:"table:fin_invoices",dep_type:"reads" },
  { from_id:"api:fin/invoices:POST",to_id:"table:fin_invoices",dep_type:"writes" },
  { from_id:"api:fin/payments:GET",to_id:"table:fin_payments",dep_type:"reads" },
  { from_id:"api:fin/ap/invoices:GET",to_id:"table:fin_invoices",dep_type:"reads" },
  { from_id:"screen:MP001",to_id:"api:mkp/listings:GET",dep_type:"calls" },
  { from_id:"screen:MP002",to_id:"api:mkp/listings:GET",dep_type:"calls" },
  { from_id:"screen:MP003",to_id:"api:mkp/listings/[id]:PATCH",dep_type:"calls" },
  { from_id:"api:mkp/listings:GET",to_id:"table:mkp_listings",dep_type:"reads" },
  { from_id:"api:mkp/listings:POST",to_id:"table:mkp_listings",dep_type:"writes" },
  { from_id:"screen:MD001",to_id:"api:md/partners:GET",dep_type:"calls" },
  { from_id:"screen:MD002",to_id:"api:md/partners:GET",dep_type:"calls" },
  { from_id:"screen:MD003",to_id:"api:md/taxonomy:GET",dep_type:"calls" },
  { from_id:"api:md/partners:GET",to_id:"table:mdm_business_partners",dep_type:"reads" },
  { from_id:"api:md/taxonomy:GET",to_id:"table:mdm_taxonomy",dep_type:"reads" },
  { from_id:"screen:SA001",to_id:"api:sal/quotations:GET",dep_type:"calls" },
  { from_id:"screen:SA002",to_id:"api:sal/quotations:GET",dep_type:"calls" },
  { from_id:"screen:SA009",to_id:"api:sal/orders:GET",dep_type:"calls" },
  { from_id:"screen:SA010",to_id:"api:sal/orders:GET",dep_type:"calls" },
  { from_id:"api:sal/orders:GET",to_id:"table:sal_orders",dep_type:"reads" },
  { from_id:"api:sal/orders:POST",to_id:"table:sal_orders",dep_type:"writes" },
  { from_id:"api:sal/quotations:GET",to_id:"table:sal_quotations",dep_type:"reads" },
  { from_id:"api:sal/quotations:POST",to_id:"table:sal_quotations",dep_type:"writes" },
  { from_id:"screen:SY001",to_id:"api:sys/users:GET",dep_type:"calls" },
  { from_id:"screen:SY002",to_id:"api:sys/roles:GET",dep_type:"calls" },
  { from_id:"screen:SY004",to_id:"api:sys/settings:GET",dep_type:"calls" },
  { from_id:"screen:SY004",to_id:"api:sys/settings:PUT",dep_type:"calls" },
  { from_id:"screen:SY005",to_id:"api:sys/health:GET",dep_type:"calls" },
  { from_id:"screen:SY008",to_id:"api:sys/health:GET",dep_type:"calls" },
  { from_id:"screen:SY011",to_id:"api:sys/roles:GET",dep_type:"calls" },
  { from_id:"screen:SY012",to_id:"api:access-audit:GET",dep_type:"calls" },
  { from_id:"screen:SY016",to_id:"api:access-audit:GET",dep_type:"calls" },
  { from_id:"screen:SY024",to_id:"api:sys/screens:GET",dep_type:"calls" },
  { from_id:"screen:SY028",to_id:"api:sys/objects:GET",dep_type:"calls" },
  { from_id:"screen:SY028",to_id:"api:sys/dependencies:GET",dep_type:"calls" },
  { from_id:"api:sys/screens:GET",to_id:"table:bop_screens",dep_type:"reads" },
  { from_id:"api:sys/roles:GET",to_id:"table:bop_roles",dep_type:"reads" },
  { from_id:"api:sys/settings:GET",to_id:"table:bop_settings",dep_type:"reads" },
  { from_id:"api:sys/settings:PUT",to_id:"table:bop_settings",dep_type:"writes" },
  { from_id:"api:access-audit:GET",to_id:"table:bop_change_log",dep_type:"reads" },
  { from_id:"api:sys/objects:GET",to_id:"table:bop_objects",dep_type:"reads" },
  { from_id:"api:sys/objects:POST",to_id:"table:bop_objects",dep_type:"writes" },
  { from_id:"api:sys/dependencies:GET",to_id:"table:bop_dependencies",dep_type:"reads" },
  { from_id:"api:sys/dependencies:POST",to_id:"table:bop_dependencies",dep_type:"writes" },
  { from_id:"screen:CR001",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"screen:AS001",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"screen:FI001",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"screen:MP001",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"screen:MD001",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"screen:SA001",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"screen:SY001",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"screen:AI001",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"screen:SY028",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"screen:MK006",to_id:"api:mkt/generate:POST",dep_type:"calls" },
  { from_id:"screen:MK006",to_id:"api:mkt/meta:GET",dep_type:"calls" },
  { from_id:"screen:MK006",to_id:"api:mkt/campaigns:GET",dep_type:"calls" },
  { from_id:"screen:MK006",to_id:"api:mkt/campaigns/[id]:GET",dep_type:"calls" },
  { from_id:"screen:MK006",to_id:"api:mkt/outputs/[id]:PATCH",dep_type:"calls" },
  { from_id:"screen:MK006",to_id:"api:mkt/publish:POST",dep_type:"calls" },
  { from_id:"screen:MK004",to_id:"api:mkt/brand:GET",dep_type:"calls" },
  { from_id:"screen:MK004",to_id:"api:mkt/brand:PATCH",dep_type:"calls" },
  { from_id:"api:mkt/generate:POST",to_id:"table:bop_mkt_brand_profiles",dep_type:"reads" },
  { from_id:"api:mkt/generate:POST",to_id:"table:bop_mkt_channels",dep_type:"reads" },
  { from_id:"api:mkt/generate:POST",to_id:"table:bop_mkt_campaigns",dep_type:"writes" },
  { from_id:"api:mkt/generate:POST",to_id:"table:bop_mkt_generations",dep_type:"writes" },
  { from_id:"api:mkt/generate:POST",to_id:"table:bop_mkt_outputs",dep_type:"writes" },
  { from_id:"api:mkt/meta:GET",to_id:"table:bop_mkt_channels",dep_type:"reads" },
  { from_id:"api:mkt/meta:GET",to_id:"table:bop_mkt_brand_profiles",dep_type:"reads" },
  { from_id:"api:mkt/campaigns:GET",to_id:"table:bop_mkt_campaigns",dep_type:"reads" },
  { from_id:"api:mkt/campaigns:DELETE",to_id:"table:bop_mkt_campaigns",dep_type:"writes" },
  { from_id:"api:mkt/campaigns/[id]:GET",to_id:"table:bop_mkt_campaigns",dep_type:"reads" },
  { from_id:"api:mkt/campaigns/[id]:GET",to_id:"table:bop_mkt_outputs",dep_type:"reads" },
  { from_id:"api:mkt/campaigns/[id]:GET",to_id:"table:bop_mkt_publications",dep_type:"reads" },
  { from_id:"api:mkt/outputs/[id]:PATCH",to_id:"table:bop_mkt_outputs",dep_type:"writes" },
  { from_id:"api:mkt/publish:POST",to_id:"table:bop_mkt_outputs",dep_type:"writes" },
  { from_id:"api:mkt/publish:POST",to_id:"table:bop_mkt_publications",dep_type:"writes" },
  { from_id:"api:mkt/publish:POST",to_id:"table:bop_mkt_campaigns",dep_type:"writes" },
  { from_id:"api:mkt/brand:GET",to_id:"table:bop_mkt_brand_profiles",dep_type:"reads" },
  { from_id:"api:mkt/brand:PATCH",to_id:"table:bop_mkt_brand_profiles",dep_type:"writes" },
  { from_id:"screen:IN002",to_id:"api:mkp/brands:GET",dep_type:"calls" },
  { from_id:"screen:IN002",to_id:"api:mkp/brands:POST",dep_type:"calls" },
  { from_id:"screen:IN002",to_id:"api:mkp/brands/[id]:PATCH",dep_type:"calls" },
  { from_id:"screen:IN002",to_id:"api:mkp/brands/[id]:DELETE",dep_type:"calls" },
  { from_id:"screen:IN002",to_id:"api:mkp/brands/[id]/models:GET",dep_type:"calls" },
  { from_id:"screen:IN002",to_id:"api:mkp/brands/[id]/models:POST",dep_type:"calls" },
  { from_id:"api:mkp/brands:GET",to_id:"table:bop_brands",dep_type:"reads" },
  { from_id:"api:mkp/brands:GET",to_id:"table:bop_models",dep_type:"reads" },
  { from_id:"api:mkp/brands:POST",to_id:"table:bop_brands",dep_type:"writes" },
  { from_id:"api:mkp/brands/[id]:PATCH",to_id:"table:bop_brands",dep_type:"writes" },
  { from_id:"api:mkp/brands/[id]:DELETE",to_id:"table:bop_brands",dep_type:"writes" },
  { from_id:"api:mkp/brands/[id]/models:GET",to_id:"table:bop_models",dep_type:"reads" },
  { from_id:"api:mkp/brands/[id]/models:POST",to_id:"table:bop_models",dep_type:"writes" },
  { from_id:"screen:IN006",to_id:"api:mkp/models:GET",dep_type:"calls" },
  { from_id:"screen:IN006",to_id:"api:mkp/models:POST",dep_type:"calls" },
  { from_id:"api:mkp/models:GET",to_id:"table:bop_models",dep_type:"reads" },
  { from_id:"api:mkp/models:GET",to_id:"table:bop_brands",dep_type:"reads" },
  { from_id:"api:mkp/models:POST",to_id:"table:bop_models",dep_type:"writes" },
  { from_id:"api:mkp/bop-listings/meta:GET",to_id:"table:bop_body_types",dep_type:"reads" },
  { from_id:"api:mkp/bop-listings/meta:GET",to_id:"table:bop_body_type_labels",dep_type:"reads" },
  { from_id:"screen:SY032",to_id:"api:sys/locks:GET",dep_type:"calls" },
  { from_id:"screen:SY032",to_id:"api:sys/locks:DELETE",dep_type:"calls" },
  { from_id:"screen:MP003",to_id:"api:sys/locks:POST",dep_type:"calls" },
  { from_id:"screen:MP003",to_id:"api:sys/locks:PUT",dep_type:"calls" },
  { from_id:"screen:MP003",to_id:"api:sys/locks:DELETE",dep_type:"calls" },
  { from_id:"api:sys/locks:GET",to_id:"table:bop_object_locks",dep_type:"reads" },
  { from_id:"api:sys/locks:POST",to_id:"table:bop_object_locks",dep_type:"writes" },
  { from_id:"api:sys/locks:PUT",to_id:"table:bop_object_locks",dep_type:"writes" },
  { from_id:"api:sys/locks:DELETE",to_id:"table:bop_object_locks",dep_type:"writes" },
  { from_id:"api:mkp/bop-listings/[id]:PATCH",to_id:"table:bop_object_locks",dep_type:"reads" },
  { from_id:"api:mkp/bop-listings/[id]:GET",to_id:"table:bop_listing_specs_car",dep_type:"reads" },
  { from_id:"api:mkp/bop-listings/[id]:PATCH",to_id:"table:bop_listing_specs_car",dep_type:"writes" },
  { from_id:"api:mkp/bop-listings/meta:GET",to_id:"table:bop_listing_categories",dep_type:"reads" },
  { from_id:"api:mkp/bop-listings/meta:GET",to_id:"table:bop_listing_category_labels",dep_type:"reads" },
  { from_id:"screen:IN003",to_id:"api:mkp/taxonomy:GET",dep_type:"calls" },
  { from_id:"api:mkp/taxonomy:GET",to_id:"table:bop_listing_categories",dep_type:"reads" },
  { from_id:"api:mkp/taxonomy:GET",to_id:"table:bop_listing_category_labels",dep_type:"reads" },
  { from_id:"api:mkp/taxonomy:GET",to_id:"table:bop_body_types",dep_type:"reads" },
  { from_id:"api:mkp/taxonomy:GET",to_id:"table:bop_body_type_labels",dep_type:"reads" },
  { from_id:"api:mkp/taxonomy:GET",to_id:"table:bop_listings",dep_type:"reads" },
  { from_id:"api:mkp/bop-listings/[id]:PATCH",to_id:"table:bop_body_types",dep_type:"reads" },
  { from_id:"screen:MP003",to_id:"api:mkp/media/upload:POST",dep_type:"calls" },
  { from_id:"screen:MP003",to_id:"api:mkp/media/[id]:DELETE",dep_type:"calls" },
  { from_id:"screen:MP003",to_id:"api:mkp/media/[id]:PATCH",dep_type:"calls" },
  { from_id:"api:mkp/media/[id]:PATCH",to_id:"table:bop_listing_media",dep_type:"writes" },
  { from_id:"screen:MP003",to_id:"api:mkp/media/reorder:POST",dep_type:"calls" },
  { from_id:"api:mkp/media/upload:POST",to_id:"table:bop_listing_media",dep_type:"writes" },
  { from_id:"api:mkp/media/[id]:DELETE",to_id:"table:bop_listing_media",dep_type:"writes" },
  { from_id:"api:mkp/media/reorder:POST",to_id:"table:bop_listing_media",dep_type:"writes" },
  { from_id:"screen:SY036",to_id:"api:bop/comm/styles:GET",dep_type:"calls" },
  { from_id:"screen:SY036",to_id:"api:bop/comm/branding:GET",dep_type:"calls" },
  { from_id:"screen:SY036",to_id:"api:bop/comm/branding:POST",dep_type:"calls" },
  { from_id:"screen:SY037",to_id:"api:bop/comm/automation:GET",dep_type:"calls" },
  { from_id:"screen:SY037",to_id:"api:bop/comm/automation:POST",dep_type:"calls" },
  { from_id:"screen:SY037",to_id:"api:bop/comm/automation:DELETE",dep_type:"calls" },
  { from_id:"screen:SY038",to_id:"api:bop/comm/history:GET",dep_type:"calls" },
  { from_id:"screen:SY039",to_id:"api:bop/comm/templates:GET",dep_type:"calls" },
  { from_id:"screen:SY039",to_id:"api:bop/comm/templates:POST",dep_type:"calls" },
  { from_id:"screen:SY039",to_id:"api:bop/comm/templates:DELETE",dep_type:"calls" },
  { from_id:"screen:SY039",to_id:"api:bop/comm/compose/preview:POST",dep_type:"calls" },
  { from_id:"screen:SY040",to_id:"api:support/requests:GET",dep_type:"calls" },
  { from_id:"screen:SY040",to_id:"api:support/requests/[id]:PATCH",dep_type:"calls" },
  { from_id:"screen:SY040",to_id:"api:support/requests/[id]/messages:POST",dep_type:"calls" },
  { from_id:"screen:SY041",to_id:"api:bop/dealer-applications:GET",dep_type:"calls" },
  { from_id:"screen:SY041",to_id:"api:bop/dealer-applications/[id]:PATCH",dep_type:"calls" },
  { from_id:"api:bop/comm/styles:GET",to_id:"table:bop_comm_master_styles",dep_type:"reads" },
  { from_id:"api:bop/comm/branding:GET",to_id:"table:bop_comm_branding",dep_type:"reads" },
  { from_id:"api:bop/comm/branding:POST",to_id:"table:bop_comm_branding",dep_type:"writes" },
  { from_id:"api:bop/comm/automation:GET",to_id:"table:bop_comm_automation",dep_type:"reads" },
  { from_id:"api:bop/comm/automation:POST",to_id:"table:bop_comm_automation",dep_type:"writes" },
  { from_id:"api:bop/comm/history:GET",to_id:"table:bop_comm_history",dep_type:"reads" },
  { from_id:"api:bop/comm/templates:GET",to_id:"table:bop_comm_templates",dep_type:"reads" },
  { from_id:"api:bop/comm/templates:POST",to_id:"table:bop_comm_templates",dep_type:"writes" },
  // Trade Flow Engine — Phase 0 foundation
  { from_id:"table:bop_doc_flow",to_id:"table:bop_cases",dep_type:"reads" },
  { from_id:"table:bop_customer_approvals",to_id:"table:bop_cases",dep_type:"reads" },
  { from_id:"table:bop_copy_control",to_id:"table:bop_conversion_rules",dep_type:"reads" },
  { from_id:"table:bop_status_transitions",to_id:"table:bop_cases",dep_type:"reads" },
  { from_id:"table:bop_doc_flow",to_id:"table:sal_quotations",dep_type:"reads" },
  { from_id:"table:bop_doc_flow",to_id:"table:sal_orders",dep_type:"reads" },
  { from_id:"table:bop_doc_flow",to_id:"table:fin_invoices",dep_type:"reads" },
  // P4 Invoice Linking dependencies
  { from_id:"screen:FI011",to_id:"api:fin/invoices/[id]/transition:GET",dep_type:"calls" },
  { from_id:"screen:FI011",to_id:"api:fin/invoices/[id]/transition:POST",dep_type:"calls" },
  { from_id:"api:fin/invoices/[id]/transition:GET",to_id:"api:bop_invoice_allowed_transitions",dep_type:"calls" },
  { from_id:"api:fin/invoices/[id]/transition:POST",to_id:"api:bop_invoice_transition",dep_type:"calls" },
  { from_id:"api:bop_invoice_transition",to_id:"table:bop_invoice_transitions",dep_type:"reads" },
  { from_id:"api:bop_invoice_transition",to_id:"table:fin_invoices",dep_type:"writes" },
  { from_id:"api:fin/invoices/from-order:POST",to_id:"api:bop_create_invoice_from_order",dep_type:"calls" },
  { from_id:"api:bop_create_invoice_from_order",to_id:"table:fin_invoices",dep_type:"writes" },
  { from_id:"api:bop_create_invoice_from_order",to_id:"table:sal_orders",dep_type:"reads" },
  { from_id:"api:bop_create_invoice_from_order",to_id:"table:bop_doc_flow",dep_type:"writes" },
  // P5 Handover dependencies
  { from_id:"screen:SA019",to_id:"api:sal/handovers:GET",dep_type:"calls" },
  { from_id:"screen:SA020",to_id:"api:sal/handovers/[id]:GET",dep_type:"calls" },
  { from_id:"screen:SA020",to_id:"api:sal/handovers/[id]:PATCH",dep_type:"calls" },
  { from_id:"screen:SA020",to_id:"api:sal/handovers/[id]/transition:GET",dep_type:"calls" },
  { from_id:"screen:SA020",to_id:"api:sal/handovers/[id]/transition:POST",dep_type:"calls" },
  { from_id:"screen:SA020",to_id:"api:sal/handovers/[id]/complete:POST",dep_type:"calls" },
  { from_id:"api:sal/handovers:GET",to_id:"table:sal_handovers",dep_type:"reads" },
  { from_id:"api:sal/handovers/[id]:PATCH",to_id:"table:sal_handovers",dep_type:"writes" },
  { from_id:"api:sal/handovers/[id]/transition:GET",to_id:"api:bop_handover_allowed_transitions",dep_type:"calls" },
  { from_id:"api:sal/handovers/[id]/transition:POST",to_id:"api:bop_handover_transition",dep_type:"calls" },
  { from_id:"api:bop_handover_transition",to_id:"table:bop_handover_transitions",dep_type:"reads" },
  { from_id:"api:bop_handover_transition",to_id:"table:sal_handovers",dep_type:"writes" },
  { from_id:"api:sal/handovers/[id]/complete:POST",to_id:"api:bop_handover_complete",dep_type:"calls" },
  { from_id:"api:bop_handover_complete",to_id:"table:sal_handovers",dep_type:"writes" },
  { from_id:"api:bop_handover_complete",to_id:"table:sal_orders",dep_type:"writes" },
  { from_id:"api:sal/handovers/from-order:POST",to_id:"api:bop_create_handover_from_order",dep_type:"calls" },
  { from_id:"api:bop_create_handover_from_order",to_id:"table:sal_handovers",dep_type:"writes" },
  { from_id:"api:bop_create_handover_from_order",to_id:"table:sal_orders",dep_type:"writes" },
  // P6 Post-Sale dependencies
  { from_id:"screen:SA021",to_id:"api:sal/warranties:GET",dep_type:"calls" },
  { from_id:"screen:SA022",to_id:"api:sal/warranties/[id]:GET",dep_type:"calls" },
  { from_id:"screen:SA022",to_id:"api:sal/warranties/[id]:PATCH",dep_type:"calls" },
  { from_id:"screen:SA022",to_id:"api:sal/warranties/[id]/claims:GET",dep_type:"calls" },
  { from_id:"screen:SA022",to_id:"api:sal/warranties/[id]/claims:POST",dep_type:"calls" },
  { from_id:"screen:SA023",to_id:"api:sal/surveys:GET",dep_type:"calls" },
  { from_id:"api:sal/warranties:GET",to_id:"table:sal_warranties",dep_type:"reads" },
  { from_id:"api:sal/warranties/[id]:PATCH",to_id:"table:sal_warranties",dep_type:"writes" },
  { from_id:"api:sal/warranties/[id]/claims:POST",to_id:"table:sal_warranty_claims",dep_type:"writes" },
  { from_id:"api:sal/warranties/from-handover:POST",to_id:"api:bop_create_warranty_from_handover",dep_type:"calls" },
  { from_id:"api:bop_create_warranty_from_handover",to_id:"table:sal_warranties",dep_type:"writes" },
  { from_id:"api:bop_create_warranty_from_handover",to_id:"table:sal_handovers",dep_type:"writes" },
  { from_id:"api:sal/surveys/schedule:POST",to_id:"api:bop_schedule_survey",dep_type:"calls" },
  { from_id:"api:bop_schedule_survey",to_id:"table:sal_surveys",dep_type:"writes" },
  { from_id:"api:sal/surveys/[id]/submit:POST",to_id:"api:bop_submit_survey",dep_type:"calls" },
  { from_id:"api:bop_submit_survey",to_id:"table:sal_surveys",dep_type:"writes" },
  { from_id:"api:bop_expire_warranties",to_id:"table:sal_warranties",dep_type:"writes" },
  { from_id:"table:bop_cases",to_id:"table:mdm_business_partners",dep_type:"reads" },
  { from_id:"table:bop_cases",to_id:"table:ast_vehicles",dep_type:"reads" },
  // Trade Flow Engine — Phase 1 lead consolidation
  { from_id:"table:bop_lead_transitions",to_id:"table:crm_leads",dep_type:"reads" },
  { from_id:"api:bop_lead_allowed_transitions",to_id:"table:bop_lead_transitions",dep_type:"reads" },
  { from_id:"api:bop_lead_transition",to_id:"table:crm_leads",dep_type:"writes" },
  { from_id:"api:bop_lead_transition",to_id:"table:bop_status_transitions",dep_type:"writes" },
  { from_id:"api:bop_convert_lead",to_id:"table:crm_leads",dep_type:"writes" },
  { from_id:"api:bop_convert_lead",to_id:"table:bop_cases",dep_type:"writes" },
  { from_id:"api:bop_convert_lead",to_id:"table:bop_doc_flow",dep_type:"writes" },
  // Trade Flow Engine — Phase 2 quotation versioning
  { from_id:"table:bop_quotation_transitions",to_id:"table:sal_quotations",dep_type:"reads" },
  { from_id:"api:bop_quotation_send",to_id:"table:sal_quotations",dep_type:"writes" },
  { from_id:"api:bop_quotation_send",to_id:"table:bop_customer_approvals",dep_type:"writes" },
  { from_id:"api:bop_quotation_new_version",to_id:"table:sal_quotations",dep_type:"writes" },
  { from_id:"api:bop_quotation_new_version",to_id:"table:bop_doc_flow",dep_type:"writes" },
  { from_id:"api:bop_approval_respond",to_id:"table:bop_customer_approvals",dep_type:"writes" },
  { from_id:"api:bop_approval_respond",to_id:"table:sal_quotations",dep_type:"writes" },
  { from_id:"api:bop_approval_respond",to_id:"table:sal_orders",dep_type:"writes" },
  // Trade Flow Engine — Phase 3 order confirmation
  { from_id:"table:bop_order_transitions",to_id:"table:sal_orders",dep_type:"reads" },
  { from_id:"api:bop_order_confirm",to_id:"table:sal_orders",dep_type:"writes" },
  { from_id:"api:bop_order_confirm",to_id:"table:bop_customer_approvals",dep_type:"writes" },
  { from_id:"api:bop_order_cancel",to_id:"table:sal_orders",dep_type:"writes" },
  // Trade Flow Engine — Phase 7 Case Timeline + Guard Rails
  { from_id:"screen:TR000",to_id:"api:sal/cases:GET",dep_type:"calls" },
  { from_id:"screen:TR001",to_id:"api:sal/cases/[id]:GET",dep_type:"calls" },
  { from_id:"screen:TR001",to_id:"api:sal/cases/[id]/timeline:GET",dep_type:"calls" },
  { from_id:"screen:TR001",to_id:"api:sal/cases/[id]/documents:GET",dep_type:"calls" },
  { from_id:"api:sal/cases:GET",to_id:"table:bop_cases",dep_type:"reads" },
  { from_id:"api:sal/cases:GET",to_id:"api:case_stage",dep_type:"calls" },
  { from_id:"api:sal/cases/[id]:GET",to_id:"table:bop_cases",dep_type:"reads" },
  { from_id:"api:sal/cases/[id]:GET",to_id:"api:case_stage",dep_type:"calls" },
  { from_id:"api:sal/cases/[id]:GET",to_id:"api:case_documents",dep_type:"calls" },
  { from_id:"api:case_stage",to_id:"table:sal_quotations",dep_type:"reads" },
  { from_id:"api:case_stage",to_id:"table:sal_orders",dep_type:"reads" },
  { from_id:"api:case_stage",to_id:"table:fin_invoices",dep_type:"reads" },
  { from_id:"api:case_stage",to_id:"table:sal_handovers",dep_type:"reads" },
  { from_id:"api:case_stage",to_id:"table:sal_warranties",dep_type:"reads" },
  { from_id:"api:case_documents",to_id:"table:crm_leads",dep_type:"reads" },
  { from_id:"api:case_documents",to_id:"table:sal_quotations",dep_type:"reads" },
  { from_id:"api:case_documents",to_id:"table:sal_orders",dep_type:"reads" },
  { from_id:"api:case_documents",to_id:"table:fin_invoices",dep_type:"reads" },
  { from_id:"api:case_documents",to_id:"table:sal_handovers",dep_type:"reads" },
  { from_id:"api:case_documents",to_id:"table:sal_warranties",dep_type:"reads" },
  { from_id:"api:case_documents",to_id:"table:sal_surveys",dep_type:"reads" },
  { from_id:"api:vehicle_availability",to_id:"table:bop_object_locks",dep_type:"reads" },
  { from_id:"api:vehicle_availability",to_id:"table:sal_orders",dep_type:"reads" },
  { from_id:"api:bop_check_doc_flow_integrity",to_id:"table:sal_orders",dep_type:"reads" },
  { from_id:"api:bop_check_doc_flow_integrity",to_id:"table:fin_invoices",dep_type:"reads" },
  { from_id:"api:bop_check_doc_flow_integrity",to_id:"table:sal_handovers",dep_type:"reads" },
  { from_id:"api:bop_check_doc_flow_integrity",to_id:"table:bop_doc_flow",dep_type:"reads" },
  { from_id:"api:sys/integrity:GET",to_id:"api:bop_check_doc_flow_integrity",dep_type:"calls" },
  { from_id:"api:bop_guard_status_update",to_id:"table:crm_leads",dep_type:"reads" },
  { from_id:"api:bop_guard_status_update",to_id:"table:sal_quotations",dep_type:"reads" },
  { from_id:"api:bop_guard_status_update",to_id:"table:sal_orders",dep_type:"reads" },
  { from_id:"api:bop_guard_status_update",to_id:"table:fin_invoices",dep_type:"reads" },
  { from_id:"api:bop_guard_status_update",to_id:"table:sal_handovers",dep_type:"reads" },
  // Workshop Intelligence — screen→API dependencies
  { from_id:"screen:WK001",to_id:"api:wrk/dashboard:GET",dep_type:"calls" },
  { from_id:"screen:WK002",to_id:"api:wrk/orders:GET",dep_type:"calls" },
  { from_id:"screen:WK002",to_id:"api:wrk/orders:POST",dep_type:"calls" },
  { from_id:"screen:WK002",to_id:"api:wrk/orders:PATCH",dep_type:"calls" },
  { from_id:"screen:WK002",to_id:"api:wrk/plate-lookup:POST",dep_type:"calls" },
  { from_id:"screen:WK003",to_id:"api:wrk/planning:GET",dep_type:"calls" },
  { from_id:"screen:WK003",to_id:"api:wrk/planning:POST",dep_type:"calls" },
  { from_id:"screen:WK004",to_id:"api:wrk/efficiency:GET",dep_type:"calls" },
  { from_id:"screen:WK004",to_id:"api:wrk/efficiency:POST",dep_type:"calls" },
  { from_id:"screen:WK005",to_id:"api:wrk/inspections:GET",dep_type:"calls" },
  { from_id:"screen:WK005",to_id:"api:wrk/inspections:POST",dep_type:"calls" },
  { from_id:"screen:WK006",to_id:"api:wrk/apk-reminders:GET",dep_type:"calls" },
  { from_id:"screen:WK006",to_id:"api:wrk/apk-reminders:POST",dep_type:"calls" },
  { from_id:"screen:WK007",to_id:"api:wrk/approvals:GET",dep_type:"calls" },
  { from_id:"screen:WK007",to_id:"api:wrk/approvals:POST",dep_type:"calls" },
  { from_id:"screen:WK008",to_id:"api:wrk/status:GET",dep_type:"calls" },
  { from_id:"screen:WK009",to_id:"api:wrk/briefing:GET",dep_type:"calls" },
  { from_id:"screen:WK010",to_id:"api:wrk/recommendations:GET",dep_type:"calls" },
  { from_id:"screen:WK011",to_id:"api:wrk/rates:GET",dep_type:"calls" },
  { from_id:"screen:WK011",to_id:"api:wrk/rates:POST",dep_type:"calls" },
  { from_id:"screen:WK012",to_id:"api:wrk/packages:GET",dep_type:"calls" },
  { from_id:"screen:WK012",to_id:"api:wrk/packages:POST",dep_type:"calls" },
  // Workshop Intelligence — API→table dependencies
  { from_id:"api:wrk/orders:GET",to_id:"table:wrk_orders",dep_type:"reads" },
  { from_id:"api:wrk/orders:POST",to_id:"table:wrk_orders",dep_type:"writes" },
  { from_id:"api:wrk/orders:PATCH",to_id:"table:wrk_orders",dep_type:"writes" },
  { from_id:"api:wrk/orders:DELETE",to_id:"table:wrk_orders",dep_type:"writes" },
  { from_id:"api:wrk/technicians:GET",to_id:"table:wrk_technicians",dep_type:"reads" },
  { from_id:"api:wrk/technicians:POST",to_id:"table:wrk_technicians",dep_type:"writes" },
  { from_id:"api:wrk/inspections:GET",to_id:"table:wrk_inspections",dep_type:"reads" },
  { from_id:"api:wrk/inspections:POST",to_id:"table:wrk_inspections",dep_type:"writes" },
  { from_id:"api:wrk/apk-reminders:GET",to_id:"table:wrk_apk_reminders",dep_type:"reads" },
  { from_id:"api:wrk/apk-reminders:POST",to_id:"table:wrk_apk_reminders",dep_type:"writes" },
  { from_id:"api:wrk/approvals:GET",to_id:"table:wrk_approvals",dep_type:"reads" },
  { from_id:"api:wrk/approvals:POST",to_id:"table:wrk_approvals",dep_type:"writes" },
  { from_id:"api:wrk/rates:GET",to_id:"table:wrk_labour_rates",dep_type:"reads" },
  { from_id:"api:wrk/rates:POST",to_id:"table:wrk_labour_rates",dep_type:"writes" },
  { from_id:"api:wrk/packages:GET",to_id:"table:wrk_service_packages",dep_type:"reads" },
  { from_id:"api:wrk/packages:POST",to_id:"table:wrk_service_packages",dep_type:"writes" },
  { from_id:"api:wrk/efficiency:GET",to_id:"table:wrk_efficiency_metrics",dep_type:"reads" },
  { from_id:"api:wrk/efficiency:POST",to_id:"table:wrk_efficiency_metrics",dep_type:"writes" },
  { from_id:"api:wrk/planning:GET",to_id:"table:wrk_planning_slots",dep_type:"reads" },
  { from_id:"api:wrk/planning:POST",to_id:"table:wrk_planning_slots",dep_type:"writes" },
  { from_id:"api:wrk/dashboard:GET",to_id:"table:wrk_orders",dep_type:"reads" },
  { from_id:"api:wrk/dashboard:GET",to_id:"table:wrk_planning_slots",dep_type:"reads" },
  { from_id:"api:wrk/briefing:GET",to_id:"table:wrk_planning_slots",dep_type:"reads" },
  { from_id:"api:wrk/briefing:GET",to_id:"table:wrk_technicians",dep_type:"reads" },
  { from_id:"api:wrk/recommendations:GET",to_id:"table:wrk_orders",dep_type:"reads" },
  // Workshop Intelligence — cross-module integration dependencies
  { from_id:"api:wrk/orders:PATCH",to_id:"table:ast_vehicles",dep_type:"writes",description:"AST write-back: mileage + last_service_date on WO completion" },
  { from_id:"api:wrk/orders:PATCH",to_id:"table:sal_warranty_claims",dep_type:"writes",description:"SAL: auto-create warranty claim on warranty_repair completion" },
  { from_id:"api:wrk/orders:PATCH",to_id:"table:crm_activities",dep_type:"writes",description:"CRM: workshop_visit activity on WO completion" },
  { from_id:"api:wrk/plate-lookup:POST",to_id:"table:ast_vehicles",dep_type:"reads",description:"DIE: RDW plate lookup + asset matching" },
  // Workshop Intelligence — Autoflex DMS integration dependencies
  { from_id:"screen:WK013",to_id:"api:wrk/autoflex:GET",dep_type:"calls" },
  { from_id:"screen:WK013",to_id:"api:wrk/autoflex:POST",dep_type:"calls" },
  { from_id:"screen:WK013",to_id:"api:wrk/autoflex/logs:GET",dep_type:"calls" },
  { from_id:"api:wrk/autoflex:GET",to_id:"table:wrk_autoflex_config",dep_type:"reads" },
  { from_id:"api:wrk/autoflex:POST",to_id:"table:wrk_autoflex_config",dep_type:"reads" },
  { from_id:"api:wrk/autoflex:POST",to_id:"table:wrk_autoflex_sync_logs",dep_type:"writes" },
  { from_id:"api:wrk/autoflex:POST",to_id:"table:ast_assets",dep_type:"writes",description:"Autoflex vehicle sync → AST assets" },
  { from_id:"api:wrk/autoflex:POST",to_id:"table:wrk_orders",dep_type:"writes",description:"Autoflex WO sync → WRK orders" },
  { from_id:"api:wrk/autoflex:POST",to_id:"table:crm_leads",dep_type:"writes",description:"Autoflex customer sync → CRM leads" },
  { from_id:"api:wrk/autoflex/logs:GET",to_id:"table:wrk_autoflex_sync_logs",dep_type:"reads" },
  { from_id:"api:wrk/autoflex/logs:POST",to_id:"table:wrk_autoflex_sync_logs",dep_type:"writes" },
];
