import type { BopObject, BopDependency } from "@/lib/bop/types/objects";

export const OPS_SCREEN_OBJECTS: BopObject[] = [
  { object_id:"screen:OP001",type:"screen",module:"OPS",name:"Operations Cockpit",route:"/console/ops/tasks",status:"active",description:"Task management with SLA monitoring, 8-card stat strip, urgency-banded work queue" },
  { object_id:"screen:OP009",type:"screen",module:"OPS",name:"Task Grid View",route:"/console/ops/tasks/grid",status:"active",description:"Sortable grid with multi-select and bulk actions" },
  { object_id:"screen:OP010",type:"screen",module:"OPS",name:"Kanban Board",route:"/console/ops/tasks/kanban",status:"active",description:"Drag-and-drop kanban with status swim lanes and priority badges" },
  { object_id:"screen:OP011",type:"screen",module:"OPS",name:"Calendar View",route:"/console/ops/tasks/calendar",status:"active",description:"Monthly calendar grid with due-date task chips and day-click navigation" },
  { object_id:"screen:OP002",type:"screen",module:"OPS",name:"Strategy Cockpit",route:"/console/ops/goals",status:"active",description:"Goals & OKRs — hierarchical goal tree, KR tracking, entity-scoped periods" },
  { object_id:"screen:OP002-detail",type:"screen",module:"OPS",name:"Goal Detail",route:"/console/ops/goals/[id]",status:"active",description:"Goal header, KR value editor, check-in form, close-out, sparklines, metric chips" },
  { object_id:"screen:OP012",type:"screen",module:"OPS",name:"Exec Dashboard",route:"/console/ops/goals/dashboard",status:"active",description:"Vision banner, progress rings, entity lanes, at-risk panel, KPI strip, trend charts" },
  { object_id:"screen:OP013",type:"screen",module:"OPS",name:"Task Analytics",route:"/console/ops/tasks/analytics",status:"active",description:"Completion trends, SLA compliance gauge, workload by assignee/dept, priority/status distribution" },
  { object_id:"screen:OP015",type:"screen",module:"OPS",name:"Entity Scorecard",route:"/console/ops/goals/scorecard",status:"active",description:"Per-entity radar chart, KPI grid, goal health donut, period comparison table" },
  { object_id:"screen:OP014",type:"screen",module:"OPS",name:"Task Timeline",route:"/console/ops/tasks/timeline",status:"active",description:"Gantt-style timeline with dependency arrows, priority stripes, today marker" },
  { object_id:"screen:OP016",type:"screen",module:"OPS",name:"Historical Ledger",route:"/console/ops/goals/ledger",status:"active",description:"Frozen period snapshots for historical goal comparison" },
  { object_id:"screen:OP018",type:"screen",module:"OPS",name:"Fair Scout",route:"/console/ops/field-intel",status:"active",description:"Mobile-first trade fair capture tool — photo, classify, score, sync to Google Drive" },
];

export const OPS_API_OBJECTS: BopObject[] = [
  { object_id:"api:ops/tasks:GET",type:"api",module:"OPS",name:"GET Tasks (list + cockpit-summary)",route:"/api/bop/ops/tasks",status:"active" },
  { object_id:"api:ops/tasks:POST",type:"api",module:"OPS",name:"Task Actions (create, transition, assign, bulk_update, snooze)",route:"/api/bop/ops/tasks",status:"active" },
  { object_id:"api:ops/tasks:PATCH",type:"api",module:"OPS",name:"Update Task",route:"/api/bop/ops/tasks",status:"active" },
  { object_id:"api:ops/tasks:DELETE",type:"api",module:"OPS",name:"Soft-Delete Task",route:"/api/bop/ops/tasks",status:"active" },
  { object_id:"api:ops/tasks/events:GET",type:"api",module:"OPS",name:"GET Task Events",route:"/api/bop/ops/tasks/events",status:"active" },
  { object_id:"api:ops/tasks/comments:GET",type:"api",module:"OPS",name:"GET Task Comments",route:"/api/bop/ops/tasks/comments",status:"active" },
  { object_id:"api:ops/tasks/comments:POST",type:"api",module:"OPS",name:"Add Task Comment",route:"/api/bop/ops/tasks/comments",status:"active" },
  { object_id:"api:ops/tasks/deps:GET",type:"api",module:"OPS",name:"GET Task Dependencies",route:"/api/bop/ops/tasks/deps",status:"active" },
  { object_id:"api:ops/tasks/deps:POST",type:"api",module:"OPS",name:"Add Task Dependency",route:"/api/bop/ops/tasks/deps",status:"active" },
  { object_id:"api:ops/tasks/deps:DELETE",type:"api",module:"OPS",name:"Remove Task Dependency",route:"/api/bop/ops/tasks/deps",status:"active" },
  { object_id:"api:ops/goals:GET",type:"api",module:"OPS",name:"GET Goals (tree, dashboard-summary, exec-summary, metrics-catalog)",route:"/api/bop/ops/goals",status:"active" },
  { object_id:"api:ops/goals:POST",type:"api",module:"OPS",name:"Goal Actions (create, create_kr, update_kr_value, checkin, close_out, compute_kr, rollup)",route:"/api/bop/ops/goals",status:"active" },
  { object_id:"api:ops/goals:PATCH",type:"api",module:"OPS",name:"Update Goal",route:"/api/bop/ops/goals",status:"active" },
  { object_id:"api:ops/goals:DELETE",type:"api",module:"OPS",name:"Soft-Delete Goal",route:"/api/bop/ops/goals",status:"active" },
  { object_id:"api:ops/tasks/analytics:GET",type:"api",module:"OPS",name:"GET Task Analytics",route:"/api/bop/ops/tasks/analytics",status:"active" },
  { object_id:"api:ops/telegram-webhook:POST",type:"api",module:"OPS",name:"Telegram Inline Action Webhook",route:"/api/bop/ops/telegram-webhook",status:"active" },
  { object_id:"api:ops/fair-scout:GET",type:"api",module:"OPS",name:"GET Fair Scout observations",route:"/api/bop/ops/fair-scout",status:"active" },
  { object_id:"api:ops/fair-scout:POST",type:"api",module:"OPS",name:"Fair Scout sync/bootstrap/delete",route:"/api/bop/ops/fair-scout",status:"active" },
];

export const OPS_TABLE_OBJECTS: BopObject[] = [
  { object_id:"table:op_tasks",type:"table",module:"OPS",name:"op_tasks",status:"active",description:"Operational tasks — 7-status, priority 1-4, SLA, polymorphic refs, checklist, tenant-scoped" },
  { object_id:"table:op_task_dependencies",type:"table",module:"OPS",name:"op_task_dependencies",status:"active",description:"Task blocker graph — self-ref prevention, cycle detection via RPC" },
  { object_id:"table:op_task_events",type:"table",module:"OPS",name:"op_task_events",status:"active",description:"Task audit trail — 12 event types, actor + payload" },
  { object_id:"table:op_task_comments",type:"table",module:"OPS",name:"op_task_comments",status:"active",description:"Threaded task comments with soft-delete" },
  { object_id:"table:op_task_attachments",type:"table",module:"OPS",name:"op_task_attachments",status:"active",description:"Task file attachments — Supabase Storage op-tasks/{task_id}/" },
  { object_id:"table:op_goals",type:"table",module:"OPS",name:"op_goals",status:"active",description:"Hierarchical goals — 3-level, entity-scoped, period-bound, health tracking" },
  { object_id:"table:op_goal_key_results",type:"table",module:"OPS",name:"op_goal_key_results",status:"active",description:"Key results — 5 metric types, weighted, direction-aware progress" },
  { object_id:"table:op_goal_kr_snapshots",type:"table",module:"OPS",name:"op_goal_kr_snapshots",status:"active",description:"Daily KR snapshots for sparklines and trend analysis" },
  { object_id:"table:op_goal_checkins",type:"table",module:"OPS",name:"op_goal_checkins",status:"active",description:"Goal check-ins — confidence 1-5, note, blockers" },
  { object_id:"table:op_goal_metrics_catalog",type:"table",module:"OPS",name:"op_goal_metrics_catalog",status:"active",description:"System-wide metric codes — 9 query keys for auto-compute KRs (vans_sold, revenue, margin, etc.)" },
  { object_id:"table:op_goal_period_ledger",type:"table",module:"OPS",name:"op_goal_period_ledger",status:"active",description:"Frozen period snapshots — goal + KR state at close-out, historical comparison" },
];

export const OPS_DEPENDENCIES: BopDependency[] = [
  { from_id:"screen:OP001",to_id:"api:ops/tasks:GET",dep_type:"calls" },
  { from_id:"screen:OP001",to_id:"api:ops/tasks:POST",dep_type:"calls" },
  { from_id:"screen:OP001",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"screen:OP010",to_id:"api:ops/tasks:GET",dep_type:"calls" },
  { from_id:"screen:OP010",to_id:"api:ops/tasks:PATCH",dep_type:"calls" },
  { from_id:"screen:OP011",to_id:"api:ops/tasks:GET",dep_type:"calls" },
  { from_id:"api:ops/tasks:GET",to_id:"table:op_tasks",dep_type:"reads" },
  { from_id:"api:ops/tasks:POST",to_id:"table:op_tasks",dep_type:"writes" },
  { from_id:"api:ops/tasks:POST",to_id:"table:op_task_events",dep_type:"writes" },
  { from_id:"api:ops/tasks:PATCH",to_id:"table:op_tasks",dep_type:"writes" },
  { from_id:"api:ops/tasks:DELETE",to_id:"table:op_tasks",dep_type:"writes" },
  { from_id:"api:ops/tasks/events:GET",to_id:"table:op_task_events",dep_type:"reads" },
  { from_id:"api:ops/tasks/comments:GET",to_id:"table:op_task_comments",dep_type:"reads" },
  { from_id:"api:ops/tasks/comments:POST",to_id:"table:op_task_comments",dep_type:"writes" },
  { from_id:"api:ops/tasks/comments:POST",to_id:"table:op_task_events",dep_type:"writes" },
  { from_id:"api:ops/tasks/deps:GET",to_id:"table:op_task_dependencies",dep_type:"reads" },
  { from_id:"api:ops/tasks/deps:POST",to_id:"table:op_task_dependencies",dep_type:"writes" },
  { from_id:"api:ops/tasks/deps:DELETE",to_id:"table:op_task_dependencies",dep_type:"writes" },
  { from_id:"screen:OP002",to_id:"api:ops/goals:GET",dep_type:"calls" },
  { from_id:"screen:OP002",to_id:"api:ops/goals:POST",dep_type:"calls" },
  { from_id:"screen:OP002",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"screen:OP002-detail",to_id:"api:ops/goals:GET",dep_type:"calls" },
  { from_id:"screen:OP002-detail",to_id:"api:ops/goals:POST",dep_type:"calls" },
  { from_id:"screen:OP002-detail",to_id:"api:ops/goals:PATCH",dep_type:"calls" },
  { from_id:"api:ops/goals:GET",to_id:"table:op_goals",dep_type:"reads" },
  { from_id:"api:ops/goals:GET",to_id:"table:op_goal_key_results",dep_type:"reads" },
  { from_id:"api:ops/goals:GET",to_id:"table:op_goal_checkins",dep_type:"reads" },
  { from_id:"api:ops/goals:POST",to_id:"table:op_goals",dep_type:"writes" },
  { from_id:"api:ops/goals:POST",to_id:"table:op_goal_key_results",dep_type:"writes" },
  { from_id:"api:ops/goals:POST",to_id:"table:op_goal_checkins",dep_type:"writes" },
  { from_id:"api:ops/goals:PATCH",to_id:"table:op_goals",dep_type:"writes" },
  { from_id:"api:ops/goals:DELETE",to_id:"table:op_goals",dep_type:"writes" },
  { from_id:"screen:OP012",to_id:"api:ops/goals:GET",dep_type:"calls" },
  { from_id:"screen:OP012",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"api:ops/goals:GET",to_id:"table:op_goal_kr_snapshots",dep_type:"reads" },
  { from_id:"api:ops/goals:GET",to_id:"table:op_goal_metrics_catalog",dep_type:"reads" },
  { from_id:"api:ops/goals:POST",to_id:"table:op_goal_kr_snapshots",dep_type:"writes" },
  { from_id:"screen:OP013",to_id:"api:ops/tasks/analytics:GET",dep_type:"calls" },
  { from_id:"screen:OP014",to_id:"api:ops/tasks:GET",dep_type:"calls" },
  { from_id:"screen:OP014",to_id:"api:ops/tasks/deps:GET",dep_type:"calls" },
  { from_id:"api:ops/tasks/analytics:GET",to_id:"table:op_tasks",dep_type:"reads" },
  { from_id:"api:ops/tasks/analytics:GET",to_id:"table:op_task_events",dep_type:"reads" },
  { from_id:"api:ops/telegram-webhook:POST",to_id:"table:op_tasks",dep_type:"writes" },
  { from_id:"api:ops/goals:POST",to_id:"table:op_goal_period_ledger",dep_type:"writes" },
  { from_id:"api:ops/goals:GET",to_id:"table:op_goal_period_ledger",dep_type:"reads" },
  { from_id:"screen:OP012",to_id:"api:ops/goals:POST",dep_type:"calls" },
  { from_id:"screen:OP015",to_id:"api:ops/goals:GET",dep_type:"calls" },
  { from_id:"screen:OP015",to_id:"component:ScreenHeader",dep_type:"renders" },
  { from_id:"screen:OP018",to_id:"api:ops/fair-scout:GET",dep_type:"calls" },
  { from_id:"screen:OP018",to_id:"api:ops/fair-scout:POST",dep_type:"calls" },
  { from_id:"screen:OP018",to_id:"component:ScreenHeader",dep_type:"renders" },
];
