-- Auto-generated seed data for bop_table_docs
-- Generated from table metadata analysis
-- 509 table descriptions

INSERT INTO bop_table_docs (schema_name, table_name, column_name, description, tags, module, updated_by, updated_at)
VALUES
  ('public', 'activity_log', NULL, 'Visitor activity events on the website (page views, clicks, interactions). Tracks session, device, geo, and referrer data.', '{audit,multi-tenant}', 'ANL', 'system-seed', now()),
  ('public', 'activity_log2', NULL, 'Aggregated visitor sessions with UTM tracking, traffic channel attribution, and bounce detection.', '{timestamped,audit,multi-tenant}', 'ANL', 'system-seed', now()),
  ('public', 'activity_log2_delete_parameters', NULL, 'IP/city-based rules for purging bot or spam entries from activity_log2.', '{audit,config}', 'ANL', 'system-seed', now()),
  ('public', 'adm_change_log', NULL, 'Audit trail for admin screen field changes (old/new values, actor, source).', '{audit}', 'ADM', 'system-seed', now()),
  ('public', 'adm_dependencies', NULL, 'Dependency graph between admin objects (auto-detected or manual).', '{}', 'ADM', 'system-seed', now()),
  ('public', 'adm_documentation', NULL, 'Markdown documentation entries attached to admin objects (screens, modules, APIs).', '{}', 'ADM', 'system-seed', now()),
  ('public', 'adm_objects', NULL, 'Registry of all admin/BOP objects (screens, APIs, tables) with lifecycle and protection metadata.', '{}', 'ADM', 'system-seed', now()),
  ('public', 'adm_screen_meta', NULL, 'Extended metadata for admin screens: API routes, DB tables, and notes.', '{}', 'ADM', 'system-seed', now()),
  ('public', 'admin_notifications', NULL, 'In-app notification inbox for admin users.', '{multi-tenant}', 'ADM', 'system-seed', now()),
  ('public', 'admin_quote', NULL, 'Legacy quotation system for vehicles with pricing, VAT, trade-in, and customer details.', '{timestamped,multi-tenant}', 'ADM', 'system-seed', now()),
  ('public', 'admin_quote_log', NULL, 'Event log for quote lifecycle changes (sent, viewed, accepted).', '{audit}', 'ADM', 'system-seed', now()),
  ('public', 'admin_roles', NULL, 'User-to-role assignments with timezone and UI preferences.', '{security}', 'ADM', 'system-seed', now()),
  ('public', 'admin_screens', NULL, 'Legacy screen registry for admin console navigation.', '{}', 'ADM', 'system-seed', now()),
  ('public', 'admin_user_activity', NULL, 'Tracks which admin users accessed which screens.', '{multi-tenant}', 'ADM', 'system-seed', now()),
  ('public', 'afleverbon', NULL, 'Vehicle handover/delivery documents with digital signature capture and checklist.', '{}', 'SAL', 'system-seed', now()),
  ('public', 'agent_api_keys', NULL, 'API keys for external agent integrations with scope and rate limiting.', '{integration}', 'AGT', 'system-seed', now()),
  ('public', 'agent_competitor_listings', NULL, 'Scraped competitor vehicle listings from external platforms.', '{}', 'AGT', 'system-seed', now()),
  ('public', 'agent_jobs', NULL, 'Scheduled agent automation jobs (scraping, publishing) with cron schedules.', '{timestamped}', 'AGT', 'system-seed', now()),
  ('public', 'agent_messages', NULL, 'Inbound messages from marketplace platforms (buyer inquiries, offers).', '{}', 'AGT', 'system-seed', now()),
  ('public', 'agent_platforms', NULL, 'Marketplace platform credentials and connection configuration.', '{timestamped}', 'AGT', 'system-seed', now()),
  ('public', 'agent_publish_queue', NULL, 'Queue for publishing listings to external platforms with approval workflow.', '{}', 'AGT', 'system-seed', now()),
  ('public', 'agent_run_log', NULL, 'AI agent execution logs with token usage and cost tracking.', '{audit}', 'AGT', 'system-seed', now()),
  ('public', 'agent_run_logs', NULL, 'Detailed run logs for agent jobs with item processing stats.', '{audit}', 'AGT', 'system-seed', now()),
  ('public', 'aim_action_log', NULL, 'Audit log for AI Management module actions.', '{audit}', 'AIM', 'system-seed', now()),
  ('public', 'aim_actions', NULL, 'Registered AI actions with parameter schemas and endpoints.', '{}', 'AIM', 'system-seed', now()),
  ('public', 'anl_alert_rules', NULL, 'Configurable alert rules with thresholds and notification settings.', '{config,multi-tenant}', 'ANL', 'system-seed', now()),
  ('public', 'anl_daily_snapshots', NULL, 'Daily aggregated metric snapshots per tenant.', '{analytics,multi-tenant}', 'ANL', 'system-seed', now()),
  ('public', 'app_locks', NULL, 'Application-level advisory locks for preventing concurrent operations.', '{}', 'SYS', 'system-seed', now()),
  ('public', 'appointments', NULL, 'Legacy appointment bookings for vehicle viewings/test drives.', '{crm,timestamped,multi-tenant}', 'CRM', 'system-seed', now()),
  ('public', 'ast_assets', NULL, 'Vehicle/equipment asset register with pricing, location, and lifecycle status.', '{timestamped,soft-delete,multi-tenant}', 'AST', 'system-seed', now()),
  ('public', 'ast_cost_items', NULL, 'Cost breakdown items (repairs, transport, preparation) for assets.', '{}', 'AST', 'system-seed', now()),
  ('public', 'ast_lifecycle_events', NULL, 'Asset status transition history (acquired → prepared → listed → sold).', '{audit}', 'AST', 'system-seed', now()),
  ('public', 'auc_auctions', NULL, 'Auction events with schedule, location, and status.', '{multi-tenant}', 'AUC', 'system-seed', now()),
  ('public', 'auc_bids', NULL, 'Bids placed on auction lots.', '{}', 'AUC', 'system-seed', now()),
  ('public', 'auc_lots', NULL, 'Auction lot assignments linking assets to auctions with reserve prices.', '{}', 'AUC', 'system-seed', now()),
  ('public', 'banner_click_events', NULL, 'Banner click events.', '{audit}', 'BNR', 'system-seed', now()),
  ('public', 'banner_terms_log', NULL, 'Banner terms log.', '{audit}', 'BNR', 'system-seed', now()),
  ('public', 'bop_access_log', NULL, 'Audit/event log for BOP access operations.', '{audit,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_ai_agents', NULL, 'Bop ai agents.', '{timestamped}', 'BOP', 'system-seed', now()),
  ('public', 'bop_appointments', NULL, 'Bop appointments. multi-tenant. wide table (33 columns).', '{crm,timestamped,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_auction_bids', NULL, 'Bop auction bids.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_auction_lots', NULL, 'Bop auction lots.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_auction_results', NULL, 'Bop auction results.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_auctions', NULL, 'Bop auctions. multi-tenant.', '{timestamped,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_body_type_labels', NULL, 'Bop body type labels.', '{i18n}', 'BOP', 'system-seed', now()),
  ('public', 'bop_body_types', NULL, 'Bop body types.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_brands', NULL, 'Bop brands. multi-tenant.', '{multi-tenant,master-data}', 'BOP', 'system-seed', now()),
  ('public', 'bop_business_events', NULL, 'Audit/event log for BOP businesss operations.', '{audit,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_cases', NULL, 'Bop cases. multi-tenant.', '{timestamped,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_change_log', NULL, 'Audit/event log for BOP change operations.', '{audit}', 'BOP', 'system-seed', now()),
  ('public', 'bop_channel_domains', NULL, 'Bop channel domains.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_comm_automation', NULL, 'Communication engine automation — multi-locale email/notification system.', '{email,timestamped,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_comm_branding', NULL, 'Communication engine branding — multi-locale email/notification system.', '{email,timestamped,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_comm_compile_cache', NULL, 'Communication engine compile cache — multi-locale email/notification system.', '{email,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_comm_history', NULL, 'Audit/event log for BOP comm operations.', '{email,audit,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_comm_master_style', NULL, 'Communication engine master style — multi-locale email/notification system.', '{email,timestamped,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_comm_template', NULL, 'Communication engine template — multi-locale email/notification system.', '{email,timestamped,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_conversion_exports', NULL, 'Bop conversion exports. multi-tenant.', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_conversion_rules', NULL, 'Bop conversion rules.', '{config}', 'BOP', 'system-seed', now()),
  ('public', 'bop_copy_control', NULL, 'Bop copy control.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_counter', NULL, 'Bop counter.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_customer_approvals', NULL, 'Bop customer approvals. multi-tenant.', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_db_query_log', NULL, 'Audit/event log for BOP db query operations.', '{audit,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_dependencies', NULL, 'Bop dependencies.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_doc_flow', NULL, 'Bop doc flow. multi-tenant.', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_document_access', NULL, 'Bop document access. multi-tenant.', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_documentation', NULL, 'Bop documentation.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_email_base_layout', NULL, 'Bop email base layout.', '{email}', 'BOP', 'system-seed', now()),
  ('public', 'bop_email_brand', NULL, 'Bop email brand. multi-tenant.', '{email,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_email_log', NULL, 'Audit/event log for BOP email operations.', '{email,audit,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_email_template', NULL, 'Bop email template. multi-tenant.', '{email,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_email_template_map', NULL, 'Bop email template map.', '{email}', 'BOP', 'system-seed', now()),
  ('public', 'bop_events', NULL, 'Audit/event log for BOP events operations.', '{audit}', 'BOP', 'system-seed', now()),
  ('public', 'bop_feature_catalog', NULL, 'Audit/event log for BOP feature catalog operations.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_features', NULL, 'Bop features.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_handover_transitions', NULL, 'Allowed status transitions for handover objects (state machine rules).', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_invoice_transitions', NULL, 'Allowed status transitions for invoice objects (state machine rules).', '{transaction,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_analytics', NULL, 'Listing analytics data — extends the main bop_listings table.', '{analytics}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_attrs', NULL, 'Listing attrs data — extends the main bop_listings table.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_categories', NULL, 'Listing categories data — extends the main bop_listings table.', '{master-data}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_category_labels', NULL, 'Listing category labels data — extends the main bop_listings table.', '{i18n}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_channels', NULL, 'Listing channels data — extends the main bop_listings table.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_content', NULL, 'Listing content data — extends the main bop_listings table.', '{i18n}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_delivery', NULL, 'Listing delivery data — extends the main bop_listings table.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_docs', NULL, 'Listing docs data — extends the main bop_listings table.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_features', NULL, 'Listing features data — extends the main bop_listings table.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_layouts', NULL, 'Listing layouts data — extends the main bop_listings table.', '{timestamped,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_media', NULL, 'Listing media data — extends the main bop_listings table.', '{media}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_pricing', NULL, 'Listing pricing data — extends the main bop_listings table.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_specs_camper', NULL, 'Listing specs camper data — extends the main bop_listings table.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_specs_car', NULL, 'Listing specs car data — extends the main bop_listings table.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_specs_machinery', NULL, 'Listing specs machinery data — extends the main bop_listings table.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_specs_trailer', NULL, 'Listing specs trailer data — extends the main bop_listings table.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_specs_truck', NULL, 'Listing specs truck data — extends the main bop_listings table.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listing_specs_van', NULL, 'Listing specs van data — extends the main bop_listings table.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_listings', NULL, 'Bop listings. multi-tenant. wide table (24 columns).', '{timestamped,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_mail_identity', NULL, 'Bop mail identity. multi-tenant.', '{email,timestamped,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_mkt_assets', NULL, 'Marketing automation assets — AI content generation and publishing.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_mkt_brand_profiles', NULL, 'Marketing automation brand profiles — AI content generation and publishing.', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_mkt_campaigns', NULL, 'Marketing automation campaigns — AI content generation and publishing.', '{timestamped,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_mkt_channels', NULL, 'Marketing automation channels — AI content generation and publishing.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_mkt_generations', NULL, 'Marketing automation generations — AI content generation and publishing.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_mkt_outputs', NULL, 'Marketing automation outputs — AI content generation and publishing.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_mkt_publications', NULL, 'Marketing automation publications — AI content generation and publishing.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_models', NULL, 'Bop models.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_modules', NULL, 'Bop modules.', '{timestamped}', 'BOP', 'system-seed', now()),
  ('public', 'bop_object_locks', NULL, 'Bop object locks.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_objects', NULL, 'Bop objects.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_own_domains', NULL, 'Bop own domains.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_permissions', NULL, 'Bop permissions.', '{security}', 'BOP', 'system-seed', now()),
  ('public', 'bop_plan_features', NULL, 'Bop plan features.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_protected_tables', NULL, 'Bop protected tables.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_ref_counter', NULL, 'Bop ref counter.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_role_permissions', NULL, 'Bop role permissions.', '{security}', 'BOP', 'system-seed', now()),
  ('public', 'bop_role_screens', NULL, 'Bop role screens.', '{security}', 'BOP', 'system-seed', now()),
  ('public', 'bop_roles', NULL, 'Bop roles.', '{timestamped,security}', 'BOP', 'system-seed', now()),
  ('public', 'bop_screen_meta', NULL, 'Bop screen meta.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_screen_roles', NULL, 'Bop screen roles.', '{security}', 'BOP', 'system-seed', now()),
  ('public', 'bop_screens', NULL, 'Bop screens. wide table (25 columns).', '{timestamped}', 'BOP', 'system-seed', now()),
  ('public', 'bop_sessions', NULL, 'Bop sessions. multi-tenant.', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_settings', NULL, 'Configuration settings for BOP settings.', '{config}', 'BOP', 'system-seed', now()),
  ('public', 'bop_shortlink_clicks', NULL, 'Bop shortlink clicks. multi-tenant.', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_shortlink_prefixes', NULL, 'Bop shortlink prefixes. multi-tenant.', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_status_transitions', NULL, 'Allowed status transitions for status objects (state machine rules).', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_studio_export_targets', NULL, 'Photo studio export targets — part of the AI-powered image processing pipeline.', '{media}', 'BOP', 'system-seed', now()),
  ('public', 'bop_studio_images', NULL, 'Photo studio images — part of the AI-powered image processing pipeline.', '{media}', 'BOP', 'system-seed', now()),
  ('public', 'bop_studio_jobs', NULL, 'Photo studio jobs — part of the AI-powered image processing pipeline.', '{media}', 'BOP', 'system-seed', now()),
  ('public', 'bop_studio_preset_backgrounds', NULL, 'Photo studio preset backgrounds — part of the AI-powered image processing pipeline.', '{media}', 'BOP', 'system-seed', now()),
  ('public', 'bop_studio_presets', NULL, 'Photo studio presets — part of the AI-powered image processing pipeline.', '{media}', 'BOP', 'system-seed', now()),
  ('public', 'bop_studio_sessions', NULL, 'Photo studio sessions — part of the AI-powered image processing pipeline.', '{media,timestamped}', 'BOP', 'system-seed', now()),
  ('public', 'bop_studio_steps', NULL, 'Photo studio steps — part of the AI-powered image processing pipeline.', '{media}', 'BOP', 'system-seed', now()),
  ('public', 'bop_subscription_plans', NULL, 'Bop subscription plans.', '{timestamped}', 'BOP', 'system-seed', now()),
  ('public', 'bop_subscriptions', NULL, 'Bop subscriptions.', '{timestamped}', 'BOP', 'system-seed', now()),
  ('public', 'bop_tenant_status', NULL, 'Bop tenant status. multi-tenant.', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_tenants', NULL, 'Bop tenants. multi-tenant. wide table (40 columns).', '{timestamped,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_translations', NULL, 'Bop translations.', '{i18n}', 'BOP', 'system-seed', now()),
  ('public', 'bop_user_activity', NULL, 'User activity — per-user settings and profile data.', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_user_appearance', NULL, 'User appearance — per-user settings and profile data.', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_user_events', NULL, 'Audit/event log for BOP users operations.', '{audit,multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'bop_user_permissions', NULL, 'User permissions — per-user settings and profile data.', '{security}', 'BOP', 'system-seed', now()),
  ('public', 'bop_user_prefs', NULL, 'User prefs — per-user settings and profile data.', '{}', 'BOP', 'system-seed', now()),
  ('public', 'bop_user_profiles', NULL, 'User profiles — per-user settings and profile data.', '{timestamped}', 'BOP', 'system-seed', now()),
  ('public', 'bop_user_roles', NULL, 'User roles — per-user settings and profile data.', '{security}', 'BOP', 'system-seed', now()),
  ('public', 'bop_user_tenants', NULL, 'User tenants — per-user settings and profile data.', '{multi-tenant}', 'BOP', 'system-seed', now()),
  ('public', 'brands', NULL, 'Brands. multi-tenant.', '{timestamped,multi-tenant,master-data}', 'MDM', 'system-seed', now()),
  ('public', 'btw_customers', NULL, 'VAT/tax customers — Dutch BTW administration and quarterly reporting.', '{timestamped}', 'BTW', 'system-seed', now()),
  ('public', 'btw_expenses', NULL, 'VAT/tax expenses — Dutch BTW administration and quarterly reporting.', '{timestamped,multi-tenant}', 'BTW', 'system-seed', now()),
  ('public', 'btw_invoice_items', NULL, 'VAT/tax invoice items — Dutch BTW administration and quarterly reporting.', '{transaction,multi-tenant}', 'BTW', 'system-seed', now()),
  ('public', 'btw_invoices', NULL, 'VAT/tax invoices — Dutch BTW administration and quarterly reporting.', '{timestamped,transaction,multi-tenant}', 'BTW', 'system-seed', now()),
  ('public', 'btw_quarterly_reports', NULL, 'VAT/tax quarterly reports — Dutch BTW administration and quarterly reporting.', '{timestamped}', 'BTW', 'system-seed', now()),
  ('public', 'campaign_assets', NULL, 'Campaign assets.', '{}', 'MKT', 'system-seed', now()),
  ('public', 'campaign_reference_images', NULL, 'Campaign reference images.', '{media}', 'MKT', 'system-seed', now()),
  ('public', 'campaigns', NULL, 'Campaigns. wide table (23 columns).', '{timestamped}', 'MKT', 'system-seed', now()),
  ('public', 'categories', NULL, 'Categories.', '{master-data}', 'SYS', 'system-seed', now()),
  ('public', 'category_search_terms', NULL, 'Category search terms.', '{search}', 'SYS', 'system-seed', now()),
  ('public', 'ci_ad_spend_daily', NULL, 'Commerce intelligence ad spend daily.', '{analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_attention_item', NULL, 'Commerce intelligence attention item.', '{analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_benchmark', NULL, 'Commerce intelligence benchmark.', '{analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_consent_log', NULL, 'Commerce intelligence consent log.', '{audit,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_daily_campaign', NULL, 'Daily aggregated campaign metrics for commerce intelligence dashboards.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_daily_cart', NULL, 'Daily aggregated cart metrics for commerce intelligence dashboards.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_daily_category', NULL, 'Daily aggregated category metrics for commerce intelligence dashboards.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_daily_checkout', NULL, 'Daily aggregated checkout metrics for commerce intelligence dashboards.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_daily_customer', NULL, 'Daily aggregated customer metrics for commerce intelligence dashboards.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_daily_fulfilment', NULL, 'Daily aggregated fulfilment metrics for commerce intelligence dashboards.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_daily_funnel', NULL, 'Daily aggregated funnel metrics for commerce intelligence dashboards.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_daily_inventory', NULL, 'Daily aggregated inventory metrics for commerce intelligence dashboards.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_daily_product', NULL, 'Daily aggregated product metrics for commerce intelligence dashboards.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_daily_sales', NULL, 'Daily aggregated sales metrics for commerce intelligence dashboards.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_daily_search', NULL, 'Daily aggregated search metrics for commerce intelligence dashboards.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_daily_traffic', NULL, 'Daily aggregated traffic metrics for commerce intelligence dashboards.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_data_health', NULL, 'Commerce intelligence data health.', '{analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_events_2026_05', NULL, 'Partitioned event store for commerce intelligence — 05 partition.', '{audit,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_events_2026_06', NULL, 'Partitioned event store for commerce intelligence — 06 partition.', '{audit,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_events_2026_07', NULL, 'Partitioned event store for commerce intelligence — 07 partition.', '{audit,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_events_2026_08', NULL, 'Partitioned event store for commerce intelligence — 08 partition.', '{audit,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_events_2026_09', NULL, 'Partitioned event store for commerce intelligence — 09 partition.', '{audit,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_events_2026_10', NULL, 'Partitioned event store for commerce intelligence — 10 partition.', '{audit,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_events_2026_11', NULL, 'Partitioned event store for commerce intelligence — 11 partition.', '{audit,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_identity_link', NULL, 'Commerce intelligence identity link.', '{analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_job_run', NULL, 'Commerce intelligence job run.', '{analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_metric_def', NULL, 'Commerce intelligence metric def.', '{timestamped,analytics}', 'CI', 'system-seed', now()),
  ('public', 'ci_order_line_cost', NULL, 'Commerce intelligence order line cost.', '{timestamped,transaction,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_pseudonym_salt', NULL, 'Commerce intelligence pseudonym salt.', '{analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_restatement', NULL, 'Commerce intelligence restatement.', '{analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_score_component', NULL, 'Scoring system score component — computed health/performance scores.', '{analytics}', 'CI', 'system-seed', now()),
  ('public', 'ci_score_def', NULL, 'Scoring system score def — computed health/performance scores.', '{analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_score_result', NULL, 'Scoring system score result — computed health/performance scores.', '{analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'ci_sessions', NULL, 'Commerce intelligence sessions.', '{timestamped,analytics,multi-tenant}', 'CI', 'system-seed', now()),
  ('public', 'cloudflare_analytics', NULL, 'Cloudflare analytics. multi-tenant.', '{analytics,multi-tenant}', 'INF', 'system-seed', now()),
  ('public', 'cmp_documents', NULL, 'Cmp documents. multi-tenant.', '{multi-tenant}', 'CMP', 'system-seed', now()),
  ('public', 'cockpit_alert_log', NULL, 'Cockpit alert log.', '{audit}', 'ANL', 'system-seed', now()),
  ('public', 'cockpit_score_config', NULL, 'Cockpit score config.', '{config}', 'ANL', 'system-seed', now()),
  ('public', 'com_messages', NULL, 'Com messages.', '{}', 'COM', 'system-seed', now()),
  ('public', 'com_threads', NULL, 'Com threads. multi-tenant.', '{multi-tenant}', 'COM', 'system-seed', now()),
  ('public', 'company_settings', NULL, 'Company settings. wide table (30 columns).', '{config}', 'SYS', 'system-seed', now()),
  ('public', 'competitor_activity_log', NULL, 'Competitor activity log.', '{audit}', 'ANL', 'system-seed', now()),
  ('public', 'competitor_brands', NULL, 'Competitor brands. wide table (22 columns).', '{timestamped,master-data}', 'ANL', 'system-seed', now()),
  ('public', 'counters', NULL, 'Counters.', '{}', 'SYS', 'system-seed', now()),
  ('public', 'crm_activities', NULL, 'CRM activities — customer relationship management.', '{crm}', 'CRM', 'system-seed', now()),
  ('public', 'crm_deal_stage_history', NULL, 'CRM deal stage history — customer relationship management.', '{crm,audit}', 'CRM', 'system-seed', now()),
  ('public', 'crm_deals', NULL, 'CRM deals — customer relationship management.', '{crm,timestamped,multi-tenant}', 'CRM', 'system-seed', now()),
  ('public', 'crm_events', NULL, 'CRM events — customer relationship management.', '{crm,audit,multi-tenant}', 'CRM', 'system-seed', now()),
  ('public', 'crm_leads', NULL, 'CRM leads — customer relationship management.', '{crm,timestamped,soft-delete,multi-tenant}', 'CRM', 'system-seed', now()),
  ('public', 'customers', NULL, 'Customers.', '{timestamped,soft-delete}', 'CRM', 'system-seed', now()),
  ('public', 'dae_images', NULL, 'Data acquisition images — automated marketplace scraping and opportunity scoring.', '{media}', 'DAE', 'system-seed', now()),
  ('public', 'dae_jobs', NULL, 'Data acquisition jobs — automated marketplace scraping and opportunity scoring.', '{}', 'DAE', 'system-seed', now()),
  ('public', 'dae_listings', NULL, 'Data acquisition listings — automated marketplace scraping and opportunity scoring.', '{}', 'DAE', 'system-seed', now()),
  ('public', 'dae_metrics', NULL, 'Data acquisition metrics — automated marketplace scraping and opportunity scoring.', '{analytics}', 'DAE', 'system-seed', now()),
  ('public', 'dae_opportunity_scores', NULL, 'Data acquisition opportunity scores — automated marketplace scraping and opportunity scoring.', '{}', 'DAE', 'system-seed', now()),
  ('public', 'dae_price_history', NULL, 'Data acquisition price history — automated marketplace scraping and opportunity scoring.', '{audit}', 'DAE', 'system-seed', now()),
  ('public', 'dae_raw_captures', NULL, 'Data acquisition raw captures — automated marketplace scraping and opportunity scoring.', '{}', 'DAE', 'system-seed', now()),
  ('public', 'dae_reviews', NULL, 'Data acquisition reviews — automated marketplace scraping and opportunity scoring.', '{timestamped}', 'DAE', 'system-seed', now()),
  ('public', 'dae_runs', NULL, 'Data acquisition runs — automated marketplace scraping and opportunity scoring.', '{}', 'DAE', 'system-seed', now()),
  ('public', 'dae_search_jobs', NULL, 'Data acquisition search jobs — automated marketplace scraping and opportunity scoring.', '{search}', 'DAE', 'system-seed', now()),
  ('public', 'dae_sources', NULL, 'Data acquisition sources — automated marketplace scraping and opportunity scoring.', '{timestamped}', 'DAE', 'system-seed', now()),
  ('public', 'dev_commits', NULL, 'Development commits — release and deployment management.', '{timestamped}', 'DEV', 'system-seed', now()),
  ('public', 'dev_deployments', NULL, 'Development deployments — release and deployment management.', '{}', 'DEV', 'system-seed', now()),
  ('public', 'dev_enhancements', NULL, 'Development enhancements — release and deployment management.', '{}', 'DEV', 'system-seed', now()),
  ('public', 'dev_environment_states', NULL, 'Development environment states — release and deployment management.', '{}', 'DEV', 'system-seed', now()),
  ('public', 'dev_releases', NULL, 'Development releases — release and deployment management.', '{}', 'DEV', 'system-seed', now()),
  ('public', 'dm_activity_log', NULL, 'Digital marketplace activity log — buyer-facing platform features.', '{audit,multi-tenant}', 'DM', 'system-seed', now()),
  ('public', 'dm_activity_sessions', NULL, 'Digital marketplace activity sessions — buyer-facing platform features.', '{timestamped,multi-tenant}', 'DM', 'system-seed', now()),
  ('public', 'dm_conversations', NULL, 'Digital marketplace conversations — buyer-facing platform features.', '{}', 'DM', 'system-seed', now()),
  ('public', 'dm_favorites', NULL, 'Digital marketplace favorites — buyer-facing platform features.', '{}', 'DM', 'system-seed', now()),
  ('public', 'dm_inquiries', NULL, 'Digital marketplace inquiries — buyer-facing platform features.', '{}', 'DM', 'system-seed', now()),
  ('public', 'dm_inquiry_questions', NULL, 'Digital marketplace inquiry questions — buyer-facing platform features.', '{crm}', 'DM', 'system-seed', now()),
  ('public', 'dm_messages', NULL, 'Digital marketplace messages — buyer-facing platform features.', '{}', 'DM', 'system-seed', now()),
  ('public', 'dm_profiles', NULL, 'Digital marketplace profiles — buyer-facing platform features.', '{timestamped}', 'DM', 'system-seed', now()),
  ('public', 'dm_saved_searches', NULL, 'Digital marketplace saved searches — buyer-facing platform features.', '{}', 'DM', 'system-seed', now()),
  ('public', 'dns_record', NULL, 'Dns record. multi-tenant.', '{multi-tenant}', 'INF', 'system-seed', now()),
  ('public', 'doc_files', NULL, 'Doc files. multi-tenant.', '{multi-tenant}', NULL, 'system-seed', now()),
  ('public', 'domain_registry', NULL, 'Domain registry. multi-tenant.', '{timestamped,multi-tenant}', 'INF', 'system-seed', now()),
  ('public', 'dos_dealer_applications', NULL, 'Dos dealer applications. multi-tenant.', '{timestamped,multi-tenant}', 'DOS', 'system-seed', now()),
  ('public', 'dos_valuations', NULL, 'Dos valuations. multi-tenant.', '{multi-tenant}', 'DOS', 'system-seed', now()),
  ('public', 'email_base_layout', NULL, 'Email system base layout — template and delivery management.', '{email,timestamped,multi-tenant}', 'EML', 'system-seed', now()),
  ('public', 'email_link_clicks', NULL, 'Email system link clicks — template and delivery management.', '{email,multi-tenant}', 'EML', 'system-seed', now()),
  ('public', 'email_log', NULL, 'Email system log — template and delivery management.', '{email,audit,multi-tenant}', 'EML', 'system-seed', now()),
  ('public', 'email_template_map', NULL, 'Email system template map — template and delivery management.', '{email,timestamped,multi-tenant}', 'EML', 'system-seed', now()),
  ('public', 'environment_states', NULL, 'Environment states.', '{}', 'DEV', 'system-seed', now()),
  ('public', 'eval_jobs', NULL, 'Eval jobs.', '{}', 'ANL', 'system-seed', now()),
  ('public', 'eval_results', NULL, 'Eval results.', '{}', 'ANL', 'system-seed', now()),
  ('public', 'eval_sku_rankings', NULL, 'Eval sku rankings. wide table (21 columns).', '{}', 'ANL', 'system-seed', now()),
  ('public', 'field_definitions', NULL, 'Field definitions.', '{timestamped}', 'SYS', 'system-seed', now()),
  ('public', 'fin_invoices', NULL, 'Finance invoices — invoicing and payment tracking.', '{timestamped,transaction,multi-tenant}', 'FIN', 'system-seed', now()),
  ('public', 'fin_payments', NULL, 'Finance payments — invoicing and payment tracking.', '{transaction}', 'FIN', 'system-seed', now()),
  ('public', 'ga4_analytics', NULL, 'Ga4 analytics. multi-tenant.', '{analytics,multi-tenant}', 'ANL', 'system-seed', now()),
  ('public', 'guide_steps', NULL, 'Guide steps.', '{}', 'SYS', 'system-seed', now()),
  ('public', 'hero_images', NULL, 'Hero images. multi-tenant.', '{media,multi-tenant}', 'CMS', 'system-seed', now()),
  ('public', 'infra_config', NULL, 'Infra config. multi-tenant. wide table (28 columns).', '{timestamped,config,multi-tenant}', 'INF', 'system-seed', now()),
  ('public', 'int_flows', NULL, 'Integration hub flows — external system connections and message routing.', '{integration}', 'INT', 'system-seed', now()),
  ('public', 'int_lookup_tables', NULL, 'Integration hub lookup tables — external system connections and message routing.', '{integration}', 'INT', 'system-seed', now()),
  ('public', 'int_lookup_values', NULL, 'Integration hub lookup values — external system connections and message routing.', '{integration}', 'INT', 'system-seed', now()),
  ('public', 'int_mappings', NULL, 'Integration hub mappings — external system connections and message routing.', '{integration}', 'INT', 'system-seed', now()),
  ('public', 'int_messages', NULL, 'Integration hub messages — external system connections and message routing.', '{timestamped,integration}', 'INT', 'system-seed', now()),
  ('public', 'int_runs', NULL, 'Integration hub runs — external system connections and message routing.', '{integration}', 'INT', 'system-seed', now()),
  ('public', 'int_systems', NULL, 'Integration hub systems — external system connections and message routing.', '{timestamped,integration,multi-tenant}', 'INT', 'system-seed', now()),
  ('public', 'invoice_otp', NULL, 'Invoice otp.', '{security}', 'FIN', 'system-seed', now()),
  ('public', 'key_results', NULL, 'Key results.', '{timestamped}', 'OPS', 'system-seed', now()),
  ('public', 'lce_field_definitions', NULL, 'Lce field definitions.', '{timestamped}', 'SYS', 'system-seed', now()),
  ('public', 'lce_templates', NULL, 'Lce templates.', '{timestamped}', 'SYS', 'system-seed', now()),
  ('public', 'lead', NULL, 'Lead. multi-tenant. wide table (28 columns).', '{crm,timestamped,multi-tenant}', 'CRM', 'system-seed', now()),
  ('public', 'lead_log', NULL, 'Lead log. multi-tenant.', '{crm,audit,multi-tenant}', 'CRM', 'system-seed', now()),
  ('public', 'lead_photos', NULL, 'Lead photos.', '{media,crm}', 'CRM', 'system-seed', now()),
  ('public', 'leads', NULL, 'Leads.', '{crm,timestamped}', 'CRM', 'system-seed', now()),
  ('public', 'listing', NULL, 'Core vehicle/product listing with pricing, status, and category. Central entity for the storefront.', '{timestamped,multi-tenant}', 'LST', 'system-seed', now()),
  ('public', 'listing_analytics_snapshot', NULL, 'Listing analytics snapshot — extends the core listing entity.', '{analytics,multi-tenant}', 'LST', 'system-seed', now()),
  ('public', 'listing_content', NULL, 'Listing content — extends the core listing entity.', '{i18n}', 'LST', 'system-seed', now()),
  ('public', 'listing_det', NULL, 'Listing det — extends the core listing entity.', '{}', 'LST', 'system-seed', now()),
  ('public', 'listing_field_audit', NULL, 'Listing field audit — extends the core listing entity.', '{}', 'LST', 'system-seed', now()),
  ('public', 'listing_ingest_run', NULL, 'Listing ingest run — extends the core listing entity.', '{multi-tenant}', 'LST', 'system-seed', now()),
  ('public', 'listing_pub', NULL, 'Listing pub — extends the core listing entity.', '{timestamped}', 'LST', 'system-seed', now()),
  ('public', 'listing_subcategory', NULL, 'Listing subcategory — extends the core listing entity.', '{}', 'LST', 'system-seed', now()),
  ('public', 'listing_subscription', NULL, 'Listing subscription — extends the core listing entity.', '{multi-tenant}', 'LST', 'system-seed', now()),
  ('public', 'listing_tab_templates', NULL, 'Listing tab templates — extends the core listing entity.', '{timestamped,multi-tenant}', 'LST', 'system-seed', now()),
  ('public', 'listing_template_components', NULL, 'Listing template components — extends the core listing entity.', '{}', 'LST', 'system-seed', now()),
  ('public', 'listing_traces', NULL, 'Listing traces — extends the core listing entity.', '{timestamped,multi-tenant}', 'LST', 'system-seed', now()),
  ('public', 'listing_type_templates', NULL, 'Listing type templates — extends the core listing entity.', '{multi-tenant}', 'LST', 'system-seed', now()),
  ('public', 'log_transport_jobs', NULL, 'Log transport jobs. multi-tenant.', '{multi-tenant}', 'OPS', 'system-seed', now()),
  ('public', 'mail_identity', NULL, 'Mail identity. multi-tenant.', '{email,multi-tenant}', 'EML', 'system-seed', now()),
  ('public', 'marketplace_listings', NULL, 'Marketplace scraping listings — external platform monitoring.', '{}', 'DAE', 'system-seed', now()),
  ('public', 'marketplace_platforms', NULL, 'Marketplace scraping platforms — external platform monitoring.', '{}', 'DAE', 'system-seed', now()),
  ('public', 'marketplace_search_profiles', NULL, 'Marketplace scraping search profiles — external platform monitoring.', '{search}', 'DAE', 'system-seed', now()),
  ('public', 'marketplace_search_runs', NULL, 'Marketplace scraping search runs — external platform monitoring.', '{search}', 'DAE', 'system-seed', now()),
  ('public', 'mdm_business_partners', NULL, 'Master data business partners — shared reference data across modules.', '{timestamped,multi-tenant,master-data}', 'MDM', 'system-seed', now()),
  ('public', 'mdm_equipment', NULL, 'Master data equipment — shared reference data across modules.', '{master-data}', 'MDM', 'system-seed', now()),
  ('public', 'mdm_fuel_types', NULL, 'Master data fuel types — shared reference data across modules.', '{master-data}', 'MDM', 'system-seed', now()),
  ('public', 'mdm_partner_roles', NULL, 'Master data partner roles — shared reference data across modules.', '{security,multi-tenant,master-data}', 'MDM', 'system-seed', now()),
  ('public', 'mdm_vehicle_makes', NULL, 'Master data vehicle makes — shared reference data across modules.', '{master-data}', 'MDM', 'system-seed', now()),
  ('public', 'mdm_vehicle_models', NULL, 'Master data vehicle models — shared reference data across modules.', '{master-data}', 'MDM', 'system-seed', now()),
  ('public', 'mdm_vehicle_taxonomy', NULL, 'Master data vehicle taxonomy — shared reference data across modules.', '{multi-tenant,master-data}', 'MDM', 'system-seed', now()),
  ('public', 'mdm_vehicle_variants', NULL, 'Master data vehicle variants — shared reference data across modules.', '{master-data}', 'MDM', 'system-seed', now()),
  ('public', 'mkp_listings', NULL, 'Mkp listings. multi-tenant.', '{timestamped,multi-tenant}', 'MKP', 'system-seed', now()),
  ('public', 'mkt_campaigns', NULL, 'Mkt campaigns. multi-tenant.', '{multi-tenant}', 'MKT', 'system-seed', now()),
  ('public', 'mkt_segments', NULL, 'Mkt segments. multi-tenant.', '{multi-tenant}', 'MKT', 'system-seed', now()),
  ('public', 'objectives', NULL, 'Objectives.', '{timestamped}', 'OPS', 'system-seed', now()),
  ('public', 'op_fair_observations', NULL, 'Fair/event fair observations — trade fair observation capture.', '{multi-tenant}', 'OPS', 'system-seed', now()),
  ('public', 'op_goal_checkins', NULL, 'OKR/goals goal checkins — objective and key result tracking.', '{}', 'OPS', 'system-seed', now()),
  ('public', 'op_goal_cycles', NULL, 'OKR/goals goal cycles — objective and key result tracking.', '{multi-tenant}', 'OPS', 'system-seed', now()),
  ('public', 'op_goal_key_results', NULL, 'OKR/goals goal key results — objective and key result tracking.', '{timestamped,soft-delete,multi-tenant}', 'OPS', 'system-seed', now()),
  ('public', 'op_goal_kr_snapshots', NULL, 'OKR/goals goal kr snapshots — objective and key result tracking.', '{analytics}', 'OPS', 'system-seed', now()),
  ('public', 'op_goal_metrics_catalog', NULL, 'OKR/goals goal metrics catalog — objective and key result tracking.', '{analytics}', 'OPS', 'system-seed', now()),
  ('public', 'op_goal_period_ledger', NULL, 'OKR/goals goal period ledger — objective and key result tracking.', '{multi-tenant}', 'OPS', 'system-seed', now()),
  ('public', 'op_goal_snapshots', NULL, 'OKR/goals goal snapshots — objective and key result tracking.', '{analytics,multi-tenant}', 'OPS', 'system-seed', now()),
  ('public', 'op_goals', NULL, 'OKR/goals goals — objective and key result tracking.', '{timestamped,soft-delete,multi-tenant}', 'OPS', 'system-seed', now()),
  ('public', 'op_task_attachments', NULL, 'Task management task attachments — operational task system.', '{}', 'OPS', 'system-seed', now()),
  ('public', 'op_task_comments', NULL, 'Task management task comments — operational task system.', '{timestamped,soft-delete}', 'OPS', 'system-seed', now()),
  ('public', 'op_task_dependencies', NULL, 'Task management task dependencies — operational task system.', '{}', 'OPS', 'system-seed', now()),
  ('public', 'op_task_events', NULL, 'Task management task events — operational task system.', '{audit}', 'OPS', 'system-seed', now()),
  ('public', 'op_task_template_steps', NULL, 'Task management task template steps — operational task system.', '{}', 'OPS', 'system-seed', now()),
  ('public', 'op_task_templates', NULL, 'Task management task templates — operational task system.', '{timestamped,soft-delete,multi-tenant}', 'OPS', 'system-seed', now()),
  ('public', 'op_task_trigger_events', NULL, 'Task management task trigger events — operational task system.', '{audit}', 'OPS', 'system-seed', now()),
  ('public', 'op_task_triggers', NULL, 'Task management task triggers — operational task system.', '{timestamped,soft-delete,multi-tenant}', 'OPS', 'system-seed', now()),
  ('public', 'op_task_views', NULL, 'Task management task views — operational task system.', '{timestamped,soft-delete,multi-tenant}', 'OPS', 'system-seed', now()),
  ('public', 'op_tasks', NULL, 'Task management tasks — operational task system.', '{timestamped,soft-delete,multi-tenant}', 'OPS', 'system-seed', now()),
  ('public', 'order', NULL, 'Order. multi-tenant. wide table (35 columns).', '{timestamped,multi-tenant}', 'SAL', 'system-seed', now()),
  ('public', 'order_line_item', NULL, 'Order line item. multi-tenant.', '{multi-tenant}', 'SAL', 'system-seed', now()),
  ('public', 'payment', NULL, 'Payment.', '{timestamped}', 'FIN', 'system-seed', now()),
  ('public', 'prc_price_rules', NULL, 'Prc price rules. multi-tenant.', '{config,multi-tenant}', 'PRC', 'system-seed', now()),
  ('public', 'prc_valuations', NULL, 'Prc valuations.', '{}', 'PRC', 'system-seed', now()),
  ('public', 'product_categories', NULL, 'Product categories.', '{timestamped,master-data}', 'SHP', 'system-seed', now()),
  ('public', 'product_evaluations', NULL, 'Product evaluations.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'product_subcategories', NULL, 'Product subcategories.', '{timestamped,master-data}', 'SHP', 'system-seed', now()),
  ('public', 'profit_lab_benchmarks', NULL, 'Profit Lab benchmarks — product margin analysis and supplier scoring.', '{timestamped}', 'FIN', 'system-seed', now()),
  ('public', 'profit_lab_products', NULL, 'Profit Lab products — product margin analysis and supplier scoring.', '{timestamped}', 'FIN', 'system-seed', now()),
  ('public', 'profit_lab_scenarios', NULL, 'Profit Lab scenarios — product margin analysis and supplier scoring.', '{timestamped}', 'FIN', 'system-seed', now()),
  ('public', 'profit_lab_supplier_categories', NULL, 'Profit Lab supplier categories — product margin analysis and supplier scoring.', '{master-data}', 'FIN', 'system-seed', now()),
  ('public', 'profit_lab_supplier_contacts', NULL, 'Profit Lab supplier contacts — product margin analysis and supplier scoring.', '{}', 'FIN', 'system-seed', now()),
  ('public', 'profit_lab_suppliers', NULL, 'Profit Lab suppliers — product margin analysis and supplier scoring.', '{timestamped}', 'FIN', 'system-seed', now()),
  ('public', 'prt_portal_sessions', NULL, 'Prt portal sessions.', '{}', 'PRT', 'system-seed', now()),
  ('public', 'publish_structure', NULL, 'Publish structure.', '{timestamped}', 'LST', 'system-seed', now()),
  ('public', 'publish_structure_field', NULL, 'Publish structure field.', '{}', 'LST', 'system-seed', now()),
  ('public', 'qa_check_runs', NULL, 'Qa check runs.', '{}', 'QA', 'system-seed', now()),
  ('public', 'qa_checks', NULL, 'Qa checks.', '{}', 'QA', 'system-seed', now()),
  ('public', 'qa_scores', NULL, 'Qa scores.', '{}', 'QA', 'system-seed', now()),
  ('public', 'quote_submission', NULL, 'Quote submission.', '{}', 'SAL', 'system-seed', now()),
  ('public', 'record_field_history', NULL, 'Record field history.', '{audit}', 'SYS', 'system-seed', now()),
  ('public', 'redirect_clicks', NULL, 'Redirect clicks.', '{}', 'SYS', 'system-seed', now()),
  ('public', 'rental_blackout', NULL, 'Vehicle rental blackout — booking and availability management.', '{multi-tenant}', 'RNT', 'system-seed', now()),
  ('public', 'rental_bookings', NULL, 'Vehicle rental bookings — booking and availability management.', '{timestamped,multi-tenant}', 'RNT', 'system-seed', now()),
  ('public', 'rental_vehicle_config', NULL, 'Vehicle rental vehicle config — booking and availability management.', '{timestamped,config,multi-tenant}', 'RNT', 'system-seed', now()),
  ('public', 'review_invitations', NULL, 'Review invitations. multi-tenant.', '{multi-tenant}', 'REV', 'system-seed', now()),
  ('public', 'review_platform_clicks', NULL, 'Review platform clicks.', '{}', 'REV', 'system-seed', now()),
  ('public', 'reviews', NULL, 'Reviews. multi-tenant.', '{multi-tenant}', 'REV', 'system-seed', now()),
  ('public', 'rollback_snapshots', NULL, 'Rollback snapshots.', '{analytics}', 'DEV', 'system-seed', now()),
  ('public', 'sal_contracts', NULL, 'Sales contracts — vehicle sales lifecycle management.', '{transaction,multi-tenant}', 'SAL', 'system-seed', now()),
  ('public', 'sal_handovers', NULL, 'Sales handovers — vehicle sales lifecycle management.', '{timestamped,multi-tenant}', 'SAL', 'system-seed', now()),
  ('public', 'sal_orders', NULL, 'Sales orders — vehicle sales lifecycle management.', '{timestamped,transaction,soft-delete,multi-tenant}', 'SAL', 'system-seed', now()),
  ('public', 'sal_quotations', NULL, 'Sales quotations — vehicle sales lifecycle management.', '{timestamped,transaction,soft-delete,multi-tenant}', 'SAL', 'system-seed', now()),
  ('public', 'sal_surveys', NULL, 'Sales surveys — vehicle sales lifecycle management.', '{timestamped,multi-tenant}', 'SAL', 'system-seed', now()),
  ('public', 'sal_warranties', NULL, 'Sales warranties — vehicle sales lifecycle management.', '{timestamped,multi-tenant}', 'SAL', 'system-seed', now()),
  ('public', 'sal_warranty_claims', NULL, 'Sales warranty claims — vehicle sales lifecycle management.', '{timestamped,multi-tenant}', 'SAL', 'system-seed', now()),
  ('public', 'security_event_log', NULL, 'Security event log.', '{audit,security}', 'SYS', 'system-seed', now()),
  ('public', 'sell_lead_events', NULL, 'Sell/trade-in lead events — consumer vehicle selling flow.', '{crm,audit}', 'SEL', 'system-seed', now()),
  ('public', 'sell_lead_images', NULL, 'Sell/trade-in lead images — consumer vehicle selling flow.', '{media,crm}', 'SEL', 'system-seed', now()),
  ('public', 'sell_leads', NULL, 'Sell/trade-in leads — consumer vehicle selling flow.', '{crm,timestamped}', 'SEL', 'system-seed', now()),
  ('public', 'sell_rdw_cache', NULL, 'Sell/trade-in rdw cache — consumer vehicle selling flow.', '{}', 'SEL', 'system-seed', now()),
  ('public', 'sell_valuation_ranges', NULL, 'Sell/trade-in valuation ranges — consumer vehicle selling flow.', '{}', 'SEL', 'system-seed', now()),
  ('public', 'session_events', NULL, 'Session events.', '{audit}', 'ANL', 'system-seed', now()),
  ('public', 'sessions', NULL, 'Sessions. wide table (23 columns).', '{}', 'ANL', 'system-seed', now()),
  ('public', 'settings', NULL, 'Settings.', '{timestamped}', 'SYS', 'system-seed', now()),
  ('public', 'shop_addresses', NULL, 'Webshop addresses.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_attribute_groups', NULL, 'Webshop attribute groups.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_attributes', NULL, 'Webshop attributes.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_brands', NULL, 'Webshop brands.', '{timestamped,master-data}', 'SHP', 'system-seed', now()),
  ('public', 'shop_bundle_components', NULL, 'Webshop bundle components.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_bundles', NULL, 'Webshop bundles.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_carriers', NULL, 'Webshop carriers — shipping and logistics configuration.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_cart_lines', NULL, 'Webshop cart lines.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_carts', NULL, 'Webshop carts.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_claim_events', NULL, 'Webshop claim events — returns, refunds, and after-sales service.', '{audit}', 'SHP', 'system-seed', now()),
  ('public', 'shop_claim_photos', NULL, 'Webshop claim photos — returns, refunds, and after-sales service.', '{media}', 'SHP', 'system-seed', now()),
  ('public', 'shop_claims', NULL, 'Webshop claims — returns, refunds, and after-sales service.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_collection_products', NULL, 'Webshop collection products — product catalog and pricing.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_collection_rules', NULL, 'Webshop collection rules — content and SEO management.', '{config}', 'SHP', 'system-seed', now()),
  ('public', 'shop_collections', NULL, 'Webshop collections — content and SEO management.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_compliance_registrations', NULL, 'Webshop compliance registrations.', '{timestamped,multi-tenant}', 'SHP', 'system-seed', now()),
  ('public', 'shop_consents', NULL, 'Webshop consents — customer accounts and preferences.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_content_blocks', NULL, 'Webshop content blocks — content and SEO management.', '{timestamped,i18n}', 'SHP', 'system-seed', now()),
  ('public', 'shop_cost_parameter', NULL, 'Webshop cost parameter.', '{config,multi-tenant}', 'SHP', 'system-seed', now()),
  ('public', 'shop_cost_prices', NULL, 'Webshop cost prices — product catalog and pricing.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_country_capabilities', NULL, 'Webshop country capabilities.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_coupon_redemptions', NULL, 'Webshop coupon redemptions — promotions and discount system.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_coupons', NULL, 'Webshop coupons — promotions and discount system.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_credit_note_counters', NULL, 'Webshop credit note counters — financial/accounting records.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_credit_note_lines', NULL, 'Webshop credit note lines — financial/accounting records.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_credit_notes', NULL, 'Webshop credit notes — financial/accounting records.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_customer_agreements', NULL, 'Webshop customer agreements — customer accounts and preferences.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_customer_group_memberships', NULL, 'Webshop customer group memberships — customer accounts and preferences.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_customer_groups', NULL, 'Webshop customer groups — customer accounts and preferences.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_customer_tax_ids', NULL, 'Webshop customer tax ids — customer accounts and preferences.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_customers', NULL, 'Webshop customers — customer accounts and preferences.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_documents', NULL, 'Webshop documents.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_fitment', NULL, 'Webshop fitment.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_fitment_requests', NULL, 'Webshop fitment requests.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_fitment_targets', NULL, 'Webshop fitment targets.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_hazard_profiles', NULL, 'Webshop hazard profiles.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_invoice_counters', NULL, 'Webshop invoice counters — financial/accounting records.', '{transaction}', 'SHP', 'system-seed', now()),
  ('public', 'shop_invoice_lines', NULL, 'Webshop invoice lines — financial/accounting records.', '{transaction}', 'SHP', 'system-seed', now()),
  ('public', 'shop_invoices', NULL, 'Webshop invoices — financial/accounting records.', '{timestamped,transaction}', 'SHP', 'system-seed', now()),
  ('public', 'shop_legal_documents', NULL, 'Webshop legal documents.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_locations', NULL, 'Webshop locations.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_marketing_tokens', NULL, 'Webshop marketing tokens.', '{security}', 'SHP', 'system-seed', now()),
  ('public', 'shop_media', NULL, 'Webshop media.', '{media}', 'SHP', 'system-seed', now()),
  ('public', 'shop_option_values', NULL, 'Webshop option values — product catalog and pricing.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_options', NULL, 'Webshop options — product catalog and pricing.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_order_events', NULL, 'Webshop order events — part of the order management system.', '{audit,transaction}', 'SHP', 'system-seed', now()),
  ('public', 'shop_order_line_allocations', NULL, 'Webshop order line allocations — part of the order management system.', '{transaction}', 'SHP', 'system-seed', now()),
  ('public', 'shop_order_lines', NULL, 'Webshop order lines — part of the order management system.', '{transaction}', 'SHP', 'system-seed', now()),
  ('public', 'shop_orders', NULL, 'Webshop orders — part of the order management system.', '{timestamped,transaction}', 'SHP', 'system-seed', now()),
  ('public', 'shop_oss_lines', NULL, 'Webshop oss lines — financial/accounting records.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_oss_periods', NULL, 'Webshop oss periods — financial/accounting records.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_oss_tracker', NULL, 'Webshop oss tracker — financial/accounting records.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_packaging', NULL, 'Webshop packaging — shipping and logistics configuration.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_pages', NULL, 'Webshop pages — content and SEO management.', '{timestamped,multi-tenant}', 'SHP', 'system-seed', now()),
  ('public', 'shop_payment_events', NULL, 'Webshop payment events — financial/accounting records.', '{audit,transaction}', 'SHP', 'system-seed', now()),
  ('public', 'shop_payments', NULL, 'Webshop payments — financial/accounting records.', '{timestamped,transaction}', 'SHP', 'system-seed', now()),
  ('public', 'shop_po_lines', NULL, 'Webshop po lines — supplier and procurement management.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_po_receipts', NULL, 'Webshop po receipts — supplier and procurement management.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_price_history', NULL, 'Webshop price history — product catalog and pricing.', '{audit}', 'SHP', 'system-seed', now()),
  ('public', 'shop_price_lists', NULL, 'Webshop price lists — product catalog and pricing.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_prices', NULL, 'Webshop prices — product catalog and pricing.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_producer_fees', NULL, 'Webshop producer fees.', '{multi-tenant}', 'SHP', 'system-seed', now()),
  ('public', 'shop_product_categories', NULL, 'Webshop product categories — product catalog and pricing.', '{master-data}', 'SHP', 'system-seed', now()),
  ('public', 'shop_product_cost', NULL, 'Webshop product cost — product catalog and pricing.', '{timestamped,multi-tenant}', 'SHP', 'system-seed', now()),
  ('public', 'shop_product_media', NULL, 'Webshop product media — product catalog and pricing.', '{media}', 'SHP', 'system-seed', now()),
  ('public', 'shop_products', NULL, 'Webshop products — product catalog and pricing.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_promotion_rules', NULL, 'Webshop promotion rules — promotions and discount system.', '{config}', 'SHP', 'system-seed', now()),
  ('public', 'shop_promotions', NULL, 'Webshop promotions — promotions and discount system.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_purchase_orders', NULL, 'Webshop purchase orders — part of the order management system.', '{timestamped,transaction,multi-tenant}', 'SHP', 'system-seed', now()),
  ('public', 'shop_redirects', NULL, 'Webshop redirects — content and SEO management.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_refund_requests', NULL, 'Webshop refund requests — returns, refunds, and after-sales service.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_refunds', NULL, 'Webshop refunds — returns, refunds, and after-sales service.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_related_products', NULL, 'Webshop related products — product catalog and pricing.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_return_events', NULL, 'Webshop return events — returns, refunds, and after-sales service.', '{audit}', 'SHP', 'system-seed', now()),
  ('public', 'shop_return_inspections', NULL, 'Webshop return inspections — returns, refunds, and after-sales service.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_return_lines', NULL, 'Webshop return lines — returns, refunds, and after-sales service.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_returns', NULL, 'Webshop returns — returns, refunds, and after-sales service.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_rma_counters', NULL, 'Webshop rma counters — returns, refunds, and after-sales service.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_search_queries', NULL, 'Webshop search queries.', '{search}', 'SHP', 'system-seed', now()),
  ('public', 'shop_search_synonyms', NULL, 'Webshop search synonyms.', '{search}', 'SHP', 'system-seed', now()),
  ('public', 'shop_seo_overrides', NULL, 'Webshop seo overrides — content and SEO management.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_settings', NULL, 'Webshop settings.', '{config}', 'SHP', 'system-seed', now()),
  ('public', 'shop_settlement_lines', NULL, 'Webshop settlement lines — financial/accounting records.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_settlements', NULL, 'Webshop settlements — financial/accounting records.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_shipping_methods', NULL, 'Webshop shipping methods — shipping and logistics configuration.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_shipping_rate_rules', NULL, 'Webshop shipping rate rules — shipping and logistics configuration.', '{config}', 'SHP', 'system-seed', now()),
  ('public', 'shop_shipping_zones', NULL, 'Webshop shipping zones — shipping and logistics configuration.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_stock_count_lines', NULL, 'Webshop stock count lines — inventory and warehouse management.', '{inventory}', 'SHP', 'system-seed', now()),
  ('public', 'shop_stock_counts', NULL, 'Webshop stock counts — inventory and warehouse management.', '{timestamped,inventory,multi-tenant}', 'SHP', 'system-seed', now()),
  ('public', 'shop_stock_items', NULL, 'Webshop stock items — inventory and warehouse management.', '{inventory}', 'SHP', 'system-seed', now()),
  ('public', 'shop_stock_movements', NULL, 'Webshop stock movements — inventory and warehouse management.', '{inventory}', 'SHP', 'system-seed', now()),
  ('public', 'shop_stock_reservations', NULL, 'Webshop stock reservations — inventory and warehouse management.', '{inventory}', 'SHP', 'system-seed', now()),
  ('public', 'shop_supplier_rmas', NULL, 'Webshop supplier rmas — returns, refunds, and after-sales service.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_supplier_variants', NULL, 'Webshop supplier variants — product catalog and pricing.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_suppliers', NULL, 'Webshop suppliers — supplier and procurement management.', '{timestamped,multi-tenant}', 'SHP', 'system-seed', now()),
  ('public', 'shop_tax_classes', NULL, 'Webshop tax classes.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_tax_rates', NULL, 'Webshop tax rates.', '{config}', 'SHP', 'system-seed', now()),
  ('public', 'shop_variant_attribute_values', NULL, 'Webshop variant attribute values — product catalog and pricing.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_variant_options', NULL, 'Webshop variant options — product catalog and pricing.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_variants', NULL, 'Webshop variants — product catalog and pricing.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_vat_periods', NULL, 'Webshop vat periods — financial/accounting records.', '{timestamped}', 'SHP', 'system-seed', now()),
  ('public', 'shop_vat_transactions', NULL, 'Webshop vat transactions — financial/accounting records.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_webhook_inbox', NULL, 'Webshop webhook inbox.', '{integration}', 'SHP', 'system-seed', now()),
  ('public', 'shop_wishlist_items', NULL, 'Webshop wishlist items — customer accounts and preferences.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'shop_wishlists', NULL, 'Webshop wishlists — customer accounts and preferences.', '{}', 'SHP', 'system-seed', now()),
  ('public', 'short_links', NULL, 'Short links. multi-tenant. wide table (21 columns).', '{timestamped,multi-tenant}', 'MKT', 'system-seed', now()),
  ('public', 'site_analytics_snapshot', NULL, 'Site analytics snapshot. multi-tenant.', '{analytics,multi-tenant}', 'ANL', 'system-seed', now()),
  ('public', 'source_prefixes', NULL, 'Source prefixes. multi-tenant.', '{timestamped,multi-tenant}', 'ANL', 'system-seed', now()),
  ('public', 'st_drive_accounts', NULL, 'St drive accounts.', '{timestamped}', 'ST', 'system-seed', now()),
  ('public', 'st_files', NULL, 'St files.', '{timestamped}', 'ST', 'system-seed', now()),
  ('public', 'staff', NULL, 'Staff.', '{timestamped}', 'SYS', 'system-seed', now()),
  ('public', 'sup_messages', NULL, 'Sup messages.', '{}', 'SUP', 'system-seed', now()),
  ('public', 'sup_requests', NULL, 'Sup requests. multi-tenant.', '{timestamped,multi-tenant}', 'SUP', 'system-seed', now()),
  ('public', 'survey_responses', NULL, 'Survey responses. multi-tenant.', '{multi-tenant}', 'SAL', 'system-seed', now()),
  ('public', 'sy_deliverables', NULL, 'System implementation deliverables — program/phase/task tracking for BOP development.', '{timestamped}', 'SY', 'system-seed', now()),
  ('public', 'sy_phases', NULL, 'System implementation phases — program/phase/task tracking for BOP development.', '{timestamped}', 'SY', 'system-seed', now()),
  ('public', 'sy_programs', NULL, 'System implementation programs — program/phase/task tracking for BOP development.', '{timestamped}', 'SY', 'system-seed', now()),
  ('public', 'sy_task_deps', NULL, 'System implementation task deps — program/phase/task tracking for BOP development.', '{}', 'SY', 'system-seed', now()),
  ('public', 'sy_task_events', NULL, 'System implementation task events — program/phase/task tracking for BOP development.', '{audit}', 'SY', 'system-seed', now()),
  ('public', 'sy_tasks', NULL, 'System implementation tasks — program/phase/task tracking for BOP development.', '{timestamped}', 'SY', 'system-seed', now()),
  ('public', 'sy_template_items', NULL, 'System implementation template items — program/phase/task tracking for BOP development.', '{}', 'SY', 'system-seed', now()),
  ('public', 'sy_templates', NULL, 'System implementation templates — program/phase/task tracking for BOP development.', '{timestamped}', 'SY', 'system-seed', now()),
  ('public', 'sys_notifications', NULL, 'Sys notifications. multi-tenant.', '{multi-tenant}', NULL, 'system-seed', now()),
  ('public', 'tasks', NULL, 'Tasks.', '{timestamped}', 'OPS', 'system-seed', now()),
  ('public', 'tenant_email_brand', NULL, 'Tenant email brand — multi-tenant configuration.', '{email,timestamped,multi-tenant}', 'TNT', 'system-seed', now()),
  ('public', 'tenant_email_template', NULL, 'Tenant email template — multi-tenant configuration.', '{email,timestamped,multi-tenant}', 'TNT', 'system-seed', now()),
  ('public', 'tenant_site_features', NULL, 'Tenant site features — multi-tenant configuration.', '{multi-tenant}', 'TNT', 'system-seed', now()),
  ('public', 'tenant_status', NULL, 'Tenant status — multi-tenant configuration.', '{timestamped,multi-tenant}', 'TNT', 'system-seed', now()),
  ('public', 'tenants', NULL, 'Tenants. wide table (43 columns).', '{timestamped}', NULL, 'system-seed', now()),
  ('public', 'user_guide_progress', NULL, 'User guide progress.', '{}', 'SYS', 'system-seed', now()),
  ('public', 'vehicles', NULL, 'Vehicles.', '{timestamped,soft-delete}', 'AST', 'system-seed', now()),
  ('public', 'watermark_profiles', NULL, 'Watermark profiles.', '{timestamped}', 'MKT', 'system-seed', now()),
  ('public', 'wfl_tasks', NULL, 'Wfl tasks. multi-tenant.', '{multi-tenant}', 'WFL', 'system-seed', now()),
  ('public', 'wrk_apk_reminders', NULL, 'Workshop apk reminders — vehicle service and repair operations.', '{multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_approvals', NULL, 'Workshop approvals — vehicle service and repair operations.', '{multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_autoflex_config', NULL, 'Workshop autoflex config — vehicle service and repair operations.', '{timestamped,config,integration,multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_autoflex_field_maps', NULL, 'Workshop autoflex field maps — vehicle service and repair operations.', '{timestamped,integration,multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_autoflex_sync_logs', NULL, 'Workshop autoflex sync logs — vehicle service and repair operations.', '{audit,integration,multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_cost_lines', NULL, 'Workshop cost lines — vehicle service and repair operations.', '{}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_efficiency_metrics', NULL, 'Workshop efficiency metrics — vehicle service and repair operations.', '{analytics,multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_inspections', NULL, 'Workshop inspections — vehicle service and repair operations.', '{timestamped,multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_labour_rates', NULL, 'Workshop labour rates — vehicle service and repair operations.', '{config,multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_order_lines', NULL, 'Workshop order lines — vehicle service and repair operations.', '{transaction,multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_orders', NULL, 'Workshop orders — vehicle service and repair operations.', '{timestamped,transaction,soft-delete,multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_planning_slots', NULL, 'Workshop planning slots — vehicle service and repair operations.', '{multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_service_packages', NULL, 'Workshop service packages — vehicle service and repair operations.', '{timestamped,multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_technicians', NULL, 'Workshop technicians — vehicle service and repair operations.', '{timestamped,multi-tenant}', 'WRK', 'system-seed', now()),
  ('public', 'wrk_work_orders', NULL, 'Workshop work orders — vehicle service and repair operations.', '{transaction,multi-tenant}', 'WRK', 'system-seed', now())
ON CONFLICT (schema_name, table_name, column_name)
DO UPDATE SET description = EXCLUDED.description, tags = EXCLUDED.tags, module = EXCLUDED.module, updated_by = EXCLUDED.updated_by, updated_at = EXCLUDED.updated_at
WHERE bop_table_docs.updated_by = 'system-seed';  -- only overwrite auto-generated, not manually edited
