-- ============================================================================
-- Migration: bop_screen_meta — populate db_tables + api_routes from code scan
-- Generated: 2026-09-03 by AI code analysis
-- 
-- Scanned:
--   288 API route files for .from() / SQL table references
--   208 console page directories for /api/bop/ fetch calls
--   307 screen registry entries
--   Result: 201 screens with mappings
-- 
-- Logic:
--   UPSERT into bop_screen_meta; only overwrites db_tables / api_routes
--   when the existing value is empty (NULL or []). Manually-edited rows are
--   left untouched.
-- ============================================================================

-- Fix SY007: was incorrectly set
UPDATE bop_screen_meta SET db_tables = '["ci_job_run", "bop_change_log"]'::jsonb WHERE screen_id = 'SY007';

INSERT INTO bop_screen_meta (screen_id, api_routes, db_tables, updated_at)
VALUES
  ('AI001', '["/api/bop/access-audit"]'::jsonb, '["bop_change_log", "bop_sessions", "bop_user_activity"]'::jsonb, now()),
  ('AI003', '["/api/bop/sys/settings"]'::jsonb, '["bop_objects", "bop_settings"]'::jsonb, now()),
  ('AI004', '["/api/bop/access-audit"]'::jsonb, '["bop_change_log", "bop_sessions", "bop_user_activity"]'::jsonb, now()),
  ('AI005', '["/api/bop/ai/agents", "/api/bop/ai/chat"]'::jsonb, '["bop_ai_agents", "bop_documentation"]'::jsonb, now()),
  ('AN001', '["/api/bop/an/cockpits"]'::jsonb, '["anl_alert_rules", "anl_daily_snapshots", "dm_activity_log", "dm_activity_sessions", "dm_conversations", "dm_profiles", "sell_leads"]'::jsonb, now()),
  ('AN002', '["/api/bop/an/cockpits"]'::jsonb, '["anl_alert_rules", "anl_daily_snapshots", "dm_activity_log", "dm_activity_sessions", "dm_conversations", "dm_profiles", "sell_leads"]'::jsonb, now()),
  ('AN003', '["/api/bop/an/cockpits"]'::jsonb, '["anl_alert_rules", "anl_daily_snapshots", "dm_activity_log", "dm_activity_sessions", "dm_conversations", "dm_profiles", "sell_leads"]'::jsonb, now()),
  ('AN004', '["/api/bop/an/cockpits"]'::jsonb, '["anl_alert_rules", "anl_daily_snapshots", "dm_activity_log", "dm_activity_sessions", "dm_conversations", "dm_profiles", "sell_leads"]'::jsonb, now()),
  ('AN005', '["/api/bop/an/cockpits"]'::jsonb, '["anl_alert_rules", "anl_daily_snapshots", "dm_activity_log", "dm_activity_sessions", "dm_conversations", "dm_profiles", "sell_leads"]'::jsonb, now()),
  ('AN006', '["/api/bop/an/cockpits"]'::jsonb, '["anl_alert_rules", "anl_daily_snapshots", "dm_activity_log", "dm_activity_sessions", "dm_conversations", "dm_profiles", "sell_leads"]'::jsonb, now()),
  ('AS001', '["/api/bop/ast/assets", "/api/bop/md/partners"]'::jsonb, '["ast_assets", "ast_lifecycle_events", "mdm_business_partners", "mdm_partner_roles"]'::jsonb, now()),
  ('AS002', '["/api/bop/ast/assets", "/api/bop/md/partners"]'::jsonb, '["ast_assets", "ast_lifecycle_events", "mdm_business_partners", "mdm_partner_roles"]'::jsonb, now()),
  ('AU001', '["/api/bop/mkp/auctions"]'::jsonb, '["bop_auctions"]'::jsonb, now()),
  ('AU002', '["/api/bop/mkp/auctions", "/api/bop/mkp/bop-listings"]'::jsonb, '["bop_auctions", "bop_listing_media", "bop_listing_pricing", "bop_listings"]'::jsonb, now()),
  ('AU004', '["/api/bop/mkp/auctions"]'::jsonb, '["bop_auctions"]'::jsonb, now()),
  ('BO031', '["/api/bop/an/cleanup", "/api/bop/an/delete-params", "/api/bop/an/purge"]'::jsonb, '["activity_log2_delete_parameters", "dm_activity_log", "dm_activity_sessions"]'::jsonb, now()),
  ('CE001', '["/api/bop/content-engine/definitions"]'::jsonb, '["field_definitions"]'::jsonb, now()),
  ('CE002', '["/api/bop/content-engine/templates"]'::jsonb, '["listing_tab_templates"]'::jsonb, now()),
  ('CE003', '["/api/bop/content-engine/templates"]'::jsonb, '["listing_tab_templates"]'::jsonb, now()),
  ('CR001', '["/api/bop/crm/leads"]'::jsonb, '["crm_leads"]'::jsonb, now()),
  ('CR002', '["/api/bop/crm/activities", "/api/bop/crm/leads"]'::jsonb, '["crm_activities", "crm_leads"]'::jsonb, now()),
  ('CR003', '["/api/bop/crm/lead-stats"]'::jsonb, '["crm_leads"]'::jsonb, now()),
  ('CR004', '["/api/bop/crm/activities", "/api/bop/crm/leads"]'::jsonb, '["crm_activities", "crm_leads"]'::jsonb, now()),
  ('CR005', '["/api/bop/md/partners"]'::jsonb, '["mdm_business_partners", "mdm_partner_roles"]'::jsonb, now()),
  ('CR006', '["/api/bop/crm/leads"]'::jsonb, '["crm_leads"]'::jsonb, now()),
  ('CR008', '["/api/bop/crm/deals"]'::jsonb, '["crm_deals"]'::jsonb, now()),
  ('CR009', '["/api/bop/crm/deals", "/api/bop/crm/events"]'::jsonb, '["crm_activities", "crm_deals", "crm_events"]'::jsonb, now()),
  ('CR021', '["/api/bop/crm/customer", "/api/bop/md/partners", "/api/bop/sal/cases"]'::jsonb, '["bop_cases", "mdm_business_partners", "mdm_partner_roles"]'::jsonb, now()),
  ('DA001', '["/api/bop/dae/cockpit", "/api/bop/dae/price-history", "/api/bop/dae/review"]'::jsonb, '["dae_listings", "dae_price_history", "dae_reviews"]'::jsonb, now()),
  ('DA002', '["/api/bop/dae/profiles"]'::jsonb, '["dae_search_jobs"]'::jsonb, now()),
  ('DA003', '["/api/bop/dae/sources"]'::jsonb, '["dae_sources"]'::jsonb, now()),
  ('DA004', '["/api/bop/dae/runs"]'::jsonb, '["dae_runs"]'::jsonb, now()),
  ('DA005', '["/api/bop/dae/pricing"]'::jsonb, '["dae_listings", "dae_price_history"]'::jsonb, now()),
  ('DB001', '["/api/bop/dba/overview"]'::jsonb, '["bop_meta"]'::jsonb, now()),
  ('DB002', '["/api/bop/dba/docs", "/api/bop/dba/schema"]'::jsonb, '["bop_meta", "bop_screen_meta", "bop_screens", "bop_table_docs"]'::jsonb, now()),
  ('DB003', '["/api/bop/dba/data", "/api/bop/dba/docs", "/api/bop/dba/schema"]'::jsonb, '["bop_meta", "bop_screen_meta", "bop_screens", "bop_table_docs"]'::jsonb, now()),
  ('DB005', '["/api/bop/dba/functions", "/api/bop/dba/schema"]'::jsonb, '["bop_meta", "bop_screen_meta", "bop_screens"]'::jsonb, now()),
  ('DV001', '["/api/bop/dev/commits", "/api/bop/dev/enhancements", "/api/bop/dev/environment-states"]'::jsonb, '["dev_commits", "dev_enhancements", "environment_states"]'::jsonb, now()),
  ('DV002', '["/api/bop/dev/enhancements", "/api/bop/dev/releases"]'::jsonb, '["dev_enhancements", "dev_releases"]'::jsonb, now()),
  ('DV003', '["/api/bop/dev/commits", "/api/bop/dev/environment-states", "/api/bop/dev/promote"]'::jsonb, '["dev_commits", "environment_states"]'::jsonb, now()),
  ('DV004', '["/api/bop/dev/commits"]'::jsonb, '["dev_commits"]'::jsonb, now()),
  ('DV005', '["/api/bop/dev/deployments"]'::jsonb, '["dev_deployments", "dev_releases", "environment_states"]'::jsonb, now()),
  ('DV006', '["/api/bop/dev/releases"]'::jsonb, '["dev_releases"]'::jsonb, now()),
  ('DV007', '["/api/bop/dev/definition-audit"]'::jsonb, '["bop_dependencies", "bop_documentation", "bop_objects", "bop_screens"]'::jsonb, now()),
  ('DV008', '["/api/bop/user/me"]'::jsonb, '["bop_user_profiles"]'::jsonb, now()),
  ('FI001', '["/api/bop/fin/invoices", "/api/bop/fin/payments", "/api/bop/md/partners", "/api/bop/sal/quotations"]'::jsonb, '["fin_invoices", "fin_payments", "mdm_business_partners", "mdm_partner_roles", "sal_quotations"]'::jsonb, now()),
  ('FI002', '["/api/bop/fin/payments"]'::jsonb, '["fin_invoices", "fin_payments"]'::jsonb, now()),
  ('FI011', '["/api/bop/fin/invoices", "/api/bop/fin/payments", "/api/bop/md/partners", "/api/bop/sal/quotations"]'::jsonb, '["fin_invoices", "fin_payments", "mdm_business_partners", "mdm_partner_roles", "sal_quotations"]'::jsonb, now()),
  ('FI012', '["/api/bop/fin/ap/invoices", "/api/bop/md/partners"]'::jsonb, '["fin_invoices", "mdm_business_partners", "mdm_partner_roles"]'::jsonb, now()),
  ('IN001', '["/api/bop/inv/catalog"]'::jsonb, '["bop_brands", "bop_listing_categories", "bop_listings"]'::jsonb, now()),
  ('IN002', '["/api/bop/mkp/brands"]'::jsonb, '["bop_brands", "bop_listings", "bop_models"]'::jsonb, now()),
  ('IN003', '["/api/bop/mkp/taxonomy"]'::jsonb, '["bop_body_type_labels", "bop_body_types", "bop_listing_categories", "bop_listing_category_labels", "bop_listings"]'::jsonb, now()),
  ('IN005', '["/api/bop/ast/lifecycle"]'::jsonb, '["ast_assets"]'::jsonb, now()),
  ('IN006', '["/api/bop/mkp/brands", "/api/bop/mkp/models"]'::jsonb, '["bop_brands", "bop_listings", "bop_models"]'::jsonb, now()),
  ('IT001', '["/api/bop/int/connectors", "/api/bop/int/run"]'::jsonb, '["int_systems"]'::jsonb, now()),
  ('IT002', '["/api/bop/int/sync-log"]'::jsonb, '["int_runs"]'::jsonb, now()),
  ('IT003', '["/api/bop/int/flows"]'::jsonb, '["int_flows"]'::jsonb, now()),
  ('IT004', '["/api/bop/int/queue"]'::jsonb, '["int_messages"]'::jsonb, now()),
  ('IT005', '["/api/bop/int/flows", "/api/bop/int/mappings"]'::jsonb, '["int_flows", "int_mappings"]'::jsonb, now()),
  ('IT006', '["/api/bop/int/connectors", "/api/bop/int/lookup-tables", "/api/bop/int/lookup-values"]'::jsonb, '["int_lookup_tables", "int_lookup_values", "int_systems"]'::jsonb, now()),
  ('IT007', '["/api/bop/int/queue"]'::jsonb, '["int_messages"]'::jsonb, now()),
  ('IT008', '["/api/bop/int/queue", "/api/bop/int/webhook"]'::jsonb, '["int_messages"]'::jsonb, now()),
  ('MD001', '["/api/bop/md/partners"]'::jsonb, '["mdm_business_partners", "mdm_partner_roles"]'::jsonb, now()),
  ('MD002', '["/api/bop/crm/customer", "/api/bop/md/partners"]'::jsonb, '["mdm_business_partners", "mdm_partner_roles"]'::jsonb, now()),
  ('MD003', '["/api/bop/md/taxonomy"]'::jsonb, '["mdm_vehicle_taxonomy"]'::jsonb, now()),
  ('MD004', '["/api/bop/md/equipment"]'::jsonb, '[]'::jsonb, now()),
  ('MK004', '["/api/bop/mkt/brand"]'::jsonb, '["bop_mkt_brand_profiles"]'::jsonb, now()),
  ('MK007', '["/api/bop/mkt/studio/images", "/api/bop/mkt/studio/proxy", "/api/bop/mkt/studio/sessions"]'::jsonb, '["bop_studio_sessions"]'::jsonb, now()),
  ('MK008', '["/api/bop/mkt/studio/preset-backgrounds", "/api/bop/mkt/studio/proxy"]'::jsonb, '["bop_studio_preset_backgrounds", "bop_studio_presets", "bop_studio_sessions"]'::jsonb, now()),
  ('MK009', '["/api/bop/banner-terms"]'::jsonb, '[]'::jsonb, now()),
  ('MK018', '["/api/bop/mkt/generate", "/api/bop/mkt/meta", "/api/bop/mkt/outputs", "/api/bop/mkt/publish"]'::jsonb, '["bop_ai_agents", "bop_listing_content", "bop_listings", "bop_mkt_brand_profiles", "bop_mkt_campaigns", "bop_mkt_channels", "bop_mkt_generations", "bop_mkt_outputs", "bop_mkt_publications"]'::jsonb, now()),
  ('MK019', '["/api/bop/mkt/dealer/reserve"]'::jsonb, '[]'::jsonb, now()),
  ('MK020', '["/api/bop/mkt/studio/preset-backgrounds", "/api/bop/mkt/studio/presets", "/api/bop/mkt/studio/proxy", "/api/bop/mkt/studio/sessions"]'::jsonb, '["bop_studio_preset_backgrounds", "bop_studio_presets", "bop_studio_sessions"]'::jsonb, now()),
  ('MP001', '["/api/bop/int/run", "/api/bop/mkp/bop-listings", "/api/bop/mkp/bop-listings/meta", "/api/bop/mkp/listings", "/api/bop/mkp/tenant-domains", "/api/bop/shortlink"]'::jsonb, '["bop_body_types", "bop_brands", "bop_feature_catalog", "bop_listing_categories", "bop_listing_media", "bop_listing_pricing", "bop_listings", "bop_models", "bop_shortlink_prefixes", "bop_tenants", "mkp_listings"]'::jsonb, now()),
  ('MP002', '["/api/bop/mkp/analytics"]'::jsonb, '["bop_listings"]'::jsonb, now()),
  ('MP003', '["/api/bop/int/publish", "/api/bop/int/run", "/api/bop/mkp/bop-listings", "/api/bop/mkp/bop-listings/meta", "/api/bop/mkp/listing-layouts", "/api/bop/mkp/listings", "/api/bop/mkp/media", "/api/bop/mkp/media/reorder", "/api/bop/mkp/media/upload", "/api/bop/mkp/tenant-domains", "/api/bop/shortlink", "/api/bop/sys/locks", "/api/bop/sys/locks/release-beacon"]'::jsonb, '["bop_body_types", "bop_brands", "bop_change_log", "bop_feature_catalog", "bop_listing_categories", "bop_listing_channels", "bop_listing_layouts", "bop_listing_media", "bop_listing_pricing", "bop_listings", "bop_models", "bop_object_locks", "bop_shortlink_prefixes", "bop_tenants", "int_flows", "int_messages", "mkp_listings"]'::jsonb, now()),
  ('MP004', '["/api/bop/ast/assets", "/api/bop/mkp/listings"]'::jsonb, '["ast_assets", "ast_lifecycle_events", "mkp_listings"]'::jsonb, now()),
  ('MP005', '["/api/bop/mkp/listing-layouts"]'::jsonb, '["bop_listing_layouts"]'::jsonb, now()),
  ('OP001', '["/api/bop/ops/tasks", "/api/bop/ops/tasks/comments", "/api/bop/ops/tasks/deps", "/api/bop/ops/tasks/events"]'::jsonb, '["op_task_comments", "op_task_dependencies", "op_task_events", "op_tasks"]'::jsonb, now()),
  ('OP002', '["/api/bop/ops/goals"]'::jsonb, '["fin_invoices", "op_goal_checkins", "op_goal_cycles", "op_goal_key_results", "op_goal_kr_snapshots", "op_goal_metrics_catalog", "op_goal_period_ledger", "op_goals", "op_tasks"]'::jsonb, now()),
  ('OP009', '["/api/bop/ops/tasks"]'::jsonb, '["op_tasks"]'::jsonb, now()),
  ('OP010', '["/api/bop/ops/tasks"]'::jsonb, '["op_tasks"]'::jsonb, now()),
  ('OP011', '["/api/bop/ops/tasks"]'::jsonb, '["op_tasks"]'::jsonb, now()),
  ('OP013', '["/api/bop/ops/tasks/analytics"]'::jsonb, '["op_task_events", "op_tasks"]'::jsonb, now()),
  ('OP014', '["/api/bop/ops/tasks", "/api/bop/ops/tasks/deps"]'::jsonb, '["op_task_dependencies", "op_tasks"]'::jsonb, now()),
  ('OP015', '["/api/bop/ops/goals"]'::jsonb, '["fin_invoices", "op_goal_checkins", "op_goal_cycles", "op_goal_key_results", "op_goal_kr_snapshots", "op_goal_metrics_catalog", "op_goal_period_ledger", "op_goals", "op_tasks"]'::jsonb, now()),
  ('OP016', '["/api/bop/ops/goals"]'::jsonb, '["fin_invoices", "op_goal_checkins", "op_goal_cycles", "op_goal_key_results", "op_goal_kr_snapshots", "op_goal_metrics_catalog", "op_goal_period_ledger", "op_goals", "op_tasks"]'::jsonb, now()),
  ('OP017', '["/api/bop/ops/goals"]'::jsonb, '["fin_invoices", "op_goal_checkins", "op_goal_cycles", "op_goal_key_results", "op_goal_kr_snapshots", "op_goal_metrics_catalog", "op_goal_period_ledger", "op_goals", "op_tasks"]'::jsonb, now()),
  ('OP018', '["/api/bop/ops/fair-scout"]'::jsonb, '[]'::jsonb, now()),
  ('SA001', '["/api/bop/ast/assets", "/api/bop/md/partners", "/api/bop/sal/quotations"]'::jsonb, '["ast_assets", "ast_lifecycle_events", "mdm_business_partners", "mdm_partner_roles", "sal_quotations"]'::jsonb, now()),
  ('SA002', '["/api/bop/ast/assets", "/api/bop/md/partners", "/api/bop/sal/quotations"]'::jsonb, '["ast_assets", "ast_lifecycle_events", "mdm_business_partners", "mdm_partner_roles", "sal_quotations"]'::jsonb, now()),
  ('SA007', '["/api/bop/sal/appointments"]'::jsonb, '["bop_appointments", "bop_comm_history"]'::jsonb, now()),
  ('SA009', '["/api/bop/sal/orders"]'::jsonb, '["sal_orders"]'::jsonb, now()),
  ('SA010', '["/api/bop/sal/orders"]'::jsonb, '["sal_orders"]'::jsonb, now()),
  ('SA011', '["/api/bop/sal/orders", "/api/bop/sal/quotations"]'::jsonb, '["sal_orders", "sal_quotations"]'::jsonb, now()),
  ('SA013', '["/api/bop/sal/sell-leads"]'::jsonb, '["sell_lead_events", "sell_leads"]'::jsonb, now()),
  ('SA014', '["/api/bop/sal/sell-leads"]'::jsonb, '["sell_lead_events", "sell_leads"]'::jsonb, now()),
  ('SA015', '["/api/bop/sal/buyer-inbox"]'::jsonb, '["dm_conversations", "dm_profiles"]'::jsonb, now()),
  ('SA016', '["/api/bop/sal/buyer-inbox"]'::jsonb, '["dm_conversations", "dm_profiles"]'::jsonb, now()),
  ('SA017', '["/api/bop/sal/inquiries"]'::jsonb, '["dm_inquiries"]'::jsonb, now()),
  ('SA018', '["/api/bop/sal/inquiries"]'::jsonb, '["dm_inquiries"]'::jsonb, now()),
  ('SA019', '["/api/bop/sal/handovers"]'::jsonb, '["sal_handovers"]'::jsonb, now()),
  ('SA022', '["/api/bop/sal/surveys"]'::jsonb, '["sal_surveys"]'::jsonb, now()),
  ('SA023', '["/api/bop/sal/warranties"]'::jsonb, '["sal_warranties"]'::jsonb, now()),
  ('SH000', '["/api/bop/shop/screens"]'::jsonb, '["bop_screens"]'::jsonb, now()),
  ('SH001', '["/api/bop/shop/catalog/products"]'::jsonb, '["shop_products"]'::jsonb, now()),
  ('SH002', '["/api/bop/shop/catalog/products"]'::jsonb, '["shop_products"]'::jsonb, now()),
  ('SH003', '["/api/bop/shop/orders"]'::jsonb, '["shop_orders"]'::jsonb, now()),
  ('SH004', '["/api/bop/shop/orders"]'::jsonb, '["shop_orders"]'::jsonb, now()),
  ('SH005', '["/api/bop/shop/monitoring"]'::jsonb, '["shop_claims", "shop_inventory", "shop_orders", "shop_payments"]'::jsonb, now()),
  ('SH006', '["/api/bop/shop/orders"]'::jsonb, '["shop_orders"]'::jsonb, now()),
  ('SH007', '["/api/bop/shop/catalog/brands"]'::jsonb, '["shop_brands"]'::jsonb, now()),
  ('SH009', '["/api/bop/shop/catalog/products", "/api/bop/shop/monitoring"]'::jsonb, '["shop_claims", "shop_inventory", "shop_orders", "shop_payments", "shop_products"]'::jsonb, now()),
  ('SH010', '["/api/bop/shop/pages"]'::jsonb, '["shop_pages"]'::jsonb, now()),
  ('SH020', '["/api/bop/shop/orders"]'::jsonb, '["shop_orders"]'::jsonb, now()),
  ('SH021', '["/api/bop/shop/orders"]'::jsonb, '["shop_orders"]'::jsonb, now()),
  ('SH030', '["/api/bop/shop/finance/vat"]'::jsonb, '["shop_vat_periods"]'::jsonb, now()),
  ('SH031', '["/api/bop/shop/finance/settlements"]'::jsonb, '["shop_settlement_lines", "shop_settlements"]'::jsonb, now()),
  ('SH032', '["/api/bop/shop/finance/invoices"]'::jsonb, '["shop_invoice_lines", "shop_invoices"]'::jsonb, now()),
  ('SH033', '["/api/bop/shop/finance/credit-notes"]'::jsonb, '["shop_credit_note_lines", "shop_credit_notes"]'::jsonb, now()),
  ('SH035', '["/api/bop/shop/finance/margin"]'::jsonb, '[]'::jsonb, now()),
  ('SH040', '["/api/bop/shop/returns"]'::jsonb, '["shop_return_lines", "shop_returns"]'::jsonb, now()),
  ('SH041', '["/api/bop/shop/claims"]'::jsonb, '["shop_claim_events", "shop_claims"]'::jsonb, now()),
  ('SH050', '["/api/bop/shop/procure/suppliers"]'::jsonb, '["shop_suppliers"]'::jsonb, now()),
  ('SH051', '["/api/bop/shop/catalog/products"]'::jsonb, '["shop_products"]'::jsonb, now()),
  ('SH052', '["/api/bop/shop/procure/po"]'::jsonb, '["shop_po_lines", "shop_purchase_orders"]'::jsonb, now()),
  ('SH053', '["/api/bop/shop/procure/stock-count"]'::jsonb, '["shop_stock_count_lines", "shop_stock_counts"]'::jsonb, now()),
  ('SH054', '["/api/bop/shop/procure/receive"]'::jsonb, '["shop_po_lines", "shop_po_receipts", "shop_purchase_orders"]'::jsonb, now()),
  ('SH057', '["/api/bop/shop/procure/po", "/api/bop/shop/procure/suppliers"]'::jsonb, '["shop_po_lines", "shop_purchase_orders", "shop_suppliers"]'::jsonb, now()),
  ('SH060', '["/api/bop/shop/compliance/registrations"]'::jsonb, '["shop_compliance_registrations"]'::jsonb, now()),
  ('SH062', '["/api/bop/shop/customers/gdpr/erase", "/api/bop/shop/customers/gdpr/export"]'::jsonb, '["shop_invoices", "shop_orders"]'::jsonb, now()),
  ('SH070', '["/api/bop/shop/monitoring"]'::jsonb, '["shop_claims", "shop_inventory", "shop_orders", "shop_payments"]'::jsonb, now()),
  ('SH071', '["/api/bop/shop/control-tower"]'::jsonb, '["shop_invoices", "shop_orders", "shop_po_lines", "shop_purchase_orders", "shop_returns", "shop_stock_items", "shop_suppliers"]'::jsonb, now()),
  ('SH080', '["/api/bop/shop/orders"]'::jsonb, '["shop_orders"]'::jsonb, now()),
  ('SH081', '["/api/bop/shop/orders"]'::jsonb, '["shop_orders"]'::jsonb, now()),
  ('SH082', '["/api/bop/shop/orders"]'::jsonb, '["shop_orders"]'::jsonb, now()),
  ('SH083', '["/api/bop/shop/fulfil/dropship/dispatch"]'::jsonb, '["shop_purchase_orders"]'::jsonb, now()),
  ('SH084', '["/api/bop/shop/payments/refund/request"]'::jsonb, '["shop_orders", "shop_refund_requests"]'::jsonb, now()),
  ('SH085', '["/api/bop/shop/returns/inspect"]'::jsonb, '["shop_return_inspections", "shop_return_lines", "shop_returns"]'::jsonb, now()),
  ('SH086', '["/api/bop/shop/compliance/fees"]'::jsonb, '["shop_producer_fees"]'::jsonb, now()),
  ('SH090', '["/api/bop/shop/guide"]'::jsonb, '["guide_steps", "user_guide_progress"]'::jsonb, now()),
  ('SH109', '["/api/bop/shop/analytics/attention"]'::jsonb, '["ci_attention_item", "ci_data_health"]'::jsonb, now()),
  ('SY001', '["/api/bop/users"]'::jsonb, '["bop_user_profiles", "bop_user_tenants"]'::jsonb, now()),
  ('SY002', '["/api/bop/sys/roles", "/api/bop/sys/screens"]'::jsonb, '["bop_roles", "bop_screens"]'::jsonb, now()),
  ('SY003', '["/api/bop/comm/mail-identities", "/api/bop/hero-images", "/api/bop/hero-images/preview", "/api/bop/hero-images/size", "/api/bop/hero-images/upload", "/api/bop/shortlink", "/api/bop/sys/email-admin", "/api/bop/sys/email/preview", "/api/bop/sys/site-features", "/api/bop/sys/tenant-config", "/api/bop/sys/tenant-status"]'::jsonb, '["bop_email_base_layout", "bop_email_brand", "bop_email_log", "bop_email_template", "bop_email_template_map", "bop_mail_identity", "bop_shortlink_prefixes", "bop_tenant_status", "bop_tenants", "hero_images", "tenant_site_features"]'::jsonb, now()),
  ('SY004', '["/api/bop/sys/settings"]'::jsonb, '["bop_objects", "bop_settings"]'::jsonb, now()),
  ('SY005', '["/api/bop/sys/admin-dashboard", "/api/bop/sys/health"]'::jsonb, '["admin_notifications", "bop_modules", "bop_roles", "bop_screens", "bop_user_tenants", "bop_users"]'::jsonb, now()),
  ('SY006', '["/api/bop/sys/admin-dashboard", "/api/bop/sys/health"]'::jsonb, '["admin_notifications", "bop_modules", "bop_roles", "bop_screens", "bop_user_tenants", "bop_users"]'::jsonb, now()),
  ('SY007', '["/api/bop/access-audit", "/api/bop/shop/analytics/jobs/history", "/api/bop/shop/analytics/jobs/trigger"]'::jsonb, '["bop_change_log", "bop_sessions", "bop_user_activity", "ci_job_run"]'::jsonb, now()),
  ('SY008', '["/api/bop/sys/admin-dashboard"]'::jsonb, '["bop_modules", "bop_roles", "bop_screens", "bop_user_tenants", "bop_users"]'::jsonb, now()),
  ('SY010', '["/api/bop/st/accounts", "/api/bop/st/files", "/api/bop/st/oauth/callback", "/api/bop/st/oauth/start"]'::jsonb, '["st_drive_accounts"]'::jsonb, now()),
  ('SY011', '["/api/bop/sys/roles", "/api/bop/sys/users"]'::jsonb, '["bop_roles", "bop_user_roles"]'::jsonb, now()),
  ('SY012', '["/api/bop/access-audit"]'::jsonb, '["bop_change_log", "bop_sessions", "bop_user_activity"]'::jsonb, now()),
  ('SY013', '["/api/bop/sys/counters"]'::jsonb, '["bop_counter"]'::jsonb, now()),
  ('SY014', '["/api/bop/access-audit"]'::jsonb, '["bop_change_log", "bop_sessions", "bop_user_activity"]'::jsonb, now()),
  ('SY015', '["/api/bop/sys/email/reset-link", "/api/bop/sys/roles", "/api/bop/sys/users", "/api/bop/sys/users/invite"]'::jsonb, '["bop_email_log", "bop_roles", "bop_user_profiles", "bop_user_roles"]'::jsonb, now()),
  ('SY016', '["/api/bop/access-audit"]'::jsonb, '["bop_change_log", "bop_sessions", "bop_user_activity"]'::jsonb, now()),
  ('SY017', '["/api/bop/sys/settings"]'::jsonb, '["bop_objects", "bop_settings"]'::jsonb, now()),
  ('SY018', '["/api/bop/sys/modules", "/api/bop/sys/screens"]'::jsonb, '["bop_modules", "bop_screens"]'::jsonb, now()),
  ('SY019', '["/api/bop/sys/screens"]'::jsonb, '["bop_screens"]'::jsonb, now()),
  ('SY020', '["/api/bop/sys/access-requests", "/api/bop/sys/roles"]'::jsonb, '["bop_change_log", "bop_roles"]'::jsonb, now()),
  ('SY021', '["/api/bop/sys/roles", "/api/bop/sys/users"]'::jsonb, '["bop_roles", "bop_user_roles"]'::jsonb, now()),
  ('SY022', '["/api/bop/sys/users"]'::jsonb, '["bop_roles", "bop_user_roles"]'::jsonb, now()),
  ('SY023', '["/api/bop/sys/users"]'::jsonb, '["bop_roles", "bop_user_roles"]'::jsonb, now()),
  ('SY024', '["/api/bop/sys/health", "/api/bop/sys/modules", "/api/bop/sys/screens"]'::jsonb, '["admin_notifications", "bop_modules", "bop_screens"]'::jsonb, now()),
  ('SY025', '["/api/bop/access-audit"]'::jsonb, '["bop_change_log", "bop_sessions", "bop_user_activity"]'::jsonb, now()),
  ('SY026', '["/api/bop/access-audit"]'::jsonb, '["bop_change_log", "bop_sessions", "bop_user_activity"]'::jsonb, now()),
  ('SY027', '["/api/bop/suim"]'::jsonb, '["bop_change_log", "bop_screen_roles", "bop_user_activity", "bop_user_profiles"]'::jsonb, now()),
  ('SY028', '["/api/bop/sys/dependencies", "/api/bop/sys/objects", "/api/bop/sys/objects/audit", "/api/bop/sys/objects/seed"]'::jsonb, '["bop_dependencies", "bop_objects", "bop_screens", "bop_settings"]'::jsonb, now()),
  ('SY029', '["/api/bop/sys/explorer"]'::jsonb, '["bop_objects", "bop_screens"]'::jsonb, now()),
  ('SY032', '["/api/bop/sys/locks"]'::jsonb, '["bop_change_log", "bop_object_locks"]'::jsonb, now()),
  ('SY033', '["/api/bop/sys/processes"]'::jsonb, '["bop_dependencies", "bop_documentation", "bop_objects", "bop_screens"]'::jsonb, now()),
  ('SY034', '["/api/bop/sys/docs"]'::jsonb, '["bop_documentation", "bop_objects", "bop_screens"]'::jsonb, now()),
  ('SY035', '["/api/bop/sys/explorer", "/api/bop/sys/flow-map"]'::jsonb, '["bop_dependencies", "bop_objects", "bop_screens"]'::jsonb, now()),
  ('SY036', '["/api/bop/comm/branding", "/api/bop/comm/styles"]'::jsonb, '["bop_comm_branding", "bop_comm_master_style"]'::jsonb, now()),
  ('SY037', '["/api/bop/comm/automation", "/api/bop/comm/templates"]'::jsonb, '["bop_comm_automation", "bop_comm_template"]'::jsonb, now()),
  ('SY038', '["/api/bop/comm/history", "/api/bop/sys/tenant-config"]'::jsonb, '["bop_comm_history", "bop_tenants"]'::jsonb, now()),
  ('SY039', '["/api/bop/comm/ai/action", "/api/bop/comm/compose/preview", "/api/bop/comm/templates"]'::jsonb, '["bop_ai_agents", "bop_comm_template"]'::jsonb, now()),
  ('SY040', '["/api/bop/support/requests"]'::jsonb, '["sup_messages", "sup_requests"]'::jsonb, now()),
  ('SY041', '["/api/bop/sys/dealer-applications"]'::jsonb, '["bop_tenants", "bop_user_profiles", "bop_user_tenants", "dos_dealer_applications"]'::jsonb, now()),
  ('SY042', '["/api/bop/sys/quality", "/api/bop/sys/quality/checks", "/api/bop/sys/quality/gate", "/api/bop/sys/quality/run"]'::jsonb, '["qa_check_runs", "qa_checks", "qa_scores"]'::jsonb, now()),
  ('SY043', '["/api/bop/sal/sell-leads/[id]/route", "/api/bop/sal/sell-leads/route"]'::jsonb, '["sell_lead_events", "sell_lead_images", "sell_leads"]'::jsonb, now()),
  ('SY050', '["/api/bop/sys/ff-preview", "/api/bop/sys/site-features", "/api/bop/sys/tenant-config"]'::jsonb, '["bop_tenants", "tenant_site_features"]'::jsonb, now()),
  ('SY051', '["/api/bop/sys/impl", "/api/bop/sys/impl/docs", "/api/bop/sys/impl/docs/download", "/api/bop/sys/impl/docs/preview", "/api/bop/sys/impl/verify"]'::jsonb, '["bop_documentation", "bop_objects", "bop_screen_roles", "bop_screens", "op_goals", "op_tasks", "sy_deliverables", "sy_phase_progress", "sy_phases", "sy_program_progress", "sy_programs", "sy_task_events", "sy_task_progress", "sy_tasks", "sy_templates"]'::jsonb, now()),
  ('SY053', '["/api/bop/sys/impl", "/api/bop/sys/impl/verify"]'::jsonb, '["bop_documentation", "bop_objects", "bop_screen_roles", "bop_screens", "op_goals", "op_tasks", "sy_deliverables", "sy_phase_progress", "sy_phases", "sy_program_progress", "sy_programs", "sy_task_events", "sy_task_progress", "sy_tasks", "sy_templates"]'::jsonb, now()),
  ('TR000', '["/api/bop/sal/cases"]'::jsonb, '["bop_cases"]'::jsonb, now()),
  ('TR001', '["/api/bop/sal/cases"]'::jsonb, '["bop_cases"]'::jsonb, now()),
  ('WK001', '["/api/bop/wrk/dashboard"]'::jsonb, '["wrk_apk_reminders", "wrk_approvals", "wrk_efficiency_metrics", "wrk_orders", "wrk_planning_slots"]'::jsonb, now()),
  ('WK002', '["/api/bop/wrk/orders", "/api/bop/wrk/plate-lookup", "/api/bop/wrk/technicians"]'::jsonb, '["ast_assets", "wrk_order_lines", "wrk_orders", "wrk_technicians"]'::jsonb, now()),
  ('WK003', '["/api/bop/wrk/planning"]'::jsonb, '["wrk_planning_slots", "wrk_technicians"]'::jsonb, now()),
  ('WK004', '["/api/bop/wrk/efficiency", "/api/bop/wrk/technicians"]'::jsonb, '["wrk_efficiency_metrics", "wrk_technicians"]'::jsonb, now()),
  ('WK005', '["/api/bop/wrk/inspections", "/api/bop/wrk/orders", "/api/bop/wrk/rates"]'::jsonb, '["wrk_inspections", "wrk_labour_rates", "wrk_order_lines", "wrk_orders"]'::jsonb, now()),
  ('WK006', '["/api/bop/wrk/apk-reminders"]'::jsonb, '["wrk_apk_reminders"]'::jsonb, now()),
  ('WK007', '["/api/bop/wrk/approvals", "/api/bop/wrk/orders"]'::jsonb, '["wrk_approvals", "wrk_order_lines", "wrk_orders"]'::jsonb, now()),
  ('WK008', '["/api/bop/wrk/status"]'::jsonb, '["wrk_orders"]'::jsonb, now()),
  ('WK009', '["/api/bop/wrk/briefing"]'::jsonb, '["wrk_apk_reminders", "wrk_orders", "wrk_planning_slots", "wrk_technicians"]'::jsonb, now()),
  ('WK010', '["/api/bop/wrk/recommendations"]'::jsonb, '["wrk_apk_reminders", "wrk_efficiency_metrics", "wrk_orders", "wrk_planning_slots", "wrk_technicians"]'::jsonb, now()),
  ('WK011', '["/api/bop/wrk/rates"]'::jsonb, '["wrk_labour_rates"]'::jsonb, now()),
  ('WK012', '["/api/bop/wrk/packages"]'::jsonb, '["wrk_service_packages"]'::jsonb, now()),
  ('WK013', '["/api/bop/wrk/autoflex", "/api/bop/wrk/autoflex/logs"]'::jsonb, '["ast_assets", "crm_leads", "shp_products", "wrk_autoflex_config", "wrk_autoflex_sync_logs", "wrk_orders"]'::jsonb, now()),
  ('WR001', '["/api/bop/user/prefs"]'::jsonb, '["bop_user_prefs"]'::jsonb, now()),
  ('AI002', '[]'::jsonb, '[]'::jsonb, now()),
  ('AS003', '[]'::jsonb, '[]'::jsonb, now()),
  ('AS004', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO000', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO001', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO002', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO003', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO004', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO005', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO006', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO007', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO008', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO009', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO010', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO011', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO012', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO013', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO014', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO015', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO016', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO017', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO018', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO019', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO020', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO021', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO022', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO023', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO024', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO025', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO026', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO027', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO028', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO029', '[]'::jsonb, '[]'::jsonb, now()),
  ('BO030', '[]'::jsonb, '[]'::jsonb, now()),
  ('CM001', '[]'::jsonb, '[]'::jsonb, now()),
  ('CR000', '[]'::jsonb, '[]'::jsonb, now()),
  ('DB004', '[]'::jsonb, '[]'::jsonb, now()),
  ('DB006', '[]'::jsonb, '[]'::jsonb, now()),
  ('DB007', '[]'::jsonb, '[]'::jsonb, now()),
  ('DB008', '[]'::jsonb, '[]'::jsonb, now()),
  ('FI000', '[]'::jsonb, '[]'::jsonb, now()),
  ('FI005', '[]'::jsonb, '[]'::jsonb, now()),
  ('FI006', '[]'::jsonb, '[]'::jsonb, now()),
  ('FI009', '[]'::jsonb, '[]'::jsonb, now()),
  ('FI013', '[]'::jsonb, '[]'::jsonb, now()),
  ('FI014', '[]'::jsonb, '[]'::jsonb, now()),
  ('IN000', '[]'::jsonb, '[]'::jsonb, now()),
  ('IN004', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK000', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK001', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK002', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK003', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK005', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK010', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK011', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK012', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK013', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK014', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK015', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK016', '[]'::jsonb, '[]'::jsonb, now()),
  ('MK017', '[]'::jsonb, '[]'::jsonb, now()),
  ('OP000', '[]'::jsonb, '[]'::jsonb, now()),
  ('OP003', '[]'::jsonb, '[]'::jsonb, now()),
  ('OP004', '[]'::jsonb, '[]'::jsonb, now()),
  ('OP005', '[]'::jsonb, '[]'::jsonb, now()),
  ('OP006', '[]'::jsonb, '[]'::jsonb, now()),
  ('OP007', '[]'::jsonb, '[]'::jsonb, now()),
  ('OP008', '[]'::jsonb, '[]'::jsonb, now()),
  ('PB000', '[]'::jsonb, '[]'::jsonb, now()),
  ('PB001', '[]'::jsonb, '[]'::jsonb, now()),
  ('PB002', '[]'::jsonb, '[]'::jsonb, now()),
  ('SA000', '[]'::jsonb, '[]'::jsonb, now()),
  ('SA005', '[]'::jsonb, '[]'::jsonb, now()),
  ('SA006', '[]'::jsonb, '[]'::jsonb, now()),
  ('SA008', '[]'::jsonb, '[]'::jsonb, now()),
  ('SA012', '[]'::jsonb, '[]'::jsonb, now()),
  ('SA020', '[]'::jsonb, '[]'::jsonb, now()),
  ('SA021', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH008', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH011', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH012', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH022', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH023', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH024', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH025', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH026', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH034', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH042', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH043', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH055', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH056', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH061', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH100', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH101', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH102', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH103', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH104', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH105', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH106', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH107', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH108', '[]'::jsonb, '[]'::jsonb, now()),
  ('SH110', '[]'::jsonb, '[]'::jsonb, now()),
  ('SY000', '[]'::jsonb, '[]'::jsonb, now()),
  ('SY009', '[]'::jsonb, '[]'::jsonb, now())
ON CONFLICT (screen_id) DO UPDATE SET
  db_tables = CASE
    WHEN jsonb_typeof(COALESCE(bop_screen_meta.db_tables, '[]'::jsonb)) != 'array'
      OR jsonb_array_length(COALESCE(bop_screen_meta.db_tables, '[]'::jsonb)) = 0
    THEN EXCLUDED.db_tables
    ELSE bop_screen_meta.db_tables
  END,
  api_routes = CASE
    WHEN jsonb_typeof(COALESCE(bop_screen_meta.api_routes, '[]'::jsonb)) != 'array'
      OR jsonb_array_length(COALESCE(bop_screen_meta.api_routes, '[]'::jsonb)) = 0
    THEN EXCLUDED.api_routes
    ELSE bop_screen_meta.api_routes
  END,
  updated_at = now();
