-- CI-T34..T39 — Attention Center / Intelligence tables
-- ci_attention_item: alerts generated by the rule engine
-- ci_attention_outcome: outcome tracking for actioned items

-- ═══════════════════════════════════════════════════════
--  ci_attention_item
-- ═══════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS ci_attention_item (
  id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id       integer NOT NULL DEFAULT current_setting('app.tenant_id', true)::integer,
  rule_id         text    NOT NULL,       -- e.g. 'payment_failure_spike', 'cvr_drop'
  severity        text    NOT NULL,       -- 'critical' | 'high' | 'medium' | 'opportunity'
  entity_type     text,                   -- 'product' | 'category' | 'supplier' | 'query' | null (site-level)
  entity_id       text,                   -- specific entity or null for site-level
  group_key       text,                   -- dedup key: rule_id + entity_type + coalesced entity
  group_count     integer NOT NULL DEFAULT 1,
  title           text    NOT NULL,
  detail          jsonb   NOT NULL DEFAULT '{}',
  evidence        jsonb   NOT NULL DEFAULT '{}',
  status          text    NOT NULL DEFAULT 'open',  -- 'open' | 'actioned' | 'dismissed' | 'expired'
  first_seen      timestamptz NOT NULL DEFAULT now(),
  last_seen       timestamptz NOT NULL DEFAULT now(),
  expires_at      timestamptz,
  actioned_by     text,
  actioned_at     timestamptz,
  outcome_note    text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, group_key, status)
);

CREATE INDEX IF NOT EXISTS idx_ci_attention_item_open
  ON ci_attention_item (tenant_id, status, severity)
  WHERE status = 'open';

ALTER TABLE ci_attention_item ENABLE ROW LEVEL SECURITY;
CREATE POLICY ci_attention_item_tenant_isolation ON ci_attention_item
  USING (tenant_id = current_setting('app.tenant_id', true)::integer)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::integer);

-- ═══════════════════════════════════════════════════════
--  bop_objects registration
-- ═══════════════════════════════════════════════════════

INSERT INTO bop_objects (object_id, type, module, name, status, description)
VALUES
  ('table:ci_attention_item', 'table', 'SHP', 'ci_attention_item', 'active',
   'Intelligence alerts — rule-generated attention items with dedup, grouping, expiry, and outcome tracking (L2, §8)')
ON CONFLICT (object_id) DO NOTHING;

INSERT INTO bop_dependencies (from_id, to_id, dep_type)
VALUES
  ('table:ci_attention_item', 'table:ci_daily_sales',   'reads'),
  ('table:ci_attention_item', 'table:ci_daily_product', 'reads'),
  ('table:ci_attention_item', 'table:ci_score_result',  'reads'),
  ('table:ci_attention_item', 'table:ci_benchmark',     'reads')
ON CONFLICT DO NOTHING;

-- ROLLBACK:
-- DROP TABLE IF EXISTS ci_attention_item;
-- DELETE FROM bop_objects WHERE object_id = 'table:ci_attention_item';
-- DELETE FROM bop_dependencies WHERE from_id = 'table:ci_attention_item';
