// AUTO-GENERATED from bop_screens DB — do not edit manually
// Regenerate: python3 /tmp/gen_registry.py on VPS

export type ScreenMeta = { id: string; title: string; mod: string; };

export const MOD_COLORS: Record<string, string> = {
  AIM: 'bg-indigo-100 text-indigo-700',
  ANL: 'bg-indigo-100 text-indigo-700',
  AST: 'bg-blue-100 text-blue-700',
  AUC: 'bg-amber-100 text-amber-700',
  BOP: 'bg-violet-100 text-violet-700',
  COM: 'bg-pink-100 text-pink-700',
  CRM: 'bg-purple-100 text-purple-700',
  FIN: 'bg-emerald-100 text-emerald-700',
  INV: 'bg-yellow-100 text-yellow-700',
  LOG: 'bg-lime-100 text-lime-700',
  MDM: 'bg-rose-100 text-rose-700',
  MKP: 'bg-orange-100 text-orange-700',
  MKT: 'bg-fuchsia-100 text-fuchsia-700',
  OPS: 'bg-cyan-100 text-cyan-700',
  PRT: 'bg-red-100 text-red-700',
  PUB: 'bg-blue-100 text-blue-700',
  SAL: 'bg-green-100 text-green-700',
  SYS: 'bg-slate-100 text-slate-700',
  DEV: 'bg-violet-100 text-violet-700',
  INT: 'bg-cyan-100 text-cyan-700',
  DAE: 'bg-teal-100 text-teal-700',
  WFL: 'bg-teal-100 text-teal-700',
  WRK: 'bg-sky-100 text-sky-700',
  SHP: 'bg-amber-100 text-amber-700',
  DBA: 'bg-stone-100 text-stone-700',
};

export const SCREEN_REGISTRY: Record<string, ScreenMeta> = {
  '/console/ai/command': { id: 'AI001', title: 'AI Command Center', mod: 'AIM' },
  '/console/ai/tools': { id: 'AI002', title: 'Tool Registry', mod: 'AIM' },
  '/console/ai/prompts': { id: 'AI003', title: 'Prompt Manager', mod: 'AIM' },
  '/console/ai/audit': { id: 'AI004', title: 'AI Action Audit', mod: 'AIM' },
  '/console/ai/models': { id: 'AI005', title: 'Model Configuration', mod: 'AIM' },
  '/console/anl/exec-dashboard': { id: 'AN001', title: 'Exec Dashboard', mod: 'ANL' },
  '/console/an/funnel': { id: 'AN002', title: 'Conversion Funnel', mod: 'ANL' },
  '/console/an/sessions-intel': { id: 'AN003', title: 'Session Intelligence', mod: 'ANL' },
  '/console/an/traffic': { id: 'AN004', title: 'Traffic & Acquisition', mod: 'ANL' },
  '/console/an/listing-perf': { id: 'AN005', title: 'Listing Performance', mod: 'ANL' },
  '/console/an/monitor': { id: 'AN006', title: 'Quality Monitor', mod: 'ANL' },
  '/console/ast/inventory': { id: 'AS001', title: 'Inventory', mod: 'AST' },
  '/console/ast/inventory/[id]': { id: 'AS002', title: 'Vehicle 360', mod: 'AST' },
  '/console/inventory/lifecycle': { id: 'AS003', title: 'Lifecycle Tracker', mod: 'AST' },
  '/console/inventory/costs': { id: 'AS004', title: 'Cost Tracker', mod: 'AST' },
  '/console/mkp/auctions/[id]': { id: 'AU002', title: 'Auction Detail', mod: 'AUC' },
  '/console/mkp/auctions/[id]/bidding': { id: 'AU004', title: 'Bidding Console', mod: 'AUC' },
  '/menu/bop': { id: 'BO000', title: 'BOP Menu', mod: 'BOP' },
  '/console/bop/dashboard': { id: 'BO001', title: 'Dashboard', mod: 'BOP' },
  '/console/anl/overview': { id: 'BO002', title: 'Analytics', mod: 'BOP' },
  '/menu/analytics/live': { id: 'BO003', title: 'Live', mod: 'BOP' },
  '/menu/analytics/listings': { id: 'BO004', title: 'Listings', mod: 'BOP' },
  '/menu/analytics/traffic': { id: 'BO005', title: 'Traffic', mod: 'BOP' },
  '/menu/analytics/audience': { id: 'BO006', title: 'Audience', mod: 'BOP' },
  '/menu/analytics/sessions': { id: 'BO007', title: 'Sessions', mod: 'BOP' },
  '/menu/analytics/events': { id: 'BO008', title: 'Events', mod: 'BOP' },
  '/menu/analytics/security': { id: 'BO009', title: 'Security', mod: 'BOP' },
  '/console/anl/realtime': { id: 'BO010', title: 'Realtime', mod: 'BOP' },
  '/console/anl/performance': { id: 'BO011', title: 'Performance', mod: 'BOP' },
  '/console/anl/top-viewed': { id: 'BO012', title: 'Top Viewed', mod: 'BOP' },
  '/console/anl/view-events': { id: 'BO013', title: 'View Events', mod: 'BOP' },
  '/console/anl/page-views': { id: 'BO014', title: 'Page Views', mod: 'BOP' },
  '/console/anl/visitors': { id: 'BO015', title: 'Visitors', mod: 'BOP' },
  '/console/anl/sources': { id: 'BO016', title: 'Sources', mod: 'BOP' },
  '/console/anl/top-pages': { id: 'BO017', title: 'Top Pages', mod: 'BOP' },
  '/console/anl/ga4': { id: 'BO018', title: 'GA4', mod: 'BOP' },
  '/console/anl/cloudflare': { id: 'BO019', title: 'Cloudflare', mod: 'BOP' },
  '/console/anl/cf-ga-compare': { id: 'BO020', title: 'CF&GA Compare', mod: 'BOP' },
  '/console/anl/locations': { id: 'BO021', title: 'Locations', mod: 'BOP' },
  '/console/anl/devices': { id: 'BO022', title: 'Devices', mod: 'BOP' },
  '/console/anl/sessions': { id: 'BO023', title: 'Sessions', mod: 'BOP' },
  '/console/anl/sessions-track': { id: 'BO024', title: 'Sessions Track', mod: 'BOP' },
  '/console/anl/form-submits': { id: 'BO025', title: 'Form Submits', mod: 'BOP' },
  '/console/anl/click-events': { id: 'BO026', title: 'Click Events', mod: 'BOP' },
  '/console/anl/click-analytics': { id: 'BO027', title: 'Click Analytics', mod: 'BOP' },
  '/console/anl/404-errors': { id: 'BO028', title: '404 Errors', mod: 'BOP' },
  '/console/anl/recent-activity': { id: 'BO029', title: 'Recent Activity', mod: 'BOP' },
  '/console/anl/security-events': { id: 'BO030', title: 'Security Events', mod: 'BOP' },
  '/console/anl/log-filters': { id: 'BO031', title: 'Log Filters', mod: 'BOP' },
  '/console/bop/inbox': { id: 'CM001', title: 'Inbox', mod: 'COM' },
  '/menu/crm': { id: 'CR000', title: 'CRM Menu', mod: 'CRM' },
  '/console/crm/leads': { id: 'CR001', title: 'Leads', mod: 'CRM' },
  '/console/crm/leads/[id]': { id: 'CR002', title: 'Lead Detail', mod: 'CRM' },
  '/console/crm/lead-stats': { id: 'CR003', title: 'Lead Statistics', mod: 'CRM' },
  '/console/crm/activities': { id: 'CR004', title: 'Activities', mod: 'CRM' },
  '/console/crm/customer': { id: 'CR005', title: 'Customers', mod: 'CRM' },
  '/console/crm/kanban': { id: 'CR006', title: 'Pipeline Kanban', mod: 'CRM' },
  '/console/crm/deals': { id: 'CR008', title: 'Deals', mod: 'CRM' },
  '/console/crm/deals/[id]': { id: 'CR009', title: 'Deal Workspace', mod: 'CRM' },
  '/console/crm/customer/[id]': { id: 'CR021', title: 'Customer 360', mod: 'CRM' },
  '/console/dae/cockpit': { id: 'DA001', title: 'Listings Cockpit', mod: 'DAE' },
  '/console/dae/profiles': { id: 'DA002', title: 'Search Profiles', mod: 'DAE' },
  '/console/dae/sources': { id: 'DA003', title: 'Source Config', mod: 'DAE' },
  '/console/dae/runs': { id: 'DA004', title: 'Run History', mod: 'DAE' },
  '/console/dae/pricing': { id: 'DA005', title: 'Price Intelligence', mod: 'DAE' },
  '/console/dev': { id: 'DV001', title: 'Dev Dashboard', mod: 'DEV' },
  '/console/dev/enhancements': { id: 'DV002', title: 'Enhancements', mod: 'DEV' },
  '/console/dev/queue': { id: 'DV003', title: 'Production Queue', mod: 'DEV' },
  '/console/dev/commits': { id: 'DV004', title: 'Commits', mod: 'DEV' },
  '/console/dev/definition-audit': { id: 'DV007', title: 'Definition Audit', mod: 'DEV' },
  '/console/dev/auth-smtp-audit': { id: 'DV008', title: 'Auth & SMTP Audit', mod: 'DEV' },
  '/menu/finance': { id: 'FI000', title: 'Finance Menu', mod: 'FIN' },
  '/console/fin/invoices': { id: 'FI001', title: 'BTW Quick Calc', mod: 'FIN' },
  '/console/fin/payments': { id: 'FI002', title: 'Payment Tracking', mod: 'FIN' },
  '/console/fin/expenses': { id: 'FI005', title: 'Kosten', mod: 'FIN' },
  '/console/fin/customers': { id: 'FI006', title: 'Klanten', mod: 'FIN' },
  '/console/fin/pnl': { id: 'FI009', title: 'Winst & Verlies', mod: 'FIN' },
  '/console/fin/invoices/[id]': { id: 'FI011', title: 'Invoice Detail', mod: 'FIN' },
  '/console/fin/ap': { id: 'FI012', title: 'Supplier Invoices AP', mod: 'FIN' },
  '/menu/inventory': { id: 'IN000', title: 'Inventory Menu', mod: 'INV' },
  '/console/ast/catalog': { id: 'IN001', title: 'Catalog Overview', mod: 'INV' },
  '/console/ast/brands': { id: 'IN002', title: 'Brands', mod: 'INV' },
  '/console/ast/categories': { id: 'IN003', title: 'Listing Categories', mod: 'INV' },
  '/console/ast/suppliers': { id: 'IN004', title: 'Suppliers', mod: 'INV' },
  '/console/ast/structures': { id: 'IN005', title: 'Publish Structures', mod: 'INV' },
  '/console/ast/models': { id: 'IN006', title: 'Model Catalog', mod: 'INV' },
  '/console/int/connectors': { id: 'IT001', title: 'Connector Manager', mod: 'INT' },
  '/console/int/log': { id: 'IT002', title: 'Integration Log', mod: 'INT' },
  '/console/int/flows': { id: 'IT003', title: 'Flow Manager', mod: 'INT' },
  '/console/int/queue': { id: 'IT004', title: 'Message Queue', mod: 'INT' },
  '/console/int/mappings': { id: 'IT005', title: 'Field Mapping Studio', mod: 'INT' },
  '/console/int/lookup': { id: 'IT006', title: 'Lookup Code Translation', mod: 'INT' },
  '/console/int/publish': { id: 'IT007', title: 'Publish Jobs', mod: 'INT' },
  '/console/int/webhook-events': { id: 'IT008', title: 'Webhook Events', mod: 'INT' },
  '/console/mdm/partners': { id: 'MD001', title: 'Business Partners', mod: 'MDM' },
  '/console/mdm/partners/[id]': { id: 'MD002', title: 'Partner Detail', mod: 'MDM' },
  '/console/mdm/taxonomy': { id: 'MD003', title: 'Vehicle Taxonomy', mod: 'MDM' },
  '/menu/intelligence': { id: 'MK000', title: 'Intelligence Menu', mod: 'MKT' },
  '/console/mkt/market': { id: 'MK002', title: 'Market Evaluation', mod: 'MKT' },
  '/console/mkt/competitors': { id: 'MK003', title: 'Competitor Activity', mod: 'MKT' },
  '/console/mkt/brands': { id: 'MK004', title: 'Brand Tracker', mod: 'MKT' },
  '/console/mkt/listings': { id: 'MK005', title: 'Listing Intelligence', mod: 'MKT' },
  '/console/mkt/studio': { id: 'MK007', title: 'AI Vehicle Studio', mod: 'MKT' },
  '/console/mkt/studio/preset-backgrounds': { id: 'MK008', title: 'Preset Backgrounds', mod: 'MKT' },
  '/console/mkt/banner-terms': { id: 'MK009', title: 'USP Banner Terms', mod: 'MKT' },
  '/console/mkt/corridors': { id: 'MK010', title: 'Corridors', mod: 'MKT' },
  '/console/mkt/countries': { id: 'MK011', title: 'Countries', mod: 'MKT' },
  '/console/mkt/prices': { id: 'MK012', title: 'Market Prices', mod: 'MKT' },
  '/console/mkt/distributions': { id: 'MK013', title: 'Distributions', mod: 'MKT' },
  '/console/mkt/opportunities': { id: 'MK014', title: 'Opportunities', mod: 'MKT' },
  '/console/mkt/trades': { id: 'MK015', title: 'Trade Log', mod: 'MKT' },
  '/console/mkt/trading': { id: 'MK016', title: 'Trading Dashboard', mod: 'MKT' },
  '/console/mkt/dealer-feed': { id: 'MK017', title: 'Dealer Feed', mod: 'MKT' },
  '/console/mkp/listings': { id: 'MP001', title: 'Listing Manager', mod: 'MKP' },
  '/console/mkp/analytics': { id: 'MP002', title: 'Channel Analytics', mod: 'MKP' },
  '/console/mkp/listings/[id]': { id: 'MP003', title: 'Listing Detail', mod: 'MKP' },
  '/console/mkp/publish': { id: 'MP004', title: 'Channel Publisher', mod: 'MKP' },
  '/console/mkp/layout-manager': { id: 'MP005', title: 'Layout Manager', mod: 'MKP' },
  '/menu/operations': { id: 'OP000', title: 'Operations Menu', mod: 'OPS' },
  '/console/ops/tasks': { id: 'OP001', title: 'Operations Cockpit', mod: 'OPS' },
  '/console/ops/goals': { id: 'OP002', title: 'Strategy Cockpit', mod: 'OPS' },
  '/console/ops/profit-lab': { id: 'OP003', title: 'Profit Lab', mod: 'OPS' },
  '/console/ops/qr': { id: 'OP004', title: 'QR Tool', mod: 'OPS' },
  '/console/ops/flyer': { id: 'OP005', title: 'Flyer Builder', mod: 'OPS' },
  '/console/ops/image-renamer': { id: 'OP006', title: 'Image Renamer', mod: 'OPS' },
  '/console/ops/watermark': { id: 'OP007', title: 'Watermark', mod: 'OPS' },
  '/console/ops/tasks/grid': { id: 'OP009', title: 'Task Grid', mod: 'OPS' },
  '/console/ops/tasks/kanban': { id: 'OP010', title: 'Kanban Board', mod: 'OPS' },
  '/console/ops/tasks/calendar': { id: 'OP011', title: 'Calendar View', mod: 'OPS' },
  '/console/ops/tasks/analytics': { id: 'OP013', title: 'Task Analytics', mod: 'OPS' },
  '/console/ops/tasks/timeline': { id: 'OP014', title: 'Task Timeline', mod: 'OPS' },
  '/console/ops/goals/scorecard': { id: 'OP015', title: 'Entity Scorecard', mod: 'OPS' },
  '/menu/publishing': { id: 'PB000', title: 'Publishing Menu', mod: 'PUB' },
  '/console/pub/overview': { id: 'PB001', title: 'My Publications', mod: 'PUB' },
  '/console/pub/queue': { id: 'PB002', title: 'Publish Queue', mod: 'PUB' },
  '/menu/sales': { id: 'SA000', title: 'Sales Menu', mod: 'SAL' },
  '/console/sal/quotations': { id: 'SA001', title: 'Quotations', mod: 'SAL' },
  '/console/sal/quotations/[id]': { id: 'SA002', title: 'Quotation Detail', mod: 'SAL' },
  '/console/sal/payments': { id: 'SA005', title: 'Payments', mod: 'SAL' },
  '/console/sal/reviews': { id: 'SA006', title: 'Reviews', mod: 'SAL' },
  '/console/sal/appointments': { id: 'SA007', title: 'Appointments', mod: 'SAL' },
  '/console/sal/rentals': { id: 'SA008', title: 'Rentals', mod: 'SAL' },
  '/console/sal/orders': { id: 'SA009', title: 'Orders', mod: 'SAL' },
  '/console/sal/orders/[id]': { id: 'SA010', title: 'Order Detail', mod: 'SAL' },
  '/console/sal/dashboard': { id: 'SA011', title: 'Sales Dashboard', mod: 'SAL' },
  '/console/sal/margin': { id: 'SA012', title: 'Margin Calculator', mod: 'SAL' },
  '/console/sal/sell-leads': { id: 'SA013', title: 'Sell Leads', mod: 'SAL' },
  '/console/sal/sell-leads/[id]': { id: 'SA014', title: 'Sell Lead Detail', mod: 'SAL' },
  '/console/sal/buyer-inbox': { id: 'SA015', title: 'Buyer Inbox', mod: 'SAL' },
  '/console/sal/buyer-inbox/[id]': { id: 'SA016', title: 'Buyer Thread', mod: 'SAL' },
  '/console/sal/inquiries': { id: 'SA017', title: 'Buyer Inquiries', mod: 'SAL' },
  '/console/sal/inquiries/[id]': { id: 'SA018', title: 'Inquiry Detail', mod: 'SAL' },
  '/console/shp': { id: 'SH000', title: 'Shop', mod: 'SHP' },
  '/console/shp/products': { id: 'SH001', title: 'Product Catalog', mod: 'SHP' },
  '/console/shp/products/[id]': { id: 'SH002', title: 'Product Detail', mod: 'SHP' },
  '/console/shp/orders': { id: 'SH003', title: 'Shop Orders', mod: 'SHP' },
  '/console/shp/orders/[id]': { id: 'SH004', title: 'Order Detail', mod: 'SHP' },
  '/console/shp/inventory': { id: 'SH005', title: 'Stock Management', mod: 'SHP' },
  '/console/shp/customers': { id: 'SH006', title: 'Shop Customers', mod: 'SHP' },
  '/console/shp/brands': { id: 'SH007', title: 'Brands', mod: 'SHP' },
  '/console/shp/settings': { id: 'SH008', title: 'Shop Settings', mod: 'SHP' },
  '/console/shp/dashboard': { id: 'SH009', title: 'Shop Dashboard', mod: 'SHP' },
  '/console/shp/documents': { id: 'SH010', title: 'Documents', mod: 'SHP' },
  '/console/shp/collections': { id: 'SH011', title: 'Collections', mod: 'SHP' },
  '/console/shp/import': { id: 'SH012', title: 'Import Wizard', mod: 'SHP' },
  '/console/shp/fulfil/orders': { id: 'SH020', title: 'Order List', mod: 'SHP' },
  '/console/shp/fulfil/orders/[id]': { id: 'SH021', title: 'Order Workspace', mod: 'SHP' },
  '/console/shp/fulfil/allocations': { id: 'SH022', title: 'Allocation Queue', mod: 'SHP' },
  '/console/shp/fulfil/pick': { id: 'SH023', title: 'Pick Lists', mod: 'SHP' },
  '/console/shp/fulfil/pack': { id: 'SH024', title: 'Pack Station', mod: 'SHP' },
  '/console/shp/fulfil/shipments': { id: 'SH025', title: 'Shipments', mod: 'SHP' },
  '/console/shp/fulfil/backorders': { id: 'SH026', title: 'Backorders', mod: 'SHP' },
  '/console/shp/fulfil/picking': { id: 'SH080', title: 'Picking Queue', mod: 'SHP' },
  '/console/shp/fulfil/packing': { id: 'SH081', title: 'Packing Queue', mod: 'SHP' },
  '/console/shp/fulfil/shipping': { id: 'SH082', title: 'Shipping Management', mod: 'SHP' },
  '/console/shp/fulfil/dropship': { id: 'SH083', title: 'Dropship Dispatch', mod: 'SHP' },
  '/console/shp/finance/vat': { id: 'SH030', title: 'VAT & OSS', mod: 'SHP' },
  '/console/shp/finance/settlements': { id: 'SH031', title: 'Settlements', mod: 'SHP' },
  '/console/shp/finance/invoices': { id: 'SH032', title: 'Invoices', mod: 'SHP' },
  '/console/shp/finance/credit-notes': { id: 'SH033', title: 'Credit Notes', mod: 'SHP' },
  '/console/shp/finance/payments': { id: 'SH034', title: 'Payments & Refunds', mod: 'SHP' },
  '/console/shp/finance/margin': { id: 'SH035', title: 'Margin Report', mod: 'SHP' },
  '/console/shp/aftersales/returns': { id: 'SH040', title: 'Returns (RMA)', mod: 'SHP' },
  '/console/shp/aftersales/claims': { id: 'SH041', title: 'Claims', mod: 'SHP' },
  '/console/shp/aftersales/damage': { id: 'SH042', title: 'Carrier Damage', mod: 'SHP' },
  '/console/shp/aftersales/replacements': { id: 'SH043', title: 'Replacements', mod: 'SHP' },
  '/console/shp/aftersales/refunds': { id: 'SH084', title: 'Refunds', mod: 'SHP' },
  '/console/shp/aftersales/inspections': { id: 'SH085', title: 'Return Inspections', mod: 'SHP' },
  '/console/shp/procure/suppliers': { id: 'SH050', title: 'Suppliers', mod: 'SHP' },
  '/console/shp/procure/catalog': { id: 'SH051', title: 'Supplier Catalog', mod: 'SHP' },
  '/console/shp/procure/po': { id: 'SH052', title: 'Purchase Orders', mod: 'SHP' },
  '/console/shp/procure/count': { id: 'SH053', title: 'Cycle Count', mod: 'SHP' },
  '/console/shp/procure/cycle-count': { id: 'SH053', title: 'Cycle Count', mod: 'SHP' },
  '/console/shp/procure/receive': { id: 'SH054', title: 'Goods-In Receipt', mod: 'SHP' },
  '/console/shp/procure/goods-in': { id: 'SH054', title: 'Goods-In Receipt', mod: 'SHP' },
  '/console/shp/procure/dropship': { id: 'SH055', title: 'Dropship Queue', mod: 'SHP' },
  '/console/shp/procure/demand': { id: 'SH056', title: 'Demand Planning', mod: 'SHP' },
  '/console/shp/procure/cockpit': { id: 'SH057', title: 'Procurement Cockpit', mod: 'SHP' },
  '/console/shp/compliance/registrations': { id: 'SH060', title: 'Compliance', mod: 'SHP' },
  '/console/shp/compliance/hazards': { id: 'SH061', title: 'Hazard Profiles', mod: 'SHP' },
  '/console/shp/compliance/gdpr': { id: 'SH062', title: 'GDPR Admin', mod: 'SHP' },
  '/console/shp/compliance/fees': { id: 'SH086', title: 'Compliance Fees', mod: 'SHP' },
  '/console/shp/monitor': { id: 'SH070', title: 'Shop Monitor', mod: 'SHP' },
  '/menu/system': { id: 'SY000', title: 'System Menu', mod: 'SYS' },
  '/console/sys/users': { id: 'SY001', title: 'Users', mod: 'SYS' },
  '/console/sys/roles': { id: 'SY002', title: 'Role Catalog', mod: 'SYS' },
  '/console/sys/tenants': { id: 'SY003', title: 'Tenant Management', mod: 'SYS' },
  '/console/sys/settings': { id: 'SY004', title: 'System Settings', mod: 'SYS' },
  '/console/sys/health': { id: 'SY005', title: 'System Health', mod: 'SYS' },
  '/console/sys/overview': { id: 'SY006', title: 'Systems', mod: 'SYS' },
  '/console/sys/jobs': { id: 'SY007', title: 'DB Jobs', mod: 'SYS' },
  '/console/sys/dashboard': { id: 'SY008', title: 'Admin Dashboard', mod: 'SYS' },
  '/console/sys/mcp': { id: 'SY009', title: 'MCP', mod: 'SYS' },
  '/console/sys/drive': { id: 'SY010', title: 'Google Drive Storage', mod: 'SYS' },
  '/console/sys/rbac': { id: 'SY011', title: 'RBAC Roles', mod: 'SYS' },
  '/console/sys/audit': { id: 'SY012', title: 'Audit Log', mod: 'SYS' },
  '/console/sys/counters': { id: 'SY013', title: 'Counters', mod: 'SYS' },
  '/console/sys/handoff': { id: 'SY014', title: 'Handoff Doc', mod: 'SYS' },
  '/console/sys/user-cockpit': { id: 'SY015', title: 'User Cockpit', mod: 'SYS' },
  '/console/sys/access-audit': { id: 'SY016', title: 'Access Audit', mod: 'SYS' },
  '/console/sys/imap': { id: 'SY017', title: 'IMAP Config', mod: 'SYS' },
  '/console/sys/modules': { id: 'SY018', title: 'Module Manager', mod: 'SYS' },
  '/console/sys/menu-config': { id: 'SY019', title: 'Menu Config', mod: 'SYS' },
  '/console/sys/access-request': { id: 'SY020', title: 'Access Request Workflow', mod: 'SYS' },
  '/console/sys/sod': { id: 'SY021', title: 'SoD Conflict Report', mod: 'SYS' },
  '/console/sys/recertification': { id: 'SY022', title: 'Access Recertification', mod: 'SYS' },
  '/console/sys/bulk-users': { id: 'SY023', title: 'Bulk User Operations', mod: 'SYS' },
  '/console/sys/screen-explorer': { id: 'SY024', title: 'Screen Explorer', mod: 'SYS' },
  '/console/sys/security': { id: 'SY025', title: 'Security Events', mod: 'SYS' },
  '/console/sys/sessions': { id: 'SY026', title: 'Session Manager', mod: 'SYS' },
  '/console/sys/suim': { id: 'SY027', title: 'SUIM Role Browser', mod: 'SYS' },
  '/console/sys/object-explorer': { id: 'SY028', title: 'Object Explorer', mod: 'SYS' },
  '/console/sys/data-explorer': { id: 'SY029', title: 'Data Explorer', mod: 'SYS' },
  '/console/sys/locks': { id: 'SY032', title: 'Lock Monitor', mod: 'SYS' },
  '/console/sys/processes': { id: 'SY033', title: 'Process Library', mod: 'SYS' },
  '/console/sys/docs': { id: 'SY034', title: 'Documentation Browser', mod: 'SYS' },
  '/console/sys/flow-map': { id: 'SY035', title: 'Flow Map', mod: 'SYS' },
  '/console/sys/comm/styles': { id: 'SY036', title: 'Email Style Library', mod: 'SYS' },
  '/console/sys/comm/automation': { id: 'SY037', title: 'Automation Engine', mod: 'SYS' },
  '/console/sys/comm/log': { id: 'SY038', title: 'Communication Log', mod: 'SYS' },
  '/console/sys/comm/templates': { id: 'SY039', title: 'Template Studio', mod: 'SYS' },
  '/console/sys/support': { id: 'SY040', title: 'Support Center', mod: 'SYS' },
  '/console/sys/dealer-applications': { id: 'SY041', title: 'Dealer Applications', mod: 'SYS' },
  '/console/sys/quality': { id: 'SY042', title: 'Quality Inspector', mod: 'SYS' },
  '/console/sys/tfe-flow': { id: 'SY043', title: 'TFE Flow Viewer', mod: 'SYS' },
  '/console/sys/sy050': { id: 'SY050', title: 'Feature Matrix', mod: 'SYS' },
  '/console/sys/impl': { id: 'SY051', title: 'Implementation Cockpit', mod: 'SYS' },
  '/console/sys/impl/tasks': { id: 'SY053', title: 'Task Detail', mod: 'SYS' },
  '/console/sal/cases': { id: 'TR000', title: 'Cases', mod: 'SAL' },
  '/console/sal/cases/[id]': { id: 'TR001', title: 'Case Detail', mod: 'SAL' },
  '/console/config/content-engine': { id: 'CE001', title: 'Field Catalog', mod: 'SYS' },
  '/console/config/content-engine/templates': { id: 'CE002', title: 'Template Manager', mod: 'SYS' },
  '/console/config/content-engine/templates/[id]': { id: 'CE003', title: 'Template Detail', mod: 'SYS' },
  '/console/dev/deployments': { id: 'DV005', title: 'Deployments', mod: 'DEV' },
  '/console/dev/releases': { id: 'DV006', title: 'Releases', mod: 'DEV' },
  '/console/fin/assistant': { id: 'FI013', title: 'Finance Assistant', mod: 'FIN' },
  '/console/fin/scanner': { id: 'FI014', title: 'Document Scanner', mod: 'FIN' },
  '/console/master-data/equipment': { id: 'MD004', title: 'Equipment', mod: 'MDM' },
  '/console/mkp/auctions': { id: 'AU001', title: 'Auctions', mod: 'AUC' },
  '/console/mkt/campaigns': { id: 'MK018', title: 'Campaigns', mod: 'MKT' },
  '/console/mkt/dealer-reserve': { id: 'MK019', title: 'Dealer Reserve', mod: 'MKT' },
  '/console/mkt/overview': { id: 'MK001', title: 'Market Overview', mod: 'MKT' },
  '/console/mkt/studio/new': { id: 'MK020', title: 'New Studio Job', mod: 'MKT' },
  '/console/my-work': { id: 'WR001', title: 'My Work', mod: 'WRK' },
  '/console/ops/goals/dashboard': { id: 'OP016', title: 'Goals Dashboard', mod: 'OPS' },
  '/console/ops/goals/ledger': { id: 'OP017', title: 'Goals Ledger', mod: 'OPS' },
  '/console/ops/photo-enhance': { id: 'OP008', title: 'Photo Enhance', mod: 'OPS' },
  '/console/ops/field-intel': { id: 'OP018', title: 'Fair Scout', mod: 'OPS' },
  '/console/sal/handovers': { id: 'SA019', title: 'Handovers', mod: 'SAL' },
  '/console/sal/quotes': { id: 'SA020', title: 'Quotes', mod: 'SAL' },
  '/console/sal/quote-submissions': { id: 'SA021', title: 'Quote Submissions', mod: 'SAL' },
  '/console/sal/surveys': { id: 'SA022', title: 'Surveys', mod: 'SAL' },
  '/console/sal/warranties': { id: 'SA023', title: 'Warranties', mod: 'SAL' },
  '/console/shp/control-tower': { id: 'SH071', title: 'Control Tower', mod: 'SHP' },
  '/console/shp/guide': { id: 'SH090', title: 'Shop Guide', mod: 'SHP' },
  '/console/shp/analytics/overview': { id: 'SH100', title: 'Overview', mod: 'SHP' },
  '/console/shp/analytics/funnel': { id: 'SH101', title: 'Funnel', mod: 'SHP' },
  '/console/shp/analytics/sales': { id: 'SH102', title: 'Sales', mod: 'SHP' },
  '/console/shp/analytics/products': { id: 'SH103', title: 'Products', mod: 'SHP' },
  '/console/shp/analytics/customers': { id: 'SH104', title: 'Customers', mod: 'SHP' },
  '/console/shp/analytics/traffic': { id: 'SH105', title: 'Traffic', mod: 'SHP' },
  '/console/shp/analytics/checkout': { id: 'SH106', title: 'Checkout', mod: 'SHP' },
  '/console/shp/analytics/inventory': { id: 'SH107', title: 'Inventory', mod: 'SHP' },
  '/console/shp/analytics/discovery': { id: 'SH108', title: 'Discovery', mod: 'SHP' },
  '/console/shp/analytics/attention': { id: 'SH109', title: 'Attention', mod: 'SHP' },
  '/console/shp/analytics/scoring': { id: 'SH110', title: 'Scoring', mod: 'SHP' },
  '/console/wrk/dashboard': { id: 'WK001', title: 'Workshop Dashboard', mod: 'WRK' },
  '/console/wrk/orders': { id: 'WK002', title: 'Work Orders', mod: 'WRK' },
  '/console/wrk/planning': { id: 'WK003', title: 'Planning Board', mod: 'WRK' },
  '/console/wrk/efficiency': { id: 'WK004', title: 'Efficiency KPI', mod: 'WRK' },
  '/console/wrk/inspections': { id: 'WK005', title: 'Inspection Checklist', mod: 'WRK' },
  '/console/wrk/apk-reminders': { id: 'WK006', title: 'APK Reminders', mod: 'WRK' },
  '/console/wrk/approvals': { id: 'WK007', title: 'Customer Approvals', mod: 'WRK' },
  '/console/wrk/status': { id: 'WK008', title: 'Customer Status', mod: 'WRK' },
  '/console/wrk/briefing': { id: 'WK009', title: 'Daily Briefing', mod: 'WRK' },
  '/console/wrk/recommendations': { id: 'WK010', title: 'Repair Recommendations', mod: 'WRK' },
  '/console/wrk/rates': { id: 'WK011', title: 'Labour Rates', mod: 'WRK' },
  '/console/wrk/packages': { id: 'WK012', title: 'Service Packages', mod: 'WRK' },
  '/console/wrk/dms-integration': { id: 'WK013', title: 'DMS Integration', mod: 'WRK' },
  '/console/dba': { id: 'DB001', title: 'Database Overview', mod: 'DBA' },
  '/console/dba/schema': { id: 'DB002', title: 'Schema Explorer', mod: 'DBA' },
  '/console/dba/data': { id: 'DB003', title: 'Table Data', mod: 'DBA' },
  '/console/dba/sql': { id: 'DB004', title: 'SQL Runner', mod: 'DBA' },
  '/console/dba/functions': { id: 'DB005', title: 'Functions & RPC', mod: 'DBA' },
  '/console/dba/actions': { id: 'DB006', title: 'Database Actions', mod: 'DBA' },
  '/console/dba/history': { id: 'DB007', title: 'Query History', mod: 'DBA' },
  '/console/dba/migrations': { id: 'DB008', title: 'Migrations', mod: 'DBA' },
};

export function getScreenMeta(pathname: string): ScreenMeta | null {
  if (SCREEN_REGISTRY[pathname]) return SCREEN_REGISTRY[pathname];
  const segments = pathname.split('/');
  while (segments.length > 2) {
    segments.pop();
    const parent = segments.join('/');
    if (SCREEN_REGISTRY[parent]) return SCREEN_REGISTRY[parent];
  }
  return null;
}
export const getScreen = getScreenMeta;
