-- Week 40 (2026-09-28 → 2026-10-05) documentation upserts
-- Generated by sync-week-enhancements-2026w40.mjs
-- Run with: bash /root/scripts/des-sql.sh --commit < scripts/_week40_docs_upsert.sql
--
-- Uses a temporary upsert function because bop_documentation has no
-- unique constraint on (target_type, target_id, doc_type, seq).

BEGIN;

CREATE OR REPLACE FUNCTION _tmp_doc_upsert(
  _target_type text, _target_id text, _doc_type text, _seq int,
  _title text, _body_md text, _module text, _related_screens text[]
) RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  _existing uuid;
  _ver int;
BEGIN
  SELECT doc_id, COALESCE(version, 1) INTO _existing, _ver
    FROM bop_documentation
   WHERE target_type = _target_type AND target_id = _target_id
     AND doc_type = _doc_type AND seq = _seq
   LIMIT 1;

  IF _existing IS NOT NULL THEN
    UPDATE bop_documentation SET
      title = _title, body_md = _body_md, status = 'active',
      owner = 'system', version = _ver + 1,
      module = _module, related_screens = _related_screens,
      updated_at = now()
    WHERE doc_id = _existing;
  ELSE
    INSERT INTO bop_documentation
      (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
    VALUES
      (_target_type, _target_id, _doc_type, _seq, _title, _body_md, 'active', 'system', 1, _module, _related_screens);
  END IF;
END $$;

-- SA017 — Buyer Inquiries (3 docs)
SELECT _tmp_doc_upsert('screen', 'SA017', 'overview', 0,
  'Buyer Inquiries — Inbox',
  '**Buyer Inquiries** (`SA017`) is the inbox for structured buyer questions submitted from desmobil listing pages. Route: `/console/sal/inquiries`.

Each inquiry carries question chips (intent tags), free-text, and contact details. The list shows a **Ref** column (DM-INQ-XXXXXXXX) as the first column in orange monospace font, computed from the inquiry UUID.

**Key columns:** Ref · Listing · Intent tags · Contact · Status · Received (dd-mm-yyyy HH:mm)

**Statuses:** `new` → `seen` → `replied` → `closed` (or `converted` via CRM lead promotion on SA018).

**API:** `GET /api/bop/sal/inquiries` — returns inquiry list with computed `ref_code` field.',
  'SAL', ARRAY['SA017']);

SELECT _tmp_doc_upsert('screen', 'SA017', 'reference', 1,
  'APIs & data',
  '- `GET /api/bop/sal/inquiries` — returns `dm_inquiries` rows with computed `ref_code` (DM-INQ-XXXXXXXX from UUID prefix)
- `ref_code` is computed at API level: `DM-INQ-` + first 8 chars of UUID uppercased
- Received date format: `dd-mm-yyyy HH:mm` (includes year)
- Filter param: `?status=new|seen|replied|closed|converted`
- Table: `dm_inquiries` — columns: id, listing_id, question_codes, intent_tags, free_text, contact_name, contact_email, status, locale, created_at',
  'SAL', ARRAY['SA017']);

SELECT _tmp_doc_upsert('screen', 'SA017', 'steps', 2,
  'Recent enhancements (Oct 2026)',
  '**DM-INQ Reference Code** (6bf9050) — Each inquiry now has a computed reference code `DM-INQ-XXXXXXXX` displayed as the first column in orange monospace. Computed from the inquiry UUID, not stored.

**Date Format Fix** (fc3d83d) — Received date column now shows full year: `dd-mm-yyyy HH:mm` instead of `dd-mm HH:mm`.',
  'SAL', ARRAY['SA017']);

-- SA018 — Buyer Inquiry Detail (2 docs)
SELECT _tmp_doc_upsert('screen', 'SA018', 'overview', 0,
  'Buyer Inquiry Detail',
  '**Buyer Inquiry Detail** (`SA018`) shows the full detail view for a single buyer inquiry. Route: `/console/sal/inquiries/[id]`.

The page title displays the **DM-INQ reference code** (DM-INQ-XXXXXXXX). The detail card shows:
- Question chips with intent tags (general, b2b, inspection, logistics, technical)
- Contact information (name, email)
- **Acquisition source** and **traffic channel** fields
- Free-text message
- Status machine with transitions (new → seen → replied → closed)
- CRM lead promotion action

**API:** `GET /api/bop/sal/inquiries/[id]` — single inquiry with ref_code, acquisition_source, traffic_channel.',
  'SAL', ARRAY['SA018']);

SELECT _tmp_doc_upsert('screen', 'SA018', 'steps', 1,
  'Recent enhancements (Oct 2026)',
  '**DM-INQ Reference Code** (6bf9050) — ref_code displayed in page title and listing card header.

**Acquisition & Traffic Fields** (6bf9050) — Now shows `acquisition_source` and `traffic_channel` on the detail card, giving visibility into where the inquiry originated.',
  'SAL', ARRAY['SA018']);

-- Platform — Branding (1 doc)
SELECT _tmp_doc_upsert('platform', 'platform-branding', 'overview', 0,
  '2E Terminal / Code Prompt — Brand Identity',
  '**Brand refresh (Oct 2026):** The BOP console and public site now use the **>_ des.systems** terminal-style logo concept.

**Elements:**
- Logo: `>_` prompt in brand blue (#3B82F6) + `des` in dark + `.systems` with blue dot
- Font: **IBM Plex Mono** (loaded via `next/font/google`, CSS variable `--font-ibm-plex-mono`)
- Tagline: `BUSINESS OPERATING PLATFORM` in tracked uppercase
- Favicon: navy rounded square with blue `>_` prompt (SVG at `app/icon.svg`)
- Dark/light theme support on all logo elements

**Files changed:**
- `components/Shell.tsx` — console header logo
- `components/nav.tsx` — public site navigation logo
- `components/footer.tsx` — public site footer logo
- `app/icon.svg` — favicon
- `app/layout.tsx` — IBM Plex Mono font registration',
  NULL, NULL);

-- BO018 — GA4 Sync (1 doc)
SELECT _tmp_doc_upsert('screen', 'BO018', 'steps', 2,
  'GA4 Sync Endpoint (Oct 2026)',
  '**New endpoint:** `POST /api/admin/ga4/sync`

Fetches Google Analytics 4 Data API for all tenants with `ga4_property_id` configured in `bop_tenants`, writes daily metrics to the `ga4_analytics` table.

**Auth:** `x-studio-worker-secret` header
**Params:** `?tenant_id=N` (optional, sync single tenant), `?days=30` (lookback window)
**Mechanism:** JWT auth via Google service account (`lib/ga4-data.ts`), fetches GA4 runReport with dimensions: date, sessionDefaultChannelGrouping; metrics: sessions, activeUsers, screenPageViews, conversions, totalRevenue.

**File:** `app/api/admin/ga4/sync/route.ts` + `lib/ga4-data.ts`',
  'BOP', ARRAY['BO018']);

-- BO019 — Cloudflare Sync (1 doc)
SELECT _tmp_doc_upsert('screen', 'BO019', 'steps', 2,
  'Cloudflare Analytics Sync Endpoint (Oct 2026)',
  '**New endpoint:** `POST /api/admin/cloudflare/sync`

Fetches Cloudflare GraphQL Analytics API (`httpRequests1dGroups`) for all tenants with `cloudflare_zone_id` configured in `bop_tenants`, upserts daily metrics into `cloudflare_analytics`.

**Auth:** `x-studio-worker-secret` header
**Params:** `?tenant_id=N` (optional), `?days=30` (lookback)
**Metrics:** requests, pageViews, threats, bandwidth, unique visitors, country breakdown, status code breakdown, content type breakdown.

**File:** `app/api/admin/cloudflare/sync/route.ts`',
  'BOP', ARRAY['BO019']);

-- SY043 — TFE Flow Viewer (2 docs)
SELECT _tmp_doc_upsert('screen', 'SY043', 'overview', 0,
  'TFE Flow Viewer',
  '**TFE Flow Viewer** (`SY043`) is an interactive visual guide to the Trade Flow Engine. Route: `/console/sys/tfe-flow`.

**Tabs:**
- **Pipeline & Status Machines** — 7-object document pipeline (Lead → Quotation → Order → Invoice → Handover → Warranty → Survey) plus Sell Lead. Click any object to see its status machine, transitions, guards, and RPCs.
- **Acquisition Funnel** — Sell Lead system: state machine diagram, Comm Center V2 email pipeline (SL-001 to SL-005), token map, ref code generation, file map.
- **DES Shop E-Commerce** — Cart → Order → Payment → Fulfilment → Shipment pipeline with Mollie/Sendcloud integrations, email triggers, and screen/API maps.
- **Short-Link Attribution** — link tracking and attribution flow.
- **Guard Rails** — RPC-enforced status changes, audit trail, adjacency tables, OLS vehicle locking, customer approvals, doc-flow integrity.
- **Doc-Flow Relations** — converted, replaced, spawned, reversed, partial relation types.

**Cross-links:** SY034 Documentation Browser links visual flow docs to SY043 via `VISUAL_FLOW_MAP` (trade-flow-engine, sell-lead-acquisition, desshop-commerce, shortlink-attribution).',
  'SYS', ARRAY['SY043']);

SELECT _tmp_doc_upsert('screen', 'SY043', 'reference', 1,
  'Business objects modeled',
  '**TFE Pipeline (7 objects):**
- `crm_leads` (Lead) — CRM module, field: stage
- `sal_quotations` (Quotation) — SAL module, field: status
- `sal_orders` (Order) — SAL module, field: status
- `fin_invoices` (Invoice) — FIN module, field: status
- `sal_handovers` (Handover) — SAL module, field: status
- `sal_warranties` (Warranty) — POST module, field: status
- `sal_surveys` (Survey) — POST module, field: status

**Sell Lead (standalone):** `sell_leads` — SAL module, field: status. State machine enforced at app layer, not via RPC guards.

**DES Shop Pipeline (5 objects):**
- `shop_carts` (Cart), `shop_orders` (Order), `shop_payments` (Payment), `shop_allocations` (Fulfilment), `shop_shipments` (Shipment) — SHP module

**No dedicated API** — SY043 is a purely client-side visualization. SQL mapping associates it with sell-leads API routes.',
  'SYS', ARRAY['SY043']);

-- Platform — i18n (2 docs)
SELECT _tmp_doc_upsert('platform', 'platform-i18n', 'overview', 0,
  'Internationalization — Portal & Console',
  '**i18n architecture** uses `next-intl` with centralized message files under `messages/{lang}.json`.

**Supported locales (10):** en, nl, de, fr, tr, ro, bg, el, es, it
**Config:** `i18n/config.ts` registers all 10 locales with display labels.

**Console:** nav labels use `tn(''keyName'')`, group labels use `tg(''groupKey'')`, screen titles under `"screens"` namespace — all in `messages/{lang}.json`.

**Portal:** portal-facing labels read from `messages/{lang}.json` under the `"portal"` namespace (61 keys). Previously had a separate `lib/portal/labels.ts` — now unified into the centralized files.',
  NULL, NULL);

SELECT _tmp_doc_upsert('platform', 'platform-i18n', 'steps', 1,
  'i18n Unification (Oct 2026)',
  '**Portal namespace added** (722b31e) — 61 portal keys added to en, nl, de, fr message files. `lib/portal/labels.ts` now reads from centralized `messages/*.json` instead of its own hardcoded map.

**10 locales complete** — Expanded tr, ro, bg, el, es, it locale files with full key coverage from en.json baseline.

**de/fr gaps filled** — 132 missing keys backfilled from en.json into de.json and fr.json.

**Files:** `messages/*.json` (12 files, ~9800 lines changed), `i18n/config.ts`, `lib/portal/labels.ts`',
  NULL, NULL);

-- Cleanup
DROP FUNCTION _tmp_doc_upsert(text, text, text, int, text, text, text, text[]);

COMMIT;
