-- Week 40 (2026-09-28 → 2026-10-05) documentation inserts
-- Generated by sync-week-enhancements-2026w40.mjs
-- Run with: bash /root/scripts/des-sql.sh --commit < scripts/_week40_docs_upsert.sql
--
-- Plain INSERTs — safe for first run. If re-running, delete existing
-- rows first: DELETE FROM bop_documentation WHERE target_id IN
-- ('SA017','SA018','BO018','BO019','SY043','platform-branding','platform-i18n')
-- AND owner = 'system' AND version = 1;

BEGIN;

-- SA017 — Buyer Inquiries: overview
INSERT INTO bop_documentation (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
VALUES ('screen', 'SA017', 'overview', 0,
  'Buyer Inquiries — Inbox',
  E'**Buyer Inquiries** (`SA017`) is the inbox for structured buyer questions submitted from desmobil listing pages. Route: `/console/sal/inquiries`.\n\nEach inquiry carries question chips (intent tags), free-text, and contact details. The list shows a **Ref** column (DM-INQ-XXXXXXXX) as the first column in orange monospace font, computed from the inquiry UUID.\n\n**Key columns:** Ref · Listing · Intent tags · Contact · Status · Received (dd-mm-yyyy HH:mm)\n\n**Statuses:** `new` → `seen` → `replied` → `closed` (or `converted` via CRM lead promotion on SA018).\n\n**API:** `GET /api/bop/sal/inquiries` — returns inquiry list with computed `ref_code` field.',
  'active', 'system', 1, 'SAL', ARRAY['SA017']);

-- SA017 — Buyer Inquiries: reference
INSERT INTO bop_documentation (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
VALUES ('screen', 'SA017', 'reference', 1,
  'APIs & data',
  E'- `GET /api/bop/sal/inquiries` — returns `dm_inquiries` rows with computed `ref_code` (DM-INQ-XXXXXXXX from UUID prefix)\n- `ref_code` is computed at API level: `DM-INQ-` + first 8 chars of UUID uppercased\n- Received date format: `dd-mm-yyyy HH:mm` (includes year)\n- Filter param: `?status=new|seen|replied|closed|converted`\n- Table: `dm_inquiries` — columns: id, listing_id, question_codes, intent_tags, free_text, contact_name, contact_email, status, locale, created_at',
  'active', 'system', 1, 'SAL', ARRAY['SA017']);

-- SA017 — Buyer Inquiries: steps
INSERT INTO bop_documentation (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
VALUES ('screen', 'SA017', 'steps', 2,
  'Recent enhancements (Oct 2026)',
  E'**DM-INQ Reference Code** (6bf9050) — Each inquiry now has a computed reference code `DM-INQ-XXXXXXXX` displayed as the first column in orange monospace. Computed from the inquiry UUID, not stored.\n\n**Date Format Fix** (fc3d83d) — Received date column now shows full year: `dd-mm-yyyy HH:mm` instead of `dd-mm HH:mm`.',
  'active', 'system', 1, 'SAL', ARRAY['SA017']);

-- SA018 — Buyer Inquiry Detail: overview
INSERT INTO bop_documentation (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
VALUES ('screen', 'SA018', 'overview', 0,
  'Buyer Inquiry Detail',
  E'**Buyer Inquiry Detail** (`SA018`) shows the full detail view for a single buyer inquiry. Route: `/console/sal/inquiries/[id]`.\n\nThe page title displays the **DM-INQ reference code** (DM-INQ-XXXXXXXX). The detail card shows:\n- Question chips with intent tags (general, b2b, inspection, logistics, technical)\n- Contact information (name, email)\n- **Acquisition source** and **traffic channel** fields\n- Free-text message\n- Status machine with transitions (new → seen → replied → closed)\n- CRM lead promotion action\n\n**API:** `GET /api/bop/sal/inquiries/[id]` — single inquiry with ref_code, acquisition_source, traffic_channel.',
  'active', 'system', 1, 'SAL', ARRAY['SA018']);

-- SA018 — Buyer Inquiry Detail: steps
INSERT INTO bop_documentation (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
VALUES ('screen', 'SA018', 'steps', 1,
  'Recent enhancements (Oct 2026)',
  E'**DM-INQ Reference Code** (6bf9050) — ref_code displayed in page title and listing card header.\n\n**Acquisition & Traffic Fields** (6bf9050) — Now shows `acquisition_source` and `traffic_channel` on the detail card, giving visibility into where the inquiry originated.',
  'active', 'system', 1, 'SAL', ARRAY['SA018']);

-- Platform — Branding: overview
INSERT INTO bop_documentation (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
VALUES ('platform', 'platform-branding', 'overview', 0,
  '2E Terminal / Code Prompt — Brand Identity',
  E'**Brand refresh (Oct 2026):** The BOP console and public site now use the **>_ des.systems** terminal-style logo concept.\n\n**Elements:**\n- Logo: `>_` prompt in brand blue (#3B82F6) + `des` in dark + `.systems` with blue dot\n- Font: **IBM Plex Mono** (loaded via `next/font/google`, CSS variable `--font-ibm-plex-mono`)\n- Tagline: `BUSINESS OPERATING PLATFORM` in tracked uppercase\n- Favicon: navy rounded square with blue `>_` prompt (SVG at `app/icon.svg`)\n- Dark/light theme support on all logo elements\n\n**Files changed:**\n- `components/Shell.tsx` — console header logo\n- `components/nav.tsx` — public site navigation logo\n- `components/footer.tsx` — public site footer logo\n- `app/icon.svg` — favicon\n- `app/layout.tsx` — IBM Plex Mono font registration',
  'active', 'system', 1, NULL, NULL);

-- BO018 — GA4 Sync: steps
INSERT INTO bop_documentation (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
VALUES ('screen', 'BO018', 'steps', 2,
  'GA4 Sync Endpoint (Oct 2026)',
  E'**New endpoint:** `POST /api/admin/ga4/sync`\n\nFetches Google Analytics 4 Data API for all tenants with `ga4_property_id` configured in `bop_tenants`, writes daily metrics to the `ga4_analytics` table.\n\n**Auth:** `x-studio-worker-secret` header\n**Params:** `?tenant_id=N` (optional, sync single tenant), `?days=30` (lookback window)\n**Mechanism:** JWT auth via Google service account (`lib/ga4-data.ts`), fetches GA4 runReport with dimensions: date, sessionDefaultChannelGrouping; metrics: sessions, activeUsers, screenPageViews, conversions, totalRevenue.\n\n**File:** `app/api/admin/ga4/sync/route.ts` + `lib/ga4-data.ts`',
  'active', 'system', 1, 'BOP', ARRAY['BO018']);

-- BO019 — Cloudflare Sync: steps
INSERT INTO bop_documentation (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
VALUES ('screen', 'BO019', 'steps', 2,
  'Cloudflare Analytics Sync Endpoint (Oct 2026)',
  E'**New endpoint:** `POST /api/admin/cloudflare/sync`\n\nFetches Cloudflare GraphQL Analytics API (`httpRequests1dGroups`) for all tenants with `cloudflare_zone_id` configured in `bop_tenants`, upserts daily metrics into `cloudflare_analytics`.\n\n**Auth:** `x-studio-worker-secret` header\n**Params:** `?tenant_id=N` (optional), `?days=30` (lookback)\n**Metrics:** requests, pageViews, threats, bandwidth, unique visitors, country breakdown, status code breakdown, content type breakdown.\n\n**File:** `app/api/admin/cloudflare/sync/route.ts`',
  'active', 'system', 1, 'BOP', ARRAY['BO019']);

-- SY043 — TFE Flow Viewer: overview
INSERT INTO bop_documentation (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
VALUES ('screen', 'SY043', 'overview', 0,
  'TFE Flow Viewer',
  E'**TFE Flow Viewer** (`SY043`) is an interactive visual guide to the Trade Flow Engine. Route: `/console/sys/tfe-flow`.\n\n**Tabs:**\n- **Pipeline & Status Machines** — 7-object document pipeline (Lead → Quotation → Order → Invoice → Handover → Warranty → Survey) plus Sell Lead.\n- **Acquisition Funnel** — Sell Lead system: state machine diagram, Comm Center V2 email pipeline (SL-001 to SL-005), token map, ref code generation, file map.\n- **DES Shop E-Commerce** — Cart → Order → Payment → Fulfilment → Shipment pipeline with Mollie/Sendcloud integrations.\n- **Short-Link Attribution** — link tracking and attribution flow.\n- **Guard Rails** — RPC-enforced status changes, audit trail, adjacency tables, OLS vehicle locking.\n- **Doc-Flow Relations** — converted, replaced, spawned, reversed, partial relation types.\n\n**Cross-links:** SY034 Documentation Browser links visual flow docs to SY043 via `VISUAL_FLOW_MAP`.',
  'active', 'system', 1, 'SYS', ARRAY['SY043']);

-- SY043 — TFE Flow Viewer: reference
INSERT INTO bop_documentation (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
VALUES ('screen', 'SY043', 'reference', 1,
  'Business objects modeled',
  E'**TFE Pipeline (7 objects):**\n- `crm_leads` (Lead) — CRM module, field: stage\n- `sal_quotations` (Quotation) — SAL module, field: status\n- `sal_orders` (Order) — SAL module, field: status\n- `fin_invoices` (Invoice) — FIN module, field: status\n- `sal_handovers` (Handover) — SAL module, field: status\n- `sal_warranties` (Warranty) — POST module, field: status\n- `sal_surveys` (Survey) — POST module, field: status\n\n**Sell Lead (standalone):** `sell_leads` — SAL module, field: status.\n\n**DES Shop Pipeline (5 objects):**\n- `shop_carts` (Cart), `shop_orders` (Order), `shop_payments` (Payment), `shop_allocations` (Fulfilment), `shop_shipments` (Shipment) — SHP module\n\n**No dedicated API** — SY043 is a purely client-side visualization.',
  'active', 'system', 1, 'SYS', ARRAY['SY043']);

-- Platform — i18n: overview
INSERT INTO bop_documentation (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
VALUES ('platform', 'platform-i18n', 'overview', 0,
  'Internationalization — Portal & Console',
  E'**i18n architecture** uses `next-intl` with centralized message files under `messages/{lang}.json`.\n\n**Supported locales (10):** en, nl, de, fr, tr, ro, bg, el, es, it\n**Config:** `i18n/config.ts` registers all 10 locales with display labels.\n\n**Console:** nav labels use `tn(''keyName'')`, group labels use `tg(''groupKey'')`, screen titles under `"screens"` namespace.\n\n**Portal:** portal-facing labels read from `messages/{lang}.json` under the `"portal"` namespace (61 keys). Previously had a separate `lib/portal/labels.ts` — now unified into the centralized files.',
  'active', 'system', 1, NULL, NULL);

-- Platform — i18n: steps
INSERT INTO bop_documentation (target_type, target_id, doc_type, seq, title, body_md, status, owner, version, module, related_screens)
VALUES ('platform', 'platform-i18n', 'steps', 1,
  'i18n Unification (Oct 2026)',
  E'**Portal namespace added** (722b31e) — 61 portal keys added to en, nl, de, fr message files.\n\n**10 locales complete** — Expanded tr, ro, bg, el, es, it locale files with full key coverage from en.json baseline.\n\n**de/fr gaps filled** — 132 missing keys backfilled from en.json into de.json and fr.json.\n\n**Files:** `messages/*.json` (12 files, ~9800 lines changed), `i18n/config.ts`, `lib/portal/labels.ts`',
  'active', 'system', 1, NULL, NULL);

COMMIT;
