// Customer-facing portal labels. The portal lives outside the [locale] tree,
// so labels are resolved from portal_clients.locale (same pattern as lib/documents/labels).

export type PortalLocale = 'en' | 'nl' | 'de' | 'fr' | 'tr';

export function toPortalLocale(raw: string | null | undefined): PortalLocale {
  const l = (raw || 'en').slice(0, 2) as PortalLocale;
  return (['en', 'nl', 'de', 'fr', 'tr'] as const).includes(l) ? l : 'en';
}

export const PORTAL_LABELS: Record<PortalLocale, Record<string, string>> = {
  en: {
    attachments: 'Attachments',
    dossierLabel: 'Dossier code',
    dossierHint: 'The short code from your e-mail link, e.g. “carisma”.',
    portalTitle: 'Client Portal',
    welcome: 'Welcome',
    loginTitle: 'Enter your access code',
    loginHint: 'You received this code by e-mail or in person. It belongs to one dossier and stays valid for 30 days on this device.',
    accessCode: 'Access code',
    open: 'Open',
    busy: 'One moment…',
    wrongCode: 'That code is not correct. Please check the code from your e-mail.',
    tooMany: 'Too many attempts. Please try again in 15 minutes.',
    expired: 'This access has expired. Please contact DES Systems for a new link.',
    linkIncomplete: 'This link is incomplete. Please use the link from your e-mail.',
    genericError: 'Something went wrong. Please try again.',
    loginHelp: 'Not working? Contact DES Systems — we will send you a new code. Please do not share the code: anyone with it can view your documents.',
    offers: 'Offers & proposals',
    documents: 'Documents',
    noOffers: 'No offers yet.',
    noDocuments: 'No documents yet.',
    version: 'Version',
    updated: 'Updated',
    validUntil: 'Valid until',
    total: 'Total',
    subtotal: 'Subtotal',
    vat: 'VAT',
    openDoc: 'Open',
    download: 'Download',
    logout: 'Sign out',
    status_draft: 'Draft',
    status_sent: 'Awaiting your response',
    status_viewed: 'Awaiting your response',
    status_changes_requested: 'Changes requested',
    status_approved: 'Approved',
    status_declined: 'Declined',
    status_withdrawn: 'Withdrawn',
    respondTitle: 'Your response',
    respondHint: 'Approve this proposal, or tell us what you would like changed — we will send an updated version.',
    approve: 'Approve proposal',
    requestChanges: 'Request changes',
    decline: 'Decline',
    commentLabel: 'Comments / requested changes',
    commentPlaceholder: 'What would you like us to adjust?',
    signerLabel: 'Your name (signature)',
    signerHint: 'By entering your name you confirm your response.',
    signerRequired: 'Please enter your name to confirm.',
    commentRequired: 'Please describe the changes you would like.',
    submit: 'Send response',
    thankYou: 'Thank you! Your response has been received.',
    versionHistory: 'Version history',
    changeNote: 'What changed',
    yourResponses: 'Your responses',
    respondedOn: 'Responded on',
    quantity: 'Qty',
    unitPrice: 'Unit price',
    description: 'Description',
    optionalItem: 'Optional',
    backToOverview: 'Back to overview',
    confidential: 'Confidential — intended only for you. This page is not indexed and only reachable with your access code.',
    poweredBy: 'Powered by DES Systems',
    questions: 'Questions? Call or e-mail us — half an hour on the phone often saves a week of e-mailing.',
  },
  nl: {
    attachments: 'Bijlagen',
    dossierLabel: 'Dossiercode',
    dossierHint: 'De korte code uit uw e-maillink, bijv. “carisma”.',
    portalTitle: 'Klantportaal',
    welcome: 'Welkom',
    loginTitle: 'Voer uw toegangscode in',
    loginHint: 'U heeft deze code per e-mail of persoonlijk ontvangen. Hij hoort bij één dossier en blijft 30 dagen geldig op dit apparaat.',
    accessCode: 'Toegangscode',
    open: 'Openen',
    busy: 'Bezig…',
    wrongCode: 'Code klopt niet. Controleer de code uit uw e-mail.',
    tooMany: 'Te veel pogingen. Probeer het over een kwartier opnieuw.',
    expired: 'Deze toegang is verlopen. Neem contact op met DES Systems voor een nieuwe link.',
    linkIncomplete: 'Deze link is onvolledig. Gebruik de link uit uw e-mail.',
    genericError: 'Er ging iets mis. Probeer het opnieuw.',
    loginHelp: 'Werkt het niet? Neem contact op met DES Systems — dan sturen we een nieuwe code. Deel de code niet: iedereen met de code kan uw documenten inzien.',
    offers: 'Offertes & voorstellen',
    documents: 'Documenten',
    noOffers: 'Nog geen offertes.',
    noDocuments: 'Nog geen documenten.',
    version: 'Versie',
    updated: 'Bijgewerkt',
    validUntil: 'Geldig tot',
    total: 'Totaal',
    subtotal: 'Subtotaal',
    vat: 'Btw',
    openDoc: 'Openen',
    download: 'Downloaden',
    logout: 'Uitloggen',
    status_draft: 'Concept',
    status_sent: 'Wacht op uw reactie',
    status_viewed: 'Wacht op uw reactie',
    status_changes_requested: 'Aanpassing gevraagd',
    status_approved: 'Akkoord',
    status_declined: 'Afgewezen',
    status_withdrawn: 'Ingetrokken',
    respondTitle: 'Uw reactie',
    respondHint: 'Keur dit voorstel goed, of laat weten wat u aangepast wilt — dan sturen we een nieuwe versie.',
    approve: 'Voorstel goedkeuren',
    requestChanges: 'Aanpassing vragen',
    decline: 'Afwijzen',
    commentLabel: 'Opmerkingen / gewenste aanpassingen',
    commentPlaceholder: 'Wat wilt u dat we aanpassen?',
    signerLabel: 'Uw naam (ondertekening)',
    signerHint: 'Met het invullen van uw naam bevestigt u uw reactie.',
    signerRequired: 'Vul uw naam in om te bevestigen.',
    commentRequired: 'Omschrijf welke aanpassing u wenst.',
    submit: 'Reactie versturen',
    thankYou: 'Dank u! Uw reactie is ontvangen.',
    versionHistory: 'Versiegeschiedenis',
    changeNote: 'Wat is er gewijzigd',
    yourResponses: 'Uw reacties',
    respondedOn: 'Gereageerd op',
    quantity: 'Aantal',
    unitPrice: 'Stukprijs',
    description: 'Omschrijving',
    optionalItem: 'Optioneel',
    backToOverview: 'Terug naar overzicht',
    confidential: 'Vertrouwelijk — alleen voor u bedoeld. Deze pagina is niet vindbaar via Google en alleen bereikbaar met uw toegangscode.',
    poweredBy: 'Powered by DES Systems',
    questions: 'Vragen? Bel of mail gerust — een half uur aan de telefoon scheelt vaak een week mailen.',
  },
  de: {
    attachments: 'Anhänge',
    dossierLabel: 'Dossiercode',
    dossierHint: 'Der kurze Code aus Ihrem E-Mail-Link, z. B. „carisma“.',
    portalTitle: 'Kundenportal',
    welcome: 'Willkommen',
    loginTitle: 'Geben Sie Ihren Zugangscode ein',
    loginHint: 'Sie haben diesen Code per E-Mail oder persönlich erhalten. Er gehört zu einem Dossier und bleibt 30 Tage auf diesem Gerät gültig.',
    accessCode: 'Zugangscode',
    open: 'Öffnen',
    busy: 'Einen Moment…',
    wrongCode: 'Der Code ist nicht korrekt. Bitte prüfen Sie den Code aus Ihrer E-Mail.',
    tooMany: 'Zu viele Versuche. Bitte versuchen Sie es in 15 Minuten erneut.',
    expired: 'Dieser Zugang ist abgelaufen. Bitte kontaktieren Sie DES Systems für einen neuen Link.',
    linkIncomplete: 'Dieser Link ist unvollständig. Bitte nutzen Sie den Link aus Ihrer E-Mail.',
    genericError: 'Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.',
    loginHelp: 'Funktioniert es nicht? Kontaktieren Sie DES Systems — wir senden Ihnen einen neuen Code. Bitte geben Sie den Code nicht weiter.',
    offers: 'Angebote & Vorschläge',
    documents: 'Dokumente',
    noOffers: 'Noch keine Angebote.',
    noDocuments: 'Noch keine Dokumente.',
    version: 'Version',
    updated: 'Aktualisiert',
    validUntil: 'Gültig bis',
    total: 'Gesamt',
    subtotal: 'Zwischensumme',
    vat: 'MwSt.',
    openDoc: 'Öffnen',
    download: 'Herunterladen',
    logout: 'Abmelden',
    status_draft: 'Entwurf',
    status_sent: 'Wartet auf Ihre Antwort',
    status_viewed: 'Wartet auf Ihre Antwort',
    status_changes_requested: 'Änderung angefragt',
    status_approved: 'Genehmigt',
    status_declined: 'Abgelehnt',
    status_withdrawn: 'Zurückgezogen',
    respondTitle: 'Ihre Antwort',
    respondHint: 'Genehmigen Sie diesen Vorschlag oder sagen Sie uns, was geändert werden soll — wir senden eine aktualisierte Version.',
    approve: 'Vorschlag genehmigen',
    requestChanges: 'Änderung anfragen',
    decline: 'Ablehnen',
    commentLabel: 'Kommentare / gewünschte Änderungen',
    commentPlaceholder: 'Was sollen wir anpassen?',
    signerLabel: 'Ihr Name (Unterschrift)',
    signerHint: 'Mit der Eingabe Ihres Namens bestätigen Sie Ihre Antwort.',
    signerRequired: 'Bitte geben Sie Ihren Namen ein.',
    commentRequired: 'Bitte beschreiben Sie die gewünschte Änderung.',
    submit: 'Antwort senden',
    thankYou: 'Vielen Dank! Ihre Antwort ist eingegangen.',
    versionHistory: 'Versionsverlauf',
    changeNote: 'Was geändert wurde',
    yourResponses: 'Ihre Antworten',
    respondedOn: 'Geantwortet am',
    quantity: 'Menge',
    unitPrice: 'Einzelpreis',
    description: 'Beschreibung',
    optionalItem: 'Optional',
    backToOverview: 'Zurück zur Übersicht',
    confidential: 'Vertraulich — nur für Sie bestimmt. Diese Seite ist nicht indexiert und nur mit Ihrem Zugangscode erreichbar.',
    poweredBy: 'Powered by DES Systems',
    questions: 'Fragen? Rufen Sie uns an oder schreiben Sie uns.',
  },
  fr: {
    attachments: 'Pièces jointes',
    dossierLabel: 'Code de dossier',
    dossierHint: 'Le code court de votre lien e-mail, p. ex. « carisma ».',
    portalTitle: 'Portail client',
    welcome: 'Bienvenue',
    loginTitle: "Saisissez votre code d'accès",
    loginHint: "Vous avez reçu ce code par e-mail ou en personne. Il correspond à un dossier et reste valable 30 jours sur cet appareil.",
    accessCode: "Code d'accès",
    open: 'Ouvrir',
    busy: 'Un instant…',
    wrongCode: "Ce code est incorrect. Vérifiez le code reçu par e-mail.",
    tooMany: 'Trop de tentatives. Réessayez dans 15 minutes.',
    expired: 'Cet accès a expiré. Contactez DES Systems pour un nouveau lien.',
    linkIncomplete: 'Ce lien est incomplet. Utilisez le lien de votre e-mail.',
    genericError: "Une erreur s'est produite. Veuillez réessayer.",
    loginHelp: 'Un problème ? Contactez DES Systems — nous vous enverrons un nouveau code. Ne partagez pas le code.',
    offers: 'Offres & propositions',
    documents: 'Documents',
    noOffers: "Pas encore d'offres.",
    noDocuments: 'Pas encore de documents.',
    version: 'Version',
    updated: 'Mis à jour',
    validUntil: "Valable jusqu'au",
    total: 'Total',
    subtotal: 'Sous-total',
    vat: 'TVA',
    openDoc: 'Ouvrir',
    download: 'Télécharger',
    logout: 'Se déconnecter',
    status_draft: 'Brouillon',
    status_sent: 'En attente de votre réponse',
    status_viewed: 'En attente de votre réponse',
    status_changes_requested: 'Modification demandée',
    status_approved: 'Approuvé',
    status_declined: 'Refusé',
    status_withdrawn: 'Retiré',
    respondTitle: 'Votre réponse',
    respondHint: 'Approuvez cette proposition ou dites-nous ce que vous souhaitez modifier — nous enverrons une version mise à jour.',
    approve: 'Approuver la proposition',
    requestChanges: 'Demander une modification',
    decline: 'Refuser',
    commentLabel: 'Commentaires / modifications souhaitées',
    commentPlaceholder: 'Que souhaitez-vous que nous ajustions ?',
    signerLabel: 'Votre nom (signature)',
    signerHint: 'En saisissant votre nom, vous confirmez votre réponse.',
    signerRequired: 'Veuillez saisir votre nom pour confirmer.',
    commentRequired: 'Veuillez décrire la modification souhaitée.',
    submit: 'Envoyer la réponse',
    thankYou: 'Merci ! Votre réponse a bien été reçue.',
    versionHistory: 'Historique des versions',
    changeNote: 'Ce qui a changé',
    yourResponses: 'Vos réponses',
    respondedOn: 'Répondu le',
    quantity: 'Qté',
    unitPrice: 'Prix unitaire',
    description: 'Description',
    optionalItem: 'Optionnel',
    backToOverview: "Retour à l'aperçu",
    confidential: "Confidentiel — destiné uniquement à vous. Cette page n'est pas indexée et uniquement accessible avec votre code d'accès.",
    poweredBy: 'Powered by DES Systems',
    questions: 'Des questions ? Appelez-nous ou écrivez-nous.',
  },
  tr: {
    attachments: 'Ekler',
    dossierLabel: 'Dosya kodu',
    dossierHint: 'E-posta bağlantınızdaki kısa kod, örn. “carisma”.',
    portalTitle: 'Müşteri Portalı',
    welcome: 'Hoş geldiniz',
    loginTitle: 'Erişim kodunuzu girin',
    loginHint: 'Bu kodu e-posta ile veya yüz yüze aldınız. Tek bir dosyaya aittir ve bu cihazda 30 gün geçerlidir.',
    accessCode: 'Erişim kodu',
    open: 'Aç',
    busy: 'Lütfen bekleyin…',
    wrongCode: 'Kod doğru değil. E-postanızdaki kodu kontrol edin.',
    tooMany: 'Çok fazla deneme. 15 dakika sonra tekrar deneyin.',
    expired: 'Bu erişimin süresi doldu. Yeni bir bağlantı için DES Systems ile iletişime geçin.',
    linkIncomplete: 'Bu bağlantı eksik. E-postanızdaki bağlantıyı kullanın.',
    genericError: 'Bir şeyler ters gitti. Lütfen tekrar deneyin.',
    loginHelp: 'Çalışmıyor mu? DES Systems ile iletişime geçin — yeni bir kod göndeririz. Kodu kimseyle paylaşmayın.',
    offers: 'Teklifler & öneriler',
    documents: 'Belgeler',
    noOffers: 'Henüz teklif yok.',
    noDocuments: 'Henüz belge yok.',
    version: 'Sürüm',
    updated: 'Güncellendi',
    validUntil: 'Geçerlilik',
    total: 'Toplam',
    subtotal: 'Ara toplam',
    vat: 'KDV',
    openDoc: 'Aç',
    download: 'İndir',
    logout: 'Çıkış yap',
    status_draft: 'Taslak',
    status_sent: 'Yanıtınız bekleniyor',
    status_viewed: 'Yanıtınız bekleniyor',
    status_changes_requested: 'Değişiklik istendi',
    status_approved: 'Onaylandı',
    status_declined: 'Reddedildi',
    status_withdrawn: 'Geri çekildi',
    respondTitle: 'Yanıtınız',
    respondHint: 'Bu teklifi onaylayın veya nelerin değişmesini istediğinizi söyleyin — güncellenmiş bir sürüm göndeririz.',
    approve: 'Teklifi onayla',
    requestChanges: 'Değişiklik iste',
    decline: 'Reddet',
    commentLabel: 'Yorumlar / istenen değişiklikler',
    commentPlaceholder: 'Neyi değiştirmemizi istersiniz?',
    signerLabel: 'Adınız (imza)',
    signerHint: 'Adınızı girerek yanıtınızı onaylamış olursunuz.',
    signerRequired: 'Onaylamak için lütfen adınızı girin.',
    commentRequired: 'Lütfen istediğiniz değişikliği açıklayın.',
    submit: 'Yanıtı gönder',
    thankYou: 'Teşekkürler! Yanıtınız alındı.',
    versionHistory: 'Sürüm geçmişi',
    changeNote: 'Neler değişti',
    yourResponses: 'Yanıtlarınız',
    respondedOn: 'Yanıt tarihi',
    quantity: 'Adet',
    unitPrice: 'Birim fiyat',
    description: 'Açıklama',
    optionalItem: 'Opsiyonel',
    backToOverview: 'Genel görünüme dön',
    confidential: 'Gizli — yalnızca size yöneliktir. Bu sayfa dizine eklenmez ve yalnızca erişim kodunuzla açılır.',
    poweredBy: 'Powered by DES Systems',
    questions: 'Sorularınız mı var? Bizi arayın veya yazın.',
  },
};

export function portalT(locale: string | null | undefined) {
  const l = toPortalLocale(locale);
  const dict = PORTAL_LABELS[l];
  return (key: string) => dict[key] ?? PORTAL_LABELS.en[key] ?? key;
}
